using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Whizbang.Core.Lenses;
using Whizbang.Core.Perspectives;

namespace Whizbang.Data.EFCore.Postgres;

/// <summary>
/// Extension property for selecting InMemory as the EF Core driver for Whizbang perspectives.
/// Uses C# 14 extension blocks to add .InMemory property to IDriverOptions.
/// Only visible when Whizbang.Data.EFCore.Postgres package is referenced.
/// </summary>
public static class InMemoryDriverExtensions {
  /// <summary>
  /// Extension block for IDriverOptions.
  /// Adds .InMemory property for selecting EF Core InMemory provider as the database driver.
  /// </summary>
  extension(IDriverOptions options) {
    /// <summary>
    /// Configures EF Core InMemory provider as the database driver for perspectives.
    /// Registers IPerspectiveStore&lt;T&gt; and ILensQuery&lt;T&gt; for all discovered perspective models.
    /// Uses InMemoryUpsertStrategy for fast, isolated testing.
    /// </summary>
    /// <returns>A WhizbangPerspectiveBuilder for further configuration.</returns>
    /// <exception cref="InvalidOperationException">Thrown if InMemory driver is used with non-EF Core storage.</exception>
    /// <example>
    /// <code>
    /// services
    ///     .AddWhizbangPerspectives()
    ///     .WithEFCore&lt;MyDbContext&gt;()
    ///     .WithDriver.InMemory;
    /// </code>
    /// </example>
    public WhizbangPerspectiveBuilder InMemory {
      get {
        if (options is not EFCoreDriverSelector selector) {
          throw new InvalidOperationException(
              "InMemory driver can only be used with EF Core storage. " +
              "Call .WithEFCore<TDbContext>() before .WithDriver.InMemory");
        }

        RegisterEFCoreInfrastructure(
            selector.Services,
            selector.DbContextType,
            new InMemoryUpsertStrategy()
        );

        return new WhizbangPerspectiveBuilder(selector.Services);
      }
    }
  }

  /// <summary>
  /// Registers EF Core infrastructure (IPerspectiveStore and ILensQuery) for all discovered models.
  /// Uses source-generated EFCoreRegistrationMetadata to discover model types at compile time.
  /// </summary>
  private static void RegisterEFCoreInfrastructure(
      IServiceCollection services,
      Type dbContextType,
      IDbUpsertStrategy upsertStrategy) {

    // Register all discovered perspective models
    // EFCoreRegistrationMetadata is generated by EFCoreServiceRegistrationGenerator
    foreach (var model in EFCoreRegistrationMetadata.Models) {
      RegisterPerspectiveStore(services, dbContextType, model, upsertStrategy);
      RegisterLensQuery(services, dbContextType, model);
    }
  }

  /// <summary>
  /// Registers IPerspectiveStore&lt;TModel&gt; for a specific model type.
  /// </summary>
  private static void RegisterPerspectiveStore(
      IServiceCollection services,
      Type dbContextType,
      ModelTypeInfo model,
      IDbUpsertStrategy upsertStrategy) {

    var storeInterfaceType = typeof(IPerspectiveStore<>).MakeGenericType(model.Type);

    services.AddScoped(storeInterfaceType, sp => {
      var context = (DbContext)sp.GetRequiredService(dbContextType);
      var storeType = typeof(EFCorePostgresPerspectiveStore<>).MakeGenericType(model.Type);
      return Activator.CreateInstance(storeType, context, model.TableName, upsertStrategy)
          ?? throw new InvalidOperationException($"Failed to create {storeType.Name}");
    });
  }

  /// <summary>
  /// Registers ILensQuery&lt;TModel&gt; for a specific model type.
  /// </summary>
  private static void RegisterLensQuery(
      IServiceCollection services,
      Type dbContextType,
      ModelTypeInfo model) {

    var queryInterfaceType = typeof(ILensQuery<>).MakeGenericType(model.Type);

    services.AddScoped(queryInterfaceType, sp => {
      var context = (DbContext)sp.GetRequiredService(dbContextType);
      var queryType = typeof(EFCorePostgresLensQuery<>).MakeGenericType(model.Type);
      return Activator.CreateInstance(queryType, context, model.TableName)
          ?? throw new InvalidOperationException($"Failed to create {queryType.Name}");
    });
  }
}
