#region HEADER
// <auto-generated/>
// Generated at: __TIMESTAMP__
// This file was generated by Whizbang.Transports.HotChocolate.Generators
// DO NOT EDIT - Changes will be overwritten
#endregion
#nullable enable

using HotChocolate;
using HotChocolate.Data;
using HotChocolate.Types;
using Microsoft.Extensions.DependencyInjection;
using Whizbang.Core.Lenses;

namespace __NAMESPACE__;

/// <summary>
/// Generated GraphQL query type extension for Whizbang Lenses.
/// Provides query fields for each lens marked with [GraphQLLens].
/// </summary>
[ExtendObjectType(typeof(Query))]
public sealed class WhizbangLensQueryTypeExtension {
  #region LENS_QUERY_METHODS
  // Lens query methods will be generated here
  #endregion
}

/// <summary>
/// Extension methods for registering generated Whizbang lens types with HotChocolate.
/// </summary>
public static class WhizbangLensRegistrationExtensions {
  /// <summary>
  /// Registers all generated Whizbang lens query type extensions with HotChocolate.
  /// Call this after AddWhizbangLenses() in your service configuration.
  /// </summary>
  /// <param name="builder">The HotChocolate request executor builder.</param>
  /// <returns>The builder for chaining.</returns>
  public static IRequestExecutorBuilder AddWhizbangLensQueries(
      this IRequestExecutorBuilder builder) {
    builder.AddTypeExtension<WhizbangLensQueryTypeExtension>();

    #region LENS_TYPE_REGISTRATIONS
    // Additional type registrations will be generated here
    #endregion

    return builder;
  }
}

/// <summary>
/// Diagnostic information about Whizbang GraphQL lens discovery.
/// </summary>
public static class WhizbangGraphQLDiagnostics {
  /// <summary>
  /// Gets the name of the generator that produced this code.
  /// </summary>
  public static string GeneratorName => "GraphQLLensTypeGenerator";

  /// <summary>
  /// Gets the timestamp when the code was generated.
  /// </summary>
  public static string GeneratedTimestamp => "__TIMESTAMP__";

  /// <summary>
  /// Gets the total count of discovered lenses.
  /// </summary>
  public static int DiscoveredLensCount => __LENS_COUNT__;

  #region LENS_INFO_PROPERTIES
  // Individual lens info properties will be generated here
  #endregion
}
