#region HEADER
// <auto-generated/>
// Generated at: __TIMESTAMP__
// This file was generated by Whizbang.Transports.HotChocolate.Generators
// DO NOT EDIT - Changes will be overwritten
#endregion
#nullable enable

using HotChocolate;
using HotChocolate.Types;
using Whizbang.Core;
using Whizbang.Transports.HotChocolate;
using Whizbang.Transports.Mutations;

namespace __NAMESPACE__;

#region MUTATION_CLASSES
// Mutation classes will be generated here
#endregion

/// <summary>
/// Diagnostic information about Whizbang GraphQL mutation discovery.
/// </summary>
public static class WhizbangGraphQLMutationDiagnostics {
  /// <summary>
  /// Gets the name of the generator that produced this code.
  /// </summary>
  public static string GeneratorName => "GraphQLMutationTypeGenerator";

  /// <summary>
  /// Gets the timestamp when the code was generated.
  /// </summary>
  public static string GeneratedTimestamp => "__TIMESTAMP__";

  /// <summary>
  /// Gets the total count of discovered mutations.
  /// </summary>
  public static int DiscoveredMutationCount => __MUTATION_COUNT__;

  #region MUTATION_INFO_PROPERTIES
  // Individual mutation info properties will be generated here
  #endregion
}
