using System;
using System.Threading.Tasks;
using Npgsql;
using TUnit.Assertions.Extensions;
using TUnit.Core;

namespace Whizbang.Data.Dapper.Postgres.Tests;

/// <summary>
/// That every worklist-driven backfill moves its rows once, stops, and never re-reads the table.
/// </summary>
/// <remarks>
/// <para>
/// Five migrations claim slices of a large table. Convergence over a handful of rows cannot tell a
/// linear pass from a quadratic one, because at that size a sequential scan is free — which is how a
/// quadratic slice reached a deployed store and spent hours on work that takes minutes. What
/// separates them is rows read sequentially across the whole pass: a worklist reads a few hundred, a
/// predicate re-evaluated per slice reads the table once per slice.
/// </para>
/// <para>
/// Each test restores the shape the migration expects. The fixture applies every migration, so by the
/// time a test runs the columns these backfills exist to fill are already filled, already NOT NULL,
/// or already dropped, and each worklist has been dropped behind it. Without restoring that shape the
/// only reachable path is the replay guard, which returns zero without touching a row.
/// </para>
/// </remarks>
public class MigrationWorklistBatchTests : PostgresTestBase {

  private const int ROWS = 4000;
  private const int LIMIT = 100;

  private static async Task _execAsync(NpgsqlConnection c, string sql) {
    await using var cmd = c.CreateCommand();
    cmd.CommandText = sql;
    await cmd.ExecuteNonQueryAsync();
  }

  private static async Task<long> _scalarAsync(NpgsqlConnection c, string sql) {
    await using var cmd = c.CreateCommand();
    cmd.CommandText = sql;
    var v = await cmd.ExecuteScalarAsync();
    return v is null or DBNull ? 0L : Convert.ToInt64(v, System.Globalization.CultureInfo.InvariantCulture);
  }

  private static string _seqTupSql(params string[] tables) =>
    "SELECT coalesce(sum(seq_tup_read),0)::bigint FROM pg_stat_user_tables WHERE relname IN ("
    + string.Join(",", Array.ConvertAll(tables, t => $"'{t}'")) + ");";

  private sealed record PassResult(int Calls, long SequentialRows);

  /// <summary>Drives one backfill to exhaustion, measuring what it read sequentially.</summary>
  private static async Task<PassResult> _runPassAsync(
      NpgsqlConnection c, string function, string seqTupSql) {
    await Task.Delay(1500);
    await _execAsync(c, "SELECT pg_stat_clear_snapshot();");
    var before = await _scalarAsync(c, seqTupSql);

    var calls = 0;
    long moved;
    do {
      moved = await _scalarAsync(c, $"SELECT public.{function}({LIMIT});");
      await Assert.That(moved).IsLessThanOrEqualTo(LIMIT);
      calls++;
      await Assert.That(calls).IsLessThanOrEqualTo(ROWS / LIMIT + 10);
    } while (moved > 0);

    await Task.Delay(1500);
    await _execAsync(c, "SELECT pg_stat_clear_snapshot();");
    return new PassResult(calls, await _scalarAsync(c, seqTupSql) - before);
  }

  private static async Task _assertWorklistInstalledAsync(NpgsqlConnection c, string function) {
    // Measuring the wrong function is the easiest way to reach a confident wrong conclusion.
    var ok = await _scalarAsync(c, $@"
      SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE p.proname = '{function}' AND n.nspname = 'public' AND p.prosrc LIKE '%_todo%';");
    await Assert.That(ok).IsEqualTo(1L)
      .Because($"{function} must be the worklist version, or this measures other code");
  }

  private static async Task _assertLinearAsync(long sequentialRows) =>
    // A worklist reads a few hundred rows this way across the whole pass. The predicate design this
    // replaces read the table once per slice.
    await Assert.That(sequentialRows).IsLessThan(ROWS * 2L);

  // ── 008: normalize message types in the association registry ──────────────────────────────────
  [Test]
  public async Task TheMessageTypeNormalizationReadsItsWorklistNotTheRegistryAsync() {
    await using var c = new NpgsqlConnection(ConnectionString);
    await c.OpenAsync();
    await _assertWorklistInstalledAsync(c, "wh_backfill_normalized_message_type_batch");
    try {
      await _execAsync(c, @"
        DELETE FROM public.wh_message_associations;
        DROP TABLE IF EXISTS public.wh_msgassoc_norm_todo;
        DROP TABLE IF EXISTS public.wh_msgassoc_norm_cursor;
        CREATE TABLE public.wh_msgassoc_norm_todo (
          seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id UUID NOT NULL);
        CREATE TABLE public.wh_msgassoc_norm_cursor (
          only_row BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (only_row), last_seq BIGINT NOT NULL DEFAULT 0);
        INSERT INTO public.wh_msgassoc_norm_cursor VALUES (TRUE, 0);");
      await _execAsync(c, $@"
        INSERT INTO public.wh_message_associations
          (message_type, association_type, target_name, service_name, normalized_message_type,
           created_at, updated_at)
        SELECT 'Some.Type' || g || ', Some.Assembly', 'perspective', 'T' || g, 'a-service',
               NULL, NOW(), NOW()
        FROM generate_series(1, {ROWS}) g;
        INSERT INTO public.wh_msgassoc_norm_todo (id)
        SELECT id FROM public.wh_message_associations WHERE normalized_message_type IS NULL ORDER BY ctid;
        ANALYZE public.wh_message_associations; ANALYZE public.wh_msgassoc_norm_todo;");

      var r = await _runPassAsync(c, "wh_backfill_normalized_message_type_batch",
        _seqTupSql("wh_message_associations", "wh_msgassoc_norm_todo", "wh_msgassoc_norm_cursor"));
      Console.WriteLine($"[008] calls={r.Calls} seq_tup_read={r.SequentialRows}");

      await Assert.That(await _scalarAsync(c,
        "SELECT count(*) FROM public.wh_message_associations WHERE normalized_message_type IS NULL;"))
        .IsEqualTo(0L);
      await _assertLinearAsync(r.SequentialRows);
    } finally {
      await _execAsync(c, @"
        DELETE FROM public.wh_message_associations;
        DROP TABLE IF EXISTS public.wh_msgassoc_norm_todo;
        DROP TABLE IF EXISTS public.wh_msgassoc_norm_cursor;");
    }
  }

  // ── 046: fill the inbox's source columns ──────────────────────────────────────────────────────
  [Test]
  public async Task TheInboxSourceBackfillReadsItsWorklistNotTheInboxAsync() {
    await using var c = new NpgsqlConnection(ConnectionString);
    await c.OpenAsync();
    await _assertWorklistInstalledAsync(c, "wh_backfill_inbox_source_columns_batch");
    try {
      await _execAsync(c, @"
        DELETE FROM public.wh_inbox;
        ALTER TABLE public.wh_inbox ALTER COLUMN source_service_id DROP NOT NULL;
        ALTER TABLE public.wh_inbox ALTER COLUMN source_commit_sequence DROP NOT NULL;
        DROP TABLE IF EXISTS public.wh_inbox_source_todo;
        DROP TABLE IF EXISTS public.wh_inbox_source_cursor;
        CREATE TABLE public.wh_inbox_source_todo (
          seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, message_id UUID NOT NULL);
        CREATE TABLE public.wh_inbox_source_cursor (
          only_row BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (only_row), last_seq BIGINT NOT NULL DEFAULT 0);
        INSERT INTO public.wh_inbox_source_cursor VALUES (TRUE, 0);
        INSERT INTO public.wh_service_config (single_row, service_id)
        VALUES (TRUE, gen_random_uuid()) ON CONFLICT DO NOTHING;");
      await _execAsync(c, $@"
        INSERT INTO public.wh_inbox
          (message_id, handler_name, message_type, event_data, metadata,
           source_service_id, source_commit_sequence)
        SELECT gen_random_uuid(), 'h', 'Some.Type, Some.Assembly', '{{}}'::jsonb, '{{}}'::jsonb,
               NULL, NULL
        FROM generate_series(1, {ROWS}) g;
        INSERT INTO public.wh_inbox_source_todo (message_id)
        SELECT message_id FROM public.wh_inbox
        WHERE source_service_id IS NULL OR source_commit_sequence IS NULL ORDER BY ctid;
        ANALYZE public.wh_inbox; ANALYZE public.wh_inbox_source_todo;");

      var r = await _runPassAsync(c, "wh_backfill_inbox_source_columns_batch",
        _seqTupSql("wh_inbox", "wh_inbox_source_todo", "wh_inbox_source_cursor"));
      Console.WriteLine($"[046] calls={r.Calls} seq_tup_read={r.SequentialRows}");

      await Assert.That(await _scalarAsync(c,
        "SELECT count(*) FROM public.wh_inbox WHERE source_service_id IS NULL OR source_commit_sequence IS NULL;"))
        .IsEqualTo(0L);
      await _assertLinearAsync(r.SequentialRows);
    } finally {
      await _execAsync(c, @"
        DELETE FROM public.wh_inbox;
        DROP TABLE IF EXISTS public.wh_inbox_source_todo;
        DROP TABLE IF EXISTS public.wh_inbox_source_cursor;");
    }
  }

  // ── 063: normalize aggregate type names on the event store ────────────────────────────────────
  [Test]
  public async Task TheAggregateTypeNormalizationReadsItsWorklistNotTheStoreAsync() {
    await using var c = new NpgsqlConnection(ConnectionString);
    await c.OpenAsync();
    await _assertWorklistInstalledAsync(c, "wh_normalize_aggregate_type_batch");
    try {
      await _execAsync(c, @"
        DELETE FROM public.wh_event_store;
        DROP TABLE IF EXISTS public.wh_aggtype_norm_todo;
        DROP TABLE IF EXISTS public.wh_aggtype_norm_cursor;
        CREATE TABLE public.wh_aggtype_norm_todo (
          seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id UUID NOT NULL);
        CREATE TABLE public.wh_aggtype_norm_cursor (
          only_row BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (only_row), last_seq BIGINT NOT NULL DEFAULT 0);
        INSERT INTO public.wh_aggtype_norm_cursor VALUES (TRUE, 0);
        -- The guard reads this: at version 3 there is nothing to normalize.
        INSERT INTO public.wh_settings (setting_key, setting_value, value_type, description)
        VALUES ('clr_type_name_format_version', '2', 'integer', 'test')
        ON CONFLICT (setting_key) DO UPDATE SET setting_value = '2';");
      await _execAsync(c, $@"
        INSERT INTO public.wh_event_store
          (event_id, stream_id, aggregate_id, aggregate_type, event_type, version, created_at)
        SELECT gen_random_uuid(), gen_random_uuid(), gen_random_uuid(),
               'Stale.Name',                       -- differs from split_part(event_type, ',', 1)
               'Some.Event' || g || ', Some.Assembly', g, NOW()
        FROM generate_series(1, {ROWS}) g;
        INSERT INTO public.wh_aggtype_norm_todo (event_id)
        SELECT event_id FROM public.wh_event_store
        WHERE event_type NOT LIKE '%[[%'
          AND aggregate_type IS DISTINCT FROM split_part(event_type, ',', 1) ORDER BY ctid;
        ANALYZE public.wh_event_store; ANALYZE public.wh_aggtype_norm_todo;");

      var r = await _runPassAsync(c, "wh_normalize_aggregate_type_batch",
        _seqTupSql("wh_event_store", "wh_aggtype_norm_todo", "wh_aggtype_norm_cursor"));
      Console.WriteLine($"[063] calls={r.Calls} seq_tup_read={r.SequentialRows}");

      await Assert.That(await _scalarAsync(c, @"
        SELECT count(*) FROM public.wh_event_store
        WHERE event_type NOT LIKE '%[[%'
          AND aggregate_type IS DISTINCT FROM split_part(event_type, ',', 1);")).IsEqualTo(0L);
      await _assertLinearAsync(r.SequentialRows);
    } finally {
      await _execAsync(c, @"
        DELETE FROM public.wh_event_store;
        DROP TABLE IF EXISTS public.wh_aggtype_norm_todo;
        DROP TABLE IF EXISTS public.wh_aggtype_norm_cursor;");
    }
  }

  // ── 162: seed the inbox work-state side table ─────────────────────────────────────────────────
  [Test]
  public async Task TheInboxStateSeedReadsItsWorklistNotTheInboxAsync() {
    await using var c = new NpgsqlConnection(ConnectionString);
    await c.OpenAsync();
    await _assertWorklistInstalledAsync(c, "wh_seed_inbox_state_batch");
    try {
      await _execAsync(c, @"
        DELETE FROM public.wh_inbox_state;
        DELETE FROM public.wh_inbox;
        -- The backfill's guard looks for the columns 162 moves out to the side table, so the
        -- pre-migration shape has to come back or the only reachable path is that guard.
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS instance_id UUID;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS lease_expiry TIMESTAMPTZ;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS attempts INTEGER DEFAULT 0;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS scheduled_for TIMESTAMPTZ;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS failure_reason INTEGER DEFAULT 0;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS error TEXT;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS chain_emitted_at TIMESTAMPTZ;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS status INTEGER DEFAULT 0;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS received_at TIMESTAMPTZ DEFAULT NOW();
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS partition_number INTEGER DEFAULT 0;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 0;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS is_event BOOLEAN DEFAULT TRUE;
        DROP TABLE IF EXISTS public.wh_inbox_state_seed_todo;
        DROP TABLE IF EXISTS public.wh_inbox_state_seed_cursor;
        CREATE TABLE public.wh_inbox_state_seed_todo (
          seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, message_id UUID NOT NULL);
        CREATE TABLE public.wh_inbox_state_seed_cursor (
          only_row BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (only_row), last_seq BIGINT NOT NULL DEFAULT 0);
        INSERT INTO public.wh_inbox_state_seed_cursor VALUES (TRUE, 0);");
      await _execAsync(c, $@"
        INSERT INTO public.wh_inbox
          (message_id, handler_name, message_type, event_data, metadata, source_service_id)
        SELECT gen_random_uuid(), 'h', 'Some.Type, Some.Assembly', '{{}}'::jsonb, '{{}}'::jsonb,
               gen_random_uuid()
        FROM generate_series(1, {ROWS}) g;
        INSERT INTO public.wh_inbox_state_seed_todo (message_id)
        SELECT i.message_id FROM public.wh_inbox i
        WHERE NOT EXISTS (SELECT 1 FROM public.wh_inbox_state s WHERE s.message_id = i.message_id)
        ORDER BY i.ctid;
        ANALYZE public.wh_inbox; ANALYZE public.wh_inbox_state_seed_todo;");

      var r = await _runPassAsync(c, "wh_seed_inbox_state_batch",
        _seqTupSql("wh_inbox", "wh_inbox_state", "wh_inbox_state_seed_todo", "wh_inbox_state_seed_cursor"));
      Console.WriteLine($"[162] calls={r.Calls} seq_tup_read={r.SequentialRows}");

      await Assert.That(await _scalarAsync(c, "SELECT count(*) FROM public.wh_inbox_state;"))
        .IsEqualTo((long)ROWS);
      await _assertLinearAsync(r.SequentialRows);
    } finally {
      await _execAsync(c, @"
        DELETE FROM public.wh_inbox_state;
        DELETE FROM public.wh_inbox;
        -- The backfill's guard looks for the columns 162 moves out to the side table, so the
        -- pre-migration shape has to come back or the only reachable path is that guard.
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS instance_id UUID;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS lease_expiry TIMESTAMPTZ;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS attempts INTEGER DEFAULT 0;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS scheduled_for TIMESTAMPTZ;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS failure_reason INTEGER DEFAULT 0;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS error TEXT;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS chain_emitted_at TIMESTAMPTZ;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS status INTEGER DEFAULT 0;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS received_at TIMESTAMPTZ DEFAULT NOW();
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS partition_number INTEGER DEFAULT 0;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 0;
        ALTER TABLE public.wh_inbox ADD COLUMN IF NOT EXISTS is_event BOOLEAN DEFAULT TRUE;
        DROP TABLE IF EXISTS public.wh_inbox_state_seed_todo;
        DROP TABLE IF EXISTS public.wh_inbox_state_seed_cursor;");
    }
  }
}
