codecov:
  # Wait for the quality job to upload coverage before reporting status
  notify:
    after_n_builds: 1
    wait_for_ci: true

coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
        if_ci_failed: error
    patch:
      default:
        target: 85%
        threshold: 0%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "**/*.Generated.cs"
  - "**/.whizbang-generated/**"
  - "samples/**"
  - "benchmarks/**"
  - "test-diagnostics/**"
  - "src/Whizbang.Testing/Containers/**"
