coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
        if_ci_failed: error
    patch:
      default:
        target: 100%
        threshold: 0%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "**/*.Generated.cs"
  - "**/.whizbang-generated/**"
  - "**/samples/**"
  - "**/benchmarks/**"
  - "**/test-diagnostics/**"
