using Whizbang.Core.Observability;
using Whizbang.Core.ValueObjects;

namespace Whizbang.Core.AutoPopulate;

/// <summary>
/// Interface for source-generated populators that set auto-populate properties
/// directly on message records using <c>with</c> expressions.
/// </summary>
/// <remarks>
/// <para>
/// Implementations are generated by the source generator for each assembly
/// containing record types with auto-populate attributes. Each implementation
/// uses record <c>with</c> expressions for AOT-compatible, zero-reflection population.
/// </para>
/// <para>
/// Three lifecycle phases are supported:
/// <list type="bullet">
/// <item><see cref="TryPopulateSent"/> - At dispatch time (timestamps, context, service, identifiers)</item>
/// <item><see cref="TryPopulateQueued"/> - When written to outbox (QueuedAt timestamps)</item>
/// <item><see cref="TryPopulateDelivered"/> - When received from transport (DeliveredAt timestamps)</item>
/// </list>
/// </para>
/// </remarks>
/// <docs>extending/attributes/auto-populate</docs>
public interface IAutoPopulatePopulator {
  /// <summary>
  /// Populates SentAt-phase properties on a message record.
  /// Returns a new record instance with populated values, or null if this populator doesn't handle the type.
  /// </summary>
  /// <param name="message">The message to populate.</param>
  /// <param name="hop">The message hop containing timestamp, scope, and service info.</param>
  /// <param name="messageId">The message ID for identifier population.</param>
  /// <returns>A new message instance with populated properties, or null if not handled.</returns>
  object? TryPopulateSent(object message, MessageHop hop, MessageId messageId);

  /// <summary>
  /// Populates QueuedAt-phase properties on a message record.
  /// Returns a new record instance with the QueuedAt timestamp, or null if this populator doesn't handle the type.
  /// </summary>
  /// <param name="message">The message to populate.</param>
  /// <param name="timestamp">The timestamp when the message was queued.</param>
  /// <returns>A new message instance with populated properties, or null if not handled.</returns>
  object? TryPopulateQueued(object message, DateTimeOffset timestamp);

  /// <summary>
  /// Populates DeliveredAt-phase properties on a message record.
  /// Returns a new record instance with the DeliveredAt timestamp, or null if this populator doesn't handle the type.
  /// </summary>
  /// <param name="message">The message to populate.</param>
  /// <param name="timestamp">The timestamp when the message was delivered.</param>
  /// <returns>A new message instance with populated properties, or null if not handled.</returns>
  object? TryPopulateDelivered(object message, DateTimeOffset timestamp);
}
