namespace Whizbang.Core.AutoPopulate;

/// <summary>
/// Interface for auto-populate registries generated per assembly.
/// </summary>
/// <remarks>
/// <para>
/// Implementations are generated by the source generator for each assembly
/// containing message types with auto-populate attributes. Each implementation
/// provides the registrations for its assembly's message types.
/// </para>
/// <para>
/// Implementations self-register via [ModuleInitializer] at assembly load time.
/// </para>
/// </remarks>
/// <docs>attributes/auto-populate</docs>
public interface IAutoPopulateRegistry {
  /// <summary>
  /// Gets registrations for a specific message type.
  /// </summary>
  /// <param name="messageType">The message type to get registrations for.</param>
  /// <returns>
  /// All auto-populate registrations for the message type, or empty if the type
  /// has no auto-populated properties in this assembly.
  /// </returns>
  IEnumerable<AutoPopulateRegistration> GetRegistrationsFor(Type messageType);
}
