namespace Whizbang.Core.Messaging;

/// <summary>
/// Persistence surface for the Whizbang internal DLQ (<c>wh_dead_letters</c>). Workers that
/// detect a permanent failure (attempts exceeded, validation error, etc.) call
/// <see cref="MoveAsync"/> to atomically snapshot the failing row into the DLQ and remove
/// it from the source work table.
/// </summary>
/// <docs>operations/dead-letter-queue/internal-dlq</docs>
/// <tests>tests/Whizbang.Core.Tests/Workers/OutboxPublishWorkerDlqPromotionTests.cs:SingularPublish_AttemptsAtCap_PublishFails_PromotesToDlqAsync</tests>
/// <tests>tests/Whizbang.Core.Tests/Workers/OutboxPublishWorkerDlqPromotionTests.cs:SingularPublish_AtCap_NoDeadLetterStoreWired_FallsBackToFailureChannelAsync</tests>
/// <tests>tests/Whizbang.Data.EFCore.Postgres.Tests/ScopedEFCoreDeadLetterStoreTests.cs:MoveAsync_OutboxRow_AdapterOpensScopeAndDelegatesToInnerStoreAsync</tests>
public interface IDeadLetterStore {
  /// <summary>
  /// Atomically moves a failing row from its source work table (<c>wh_outbox</c>,
  /// <c>wh_inbox</c>, or <c>wh_perspective_events</c>) into <c>wh_dead_letters</c> with a
  /// full forensic snapshot. Idempotent: returns <c>null</c> when the source row is already
  /// gone (covers the race where two failure paths try to dead-letter the same row).
  /// </summary>
  /// <param name="deadLetterId">Generated by the caller (UUIDv7 via TrackedGuid).</param>
  /// <param name="sourceTable">Source table name: <c>wh_outbox</c>, <c>wh_inbox</c>, or
  /// <c>wh_perspective_events</c>.</param>
  /// <param name="sourceId">Source row's primary key (message_id or event_work_id).</param>
  /// <param name="failureReason">A <see cref="MessageFailureReason"/> value identifying
  /// why this row dead-lettered.</param>
  /// <param name="errorText">Human-readable error context (truncated to a reasonable
  /// length by the caller).</param>
  /// <param name="instanceId">The instance that decided to dead-letter (for forensics).</param>
  /// <param name="generation">Current generation tag — e.g. <c>"0.502.0-alpha.1+consumer-1.42.0"</c>.
  /// Used by the recovery worker's generation-replay logic.</param>
  /// <param name="ct">Cancellation.</param>
  /// <returns>The <paramref name="deadLetterId"/> on success, <c>null</c> when the source
  /// row was already gone (no-op).</returns>
  Task<Guid?> MoveAsync(
    Guid deadLetterId,
    string sourceTable,
    Guid sourceId,
    MessageFailureReason failureReason,
    string? errorText,
    Guid instanceId,
    string generation,
    CancellationToken ct = default);
}

/// <summary>
/// Identifies the source work table for a dead-letter operation. String constants used as
/// SQL parameters — avoids enum-to-string conversion at the boundary.
/// </summary>
public static class DeadLetterSourceTable {
#pragma warning disable CA1707
  /// <summary>Outbox-side failure (publish to transport failed beyond retry).</summary>
  public const string OUTBOX = "wh_outbox";
  /// <summary>Inbox-side failure (handler dispatch failed beyond retry).</summary>
  public const string INBOX = "wh_inbox";
  /// <summary>Perspective-event failure (projection apply failed beyond retry).</summary>
  public const string PERSPECTIVE_EVENTS = "wh_perspective_events";
#pragma warning restore CA1707
}
