using TUnit.Assertions;
using TUnit.Assertions.Extensions;
using TUnit.Core;

#pragma warning disable CA1707 // Identifiers should not contain underscores (test method names use underscores by convention)

namespace Whizbang.Transports.AzureServiceBus.Tests;

/// <summary>
/// Unit tests for SQL filter pattern matching.
/// These tests verify that the wildcard pattern translation works correctly
/// and that generated patterns will match expected Subject values.
/// </summary>
/// <remarks>
/// The Azure Service Bus SqlFilter uses SQL LIKE patterns:
/// - % matches zero or more characters
/// - _ matches exactly one character
///
/// RabbitMQ-style patterns are translated:
/// - # → %
/// - * → %
/// </remarks>
public class SqlFilterPatternMatchingTests {

  // ========================================
  // PATTERN TRANSLATION TESTS
  // ========================================
  // These tests verify that RabbitMQ-style patterns are correctly
  // translated to SQL LIKE patterns

  [Test]
  public async Task TranslatePattern_HashWildcard_TranslatesToPercentAsync() {
    // Arrange - RabbitMQ-style pattern with #
    var rabbitPattern = "jdx.contracts.chat.#";

    // Act
    var sqlPattern = _translateToSqlPattern(rabbitPattern);

    // Assert
    await Assert.That(sqlPattern).IsEqualTo("jdx.contracts.chat.%");
  }

  [Test]
  public async Task TranslatePattern_AsteriskWildcard_TranslatesToPercentAsync() {
    // Arrange - RabbitMQ-style pattern with *
    var rabbitPattern = "jdx.contracts.chat.*";

    // Act
    var sqlPattern = _translateToSqlPattern(rabbitPattern);

    // Assert
    await Assert.That(sqlPattern).IsEqualTo("jdx.contracts.chat.%");
  }

  [Test]
  public async Task TranslatePattern_StandaloneHash_TranslatesToPercentAsync() {
    // Arrange - Single # (match all)
    var rabbitPattern = "#";

    // Act
    var sqlPattern = _translateToSqlPattern(rabbitPattern);

    // Assert
    await Assert.That(sqlPattern).IsEqualTo("%");
  }

  [Test]
  public async Task TranslatePattern_MultiplePatterns_GeneratesOrExpressionAsync() {
    // Arrange - Multiple routing patterns
    var patterns = new[] {
      "whizbang.core.commands.system.#",
      "jdx.contracts.chat.#",
      "jdx.contracts.facts.#"
    };

    // Act - Build SQL expression
    var sqlExpression = _buildSqlFilterExpression(patterns);

    // Assert
    await Assert.That(sqlExpression).IsEqualTo(
      "[Subject] LIKE 'whizbang.core.commands.system.%' OR " +
      "[Subject] LIKE 'jdx.contracts.chat.%' OR " +
      "[Subject] LIKE 'jdx.contracts.facts.%'"
    );
  }

  // ========================================
  // PATTERN MATCHING SIMULATION TESTS
  // ========================================
  // These tests verify that the SQL LIKE pattern would match the Subject
  // values generated by TransportPublishStrategy

  [Test]
  public async Task SqlLikeMatch_CommandRoutingKey_MatchesPatternAsync() {
    // Arrange
    // TransportPublishStrategy generates: jdx.contracts.chat.activitytrackedcommand
    // SqlFilter pattern is: [Subject] LIKE 'jdx.contracts.chat.%'
    var subject = "jdx.contracts.chat.activitytrackedcommand";
    var pattern = "jdx.contracts.chat.%";

    // Act
    var matches = _sqlLikeMatches(subject, pattern);

    // Assert
    await Assert.That(matches).IsTrue()
      .Because("Command routing key should match SqlFilter pattern");
  }

  [Test]
  public async Task SqlLikeMatch_NestedClassCommand_MatchesPatternAsync() {
    // Arrange
    // TransportPublishStrategy generates: jdx.contracts.chat.chatconversationscontracts+createcommand
    // SqlFilter pattern is: [Subject] LIKE 'jdx.contracts.chat.%'
    var subject = "jdx.contracts.chat.chatconversationscontracts+createcommand";
    var pattern = "jdx.contracts.chat.%";

    // Act
    var matches = _sqlLikeMatches(subject, pattern);

    // Assert
    await Assert.That(matches).IsTrue()
      .Because("Nested class command routing key should match SqlFilter pattern");
  }

  [Test]
  public async Task SqlLikeMatch_EventRoutingKey_MatchesPatternAsync() {
    // Arrange
    // TransportPublishStrategy generates: myapp.orders.events.ordercreatedevent
    // SqlFilter pattern is: [Subject] LIKE 'myapp.orders.events.%'
    var subject = "myapp.orders.events.ordercreatedevent";
    var pattern = "myapp.orders.events.%";

    // Act
    var matches = _sqlLikeMatches(subject, pattern);

    // Assert
    await Assert.That(matches).IsTrue()
      .Because("Event routing key should match SqlFilter pattern");
  }

  [Test]
  public async Task SqlLikeMatch_DifferentNamespace_DoesNotMatchAsync() {
    // Arrange - Chat pattern should NOT match auth namespace
    var subject = "jdx.contracts.auth.authcontracts+createtenantcommand";
    var pattern = "jdx.contracts.chat.%";

    // Act
    var matches = _sqlLikeMatches(subject, pattern);

    // Assert
    await Assert.That(matches).IsFalse()
      .Because("Auth namespace should not match chat filter pattern");
  }

  [Test]
  public async Task SqlLikeMatch_DefaultSubject_DoesNotMatchNamespacePatternAsync() {
    // Arrange - This was the bug! Without RoutingKey, Subject defaulted to "message"
    var subject = "message"; // Default when RoutingKey is null
    var pattern = "jdx.contracts.chat.%";

    // Act
    var matches = _sqlLikeMatches(subject, pattern);

    // Assert
    await Assert.That(matches).IsFalse()
      .Because("Default 'message' Subject should NOT match namespace patterns - this was the bug!");
  }

  [Test]
  public async Task SqlLikeMatch_MultiplePatterns_MatchesAnyAsync() {
    // Arrange - Service subscribed to multiple namespaces
    var subject = "jdx.contracts.facts.factcreatedevent";
    var patterns = new[] {
      "whizbang.core.commands.system.%",
      "jdx.contracts.chat.%",
      "jdx.contracts.facts.%"
    };

    // Act
    var matches = patterns.Any(p => _sqlLikeMatches(subject, p));

    // Assert
    await Assert.That(matches).IsTrue()
      .Because("Subject should match at least one of the subscribed patterns");
  }

  [Test]
  public async Task SqlLikeMatch_SystemCommand_MatchesSystemPatternAsync() {
    // Arrange - System commands are always included
    var subject = "whizbang.core.commands.system.healthcheckcommand";
    var pattern = "whizbang.core.commands.system.%";

    // Act
    var matches = _sqlLikeMatches(subject, pattern);

    // Assert
    await Assert.That(matches).IsTrue()
      .Because("System commands should match system command pattern");
  }

  [Test]
  public async Task SqlLikeMatch_CaseInsensitive_MatchesAsync() {
    // Arrange - Routing keys are lowercased by TransportPublishStrategy
    var subject = "jdx.contracts.chat.createcommand";
    var pattern = "jdx.contracts.chat.%";

    // Act
    var matches = _sqlLikeMatches(subject, pattern);

    // Assert
    await Assert.That(matches).IsTrue()
      .Because("Pattern matching should work with lowercase routing keys");
  }

  // ========================================
  // END-TO-END PATTERN VERIFICATION TESTS
  // ========================================
  // These tests verify the complete flow from namespace to pattern to match

  [Test]
  public async Task EndToEnd_ChatService_ReceivesChatCommandsAsync() {
    // Arrange - Chat service subscribes to these patterns
    var chatServicePatterns = new[] {
      "whizbang.core.commands.system.#",
      "jdx.contracts.chat.#"
    };

    // Commands that should be received by Chat service
    var chatCommands = new[] {
      "jdx.contracts.chat.activitytrackedcommand",
      "jdx.contracts.chat.chatconversationscontracts+createcommand",
      "whizbang.core.commands.system.healthcheckcommand"
    };

    // Commands that should NOT be received by Chat service
    var otherCommands = new[] {
      "jdx.contracts.auth.authcontracts+createtenantcommand",
      "jdx.contracts.bff.createpageviewcommand",
      "message" // Default when RoutingKey is null
    };

    // Act & Assert - All chat commands should match
    var sqlPatterns = chatServicePatterns.Select(_translateToSqlPattern).ToList();

    foreach (var cmd in chatCommands) {
      var matches = sqlPatterns.Any(p => _sqlLikeMatches(cmd, p));
      await Assert.That(matches).IsTrue()
        .Because($"Chat service SHOULD receive command: {cmd}");
    }

    // Act & Assert - Other commands should NOT match
    foreach (var cmd in otherCommands) {
      var matches = sqlPatterns.Any(p => _sqlLikeMatches(cmd, p));
      await Assert.That(matches).IsFalse()
        .Because($"Chat service should NOT receive command: {cmd}");
    }
  }

  [Test]
  public async Task EndToEnd_BFFService_ReceivesBFFCommandsAsync() {
    // Arrange - BFF service subscribes to these patterns
    var bffServicePatterns = new[] {
      "whizbang.core.commands.system.#",
      "jdx.contracts.bff.#",
      "jdx.contracts.systemseeding.#"
    };

    // Commands that should be received by BFF service
    var bffCommands = new[] {
      "jdx.contracts.bff.createpageviewcommand",
      "jdx.contracts.systemseeding.seedcompletecommand",
      "whizbang.core.commands.system.healthcheckcommand"
    };

    // Commands that should NOT be received by BFF service
    var otherCommands = new[] {
      "jdx.contracts.chat.activitytrackedcommand",
      "jdx.contracts.auth.authcontracts+createtenantcommand"
    };

    // Act & Assert
    var sqlPatterns = bffServicePatterns.Select(_translateToSqlPattern).ToList();

    foreach (var cmd in bffCommands) {
      var matches = sqlPatterns.Any(p => _sqlLikeMatches(cmd, p));
      await Assert.That(matches).IsTrue()
        .Because($"BFF service SHOULD receive command: {cmd}");
    }

    foreach (var cmd in otherCommands) {
      var matches = sqlPatterns.Any(p => _sqlLikeMatches(cmd, p));
      await Assert.That(matches).IsFalse()
        .Because($"BFF service should NOT receive command: {cmd}");
    }
  }

  // ========================================
  // HELPER METHODS
  // ========================================

  /// <summary>
  /// Translates RabbitMQ-style wildcard patterns to SQL LIKE patterns.
  /// This mirrors the logic in AzureServiceBusTransport._applyRoutingPatternFilterAsync
  /// </summary>
  private static string _translateToSqlPattern(string rabbitPattern) {
    return rabbitPattern
      .Replace(".#", ".%")
      .Replace(".*", ".%")
      .Replace("#", "%")
      .Replace("*", "%");
  }

  /// <summary>
  /// Builds the SQL filter expression for multiple patterns.
  /// This mirrors the logic in AzureServiceBusTransport._applyRoutingPatternFilterAsync
  /// </summary>
  private static string _buildSqlFilterExpression(IEnumerable<string> patterns) {
    var likePatterns = patterns
      .Select(_translateToSqlPattern)
      .Select(p => $"[Subject] LIKE '{p}'");
    return string.Join(" OR ", likePatterns);
  }

  /// <summary>
  /// Simulates SQL LIKE pattern matching.
  /// Note: This is a simplified implementation that handles % wildcard only.
  /// </summary>
  private static bool _sqlLikeMatches(string subject, string pattern) {
    // Handle simple % patterns (matches zero or more characters)
    if (pattern.EndsWith('%')) {
      var prefix = pattern[..^1];
      return subject.StartsWith(prefix, StringComparison.Ordinal);
    }

    // Exact match if no wildcard
    return string.Equals(subject, pattern, StringComparison.Ordinal);
  }
}
