using System.Text;
using Microsoft.CodeAnalysis;

namespace Whizbang.Generators;

/// <summary>
/// Generates the central diagnostics infrastructure for collecting
/// and displaying build-time diagnostic information from all generators.
/// </summary>
[Generator]
public class DiagnosticsGenerator : IIncrementalGenerator {
  public void Initialize(IncrementalGeneratorInitializationContext context) {
    // Register a single output that generates the diagnostics infrastructure
    context.RegisterPostInitializationOutput(ctx => {
      ctx.AddSource("WhizbangDiagnostics.g.cs", GenerateDiagnosticsInfrastructure());
    });
  }

  private static string GenerateDiagnosticsInfrastructure() {
    var sb = new StringBuilder();

    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine();
    sb.AppendLine("using System;");
    sb.AppendLine("using System.Collections.Generic;");
    sb.AppendLine("using System.Linq;");
    sb.AppendLine();
    sb.AppendLine("namespace Whizbang.Core.Generated {");
    sb.AppendLine();

    // DiagnosticCategory enum
    sb.AppendLine("    /// <summary>");
    sb.AppendLine("    /// Categories for diagnostic information from source generators.");
    sb.AppendLine("    /// </summary>");
    sb.AppendLine("    [Flags]");
    sb.AppendLine("    public enum DiagnosticCategory {");
    sb.AppendLine("        /// <summary>No category</summary>");
    sb.AppendLine("        None = 0,");
    sb.AppendLine("        /// <summary>Receptor discovery and registration diagnostics</summary>");
    sb.AppendLine("        ReceptorDiscovery = 1 << 0,");
    sb.AppendLine("        /// <summary>Dispatcher generation diagnostics</summary>");
    sb.AppendLine("        Dispatcher = 1 << 1,");
    sb.AppendLine("        /// <summary>Event handling diagnostics</summary>");
    sb.AppendLine("        EventHandling = 1 << 2,");
    sb.AppendLine("        /// <summary>All diagnostic categories</summary>");
    sb.AppendLine("        All = ReceptorDiscovery | Dispatcher | EventHandling");
    sb.AppendLine("    }");
    sb.AppendLine();

    // DiagnosticEntry record
    sb.AppendLine("    /// <summary>");
    sb.AppendLine("    /// Represents a diagnostic entry captured at build time.");
    sb.AppendLine("    /// </summary>");
    sb.AppendLine("    public record DiagnosticEntry(");
    sb.AppendLine("        string GeneratorName,");
    sb.AppendLine("        string Timestamp,");
    sb.AppendLine("        DiagnosticCategory Category,");
    sb.AppendLine("        string Message");
    sb.AppendLine("    );");
    sb.AppendLine();

    // WhizbangDiagnostics class
    sb.AppendLine("    /// <summary>");
    sb.AppendLine("    /// Central diagnostics aggregator for all Whizbang generators.");
    sb.AppendLine("    /// Collects diagnostic information captured at build time.");
    sb.AppendLine("    /// </summary>");
    sb.AppendLine("    public static class WhizbangDiagnostics {");
    sb.AppendLine("        private static readonly List<DiagnosticEntry> _entries = new();");
    sb.AppendLine("        private static readonly object _lock = new();");
    sb.AppendLine();

    sb.AppendLine("        /// <summary>");
    sb.AppendLine("        /// Adds a diagnostic entry to the collection.");
    sb.AppendLine("        /// This is called during static initialization by each generator.");
    sb.AppendLine("        /// </summary>");
    sb.AppendLine("        public static void AddEntry(DiagnosticEntry entry) {");
    sb.AppendLine("            lock (_lock) {");
    sb.AppendLine("                _entries.Add(entry);");
    sb.AppendLine("            }");
    sb.AppendLine("        }");
    sb.AppendLine();

    sb.AppendLine("        /// <summary>");
    sb.AppendLine("        /// Gets diagnostic information from all generators.");
    sb.AppendLine("        /// This information was captured at build time.");
    sb.AppendLine("        /// </summary>");
    sb.AppendLine("        /// <param name=\"categories\">Filter diagnostics by category. Defaults to All.</param>");
    sb.AppendLine("        /// <param name=\"printToConsole\">If true, prints the diagnostics to console. Defaults to true.</param>");
    sb.AppendLine("        /// <returns>Formatted diagnostic information as a string.</returns>");
    sb.AppendLine("        public static string Diagnostics(DiagnosticCategory categories = DiagnosticCategory.All, bool printToConsole = true) {");
    sb.AppendLine("            var filteredEntries = _entries.Where(e => (e.Category & categories) != 0).ToList();");
    sb.AppendLine();
    sb.AppendLine("            if (filteredEntries.Count == 0) {");
    sb.AppendLine("                var emptyMessage = \"No diagnostic information available for the specified categories.\";");
    sb.AppendLine("                if (printToConsole) {");
    sb.AppendLine("                    Console.WriteLine(emptyMessage);");
    sb.AppendLine("                }");
    sb.AppendLine("                return emptyMessage;");
    sb.AppendLine("            }");
    sb.AppendLine();
    sb.AppendLine("            var output = new System.Text.StringBuilder();");
    sb.AppendLine("            output.AppendLine(\"═══════════════════════════════════════════════════════════════\");");
    sb.AppendLine("            output.AppendLine(\"Whizbang Source Generators - Build Diagnostics\");");
    sb.AppendLine("            if (categories != DiagnosticCategory.All) {");
    sb.AppendLine("                output.AppendLine($\"Categories: {categories}\");");
    sb.AppendLine("            }");
    sb.AppendLine("            output.AppendLine(\"═══════════════════════════════════════════════════════════════\");");
    sb.AppendLine("            output.AppendLine($\"Total Generators: {filteredEntries.Count}\");");
    sb.AppendLine("            output.AppendLine(\"───────────────────────────────────────────────────────────────\");");
    sb.AppendLine("            output.AppendLine();");
    sb.AppendLine();
    sb.AppendLine("            foreach (var entry in filteredEntries) {");
    sb.AppendLine("                output.AppendLine($\"[{entry.GeneratorName}]\");");
    sb.AppendLine("                output.AppendLine($\"  Timestamp: {entry.Timestamp}\");");
    sb.AppendLine("                output.AppendLine($\"  Category:  {entry.Category}\");");
    sb.AppendLine("                output.AppendLine($\"  {entry.Message}\");");
    sb.AppendLine("                output.AppendLine();");
    sb.AppendLine("            }");
    sb.AppendLine();
    sb.AppendLine("            output.AppendLine(\"═══════════════════════════════════════════════════════════════\");");
    sb.AppendLine();
    sb.AppendLine("            var result = output.ToString();");
    sb.AppendLine("            if (printToConsole) {");
    sb.AppendLine("                Console.Write(result);");
    sb.AppendLine("            }");
    sb.AppendLine("            return result;");
    sb.AppendLine("        }");
    sb.AppendLine();
    sb.AppendLine("        /// <summary>");
    sb.AppendLine("        /// Prints all collected diagnostic information from all generators.");
    sb.AppendLine("        /// This is a convenience method that calls Diagnostics(printToConsole: true).");
    sb.AppendLine("        /// </summary>");
    sb.AppendLine("        [Obsolete(\"Use Diagnostics() instead. This method will be removed in a future version.\")]");
    sb.AppendLine("        public static void PrintDiagnostics() {");
    sb.AppendLine("            Diagnostics(printToConsole: true);");
    sb.AppendLine("        }");
    sb.AppendLine("    }");
    sb.AppendLine("}");

    return sb.ToString();
  }
}
