using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Whizbang.Generators.Utilities;

namespace Whizbang.Generators;

/// <summary>
/// Generates an AOT-safe <c>IMessageTypeCatalog</c> implementation listing every concrete
/// <c>IMessage</c> and <c>IPerspectiveFor&lt;&gt;</c> type in the consumer assembly with its
/// kind and optional pinned_id.
/// </summary>
/// <remarks>
/// Feeds <c>IMessageTypeRegistryPopulator</c> (Phase 3b) and the rename tool (Phase 5).
/// Independent of <c>PinnedIdRegistryGenerator</c> for cache isolation — pinned and
/// unpinned types both land in this catalog, so a change to one [PinnedId] here does
/// not invalidate the pinned-id-only registry's cache.
/// </remarks>
[Generator]
public class MessageTypeCatalogGenerator : IIncrementalGenerator {
  /// <inheritdoc/>
  public void Initialize(IncrementalGeneratorInitializationContext context) {
    var entries = context.SyntaxProvider.CreateSyntaxProvider(
        predicate: static (node, _) =>
            node is ClassDeclarationSyntax
                 or RecordDeclarationSyntax
                 or StructDeclarationSyntax,
        transform: static (ctx, ct) => _extractEntry(ctx, ct)
    ).Where(static info => info is not null);

    var combined = context.CompilationProvider.Combine(entries.Collect());

    context.RegisterSourceOutput(
        combined,
        static (ctx, data) => {
          var compilation = data.Left;
          var infos = data.Right;
          _generateCatalog(ctx, compilation, infos!);
        }
    );
  }

  private static MessageTypeCatalogEntryInfo? _extractEntry(
      GeneratorSyntaxContext context,
      System.Threading.CancellationToken cancellationToken) {
    var typeDeclaration = (TypeDeclarationSyntax)context.Node;
    var semanticModel = context.SemanticModel;

    if (semanticModel.GetDeclaredSymbol(typeDeclaration, cancellationToken) is not INamedTypeSymbol typeSymbol) {
      return null;
    }

    if (typeSymbol.IsAbstract) {
      return null;
    }

    if (typeSymbol.DeclaredAccessibility != Accessibility.Public) {
      return null;
    }

    var isEvent = TypeNameHelper.ImplementsInterface(typeSymbol, StandardInterfaceNames.I_EVENT);
    var isCommand = TypeNameHelper.ImplementsInterface(typeSymbol, StandardInterfaceNames.I_COMMAND);
    var isMessage = isEvent || isCommand || TypeNameHelper.ImplementsInterface(typeSymbol, StandardInterfaceNames.I_MESSAGE);

    var isPerspective = TypeNameHelper.ImplementsGenericInterface(
        typeSymbol,
        StandardInterfaceNames.I_PERSPECTIVE_FOR) ||
      TypeNameHelper.ImplementsGenericInterface(
        typeSymbol,
        StandardInterfaceNames.I_PERSPECTIVE_WITH_ACTIONS_FOR);

    if (!isMessage && !isPerspective) {
      return null;
    }

    var fullTypeName = TypeNameHelper.GetFullyQualifiedName(typeSymbol);
    var clrTypeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));

    var messageKind = isCommand ? "command" : "event";
    var kind = isPerspective ? "perspective" : messageKind;

    var pinnedIdAttribute = typeSymbol.GetAttributes().FirstOrDefault(attr =>
        attr.AttributeClass is not null &&
        TypeNameHelper.GetFullyQualifiedName(attr.AttributeClass) == StandardInterfaceNames.PINNED_ID_ATTRIBUTE);

    string? pinnedId = null;
    if (pinnedIdAttribute is not null &&
        pinnedIdAttribute.ConstructorArguments.Length > 0 &&
        pinnedIdAttribute.ConstructorArguments[0].Value is string pinnedIdValue &&
        !string.IsNullOrWhiteSpace(pinnedIdValue)) {
      pinnedId = pinnedIdValue;
    }

    return new MessageTypeCatalogEntryInfo(
        TypeName: fullTypeName,
        ClrTypeName: clrTypeName,
        Kind: kind,
        PinnedId: pinnedId
    );
  }

  private static void _generateCatalog(
      SourceProductionContext context,
      Compilation compilation,
      ImmutableArray<MessageTypeCatalogEntryInfo> infos) {

    if (infos.IsEmpty) {
      return;
    }

    var assemblyName = compilation.AssemblyName ?? "UnknownAssembly";
    var namespaceName = $"{assemblyName}.Generated";

    var ordered = infos.OrderBy(i => i.TypeName, System.StringComparer.Ordinal).ToList();

    var source = new StringBuilder();
    source.AppendLine("// <auto-generated/>");
    source.AppendLine($"// Generated by MessageTypeCatalogGenerator at {System.DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
    source.AppendLine("// DO NOT EDIT - Changes will be overwritten");
    source.AppendLine("#nullable enable");
    source.AppendLine();
    source.AppendLine("using System;");
    source.AppendLine("using System.Collections.Generic;");
    source.AppendLine("using Microsoft.Extensions.DependencyInjection;");
    source.AppendLine("using Whizbang.Core;");
    source.AppendLine();
    source.AppendLine($"namespace {namespaceName};");
    source.AppendLine();

    source.AppendLine("/// <summary>");
    source.AppendLine($"/// Auto-generated catalog of {ordered.Count} concrete IMessage / IPerspectiveFor&lt;&gt; type(s).");
    source.AppendLine("/// Provides zero-reflection enumeration for the type registry populator and rename tool.");
    source.AppendLine("/// </summary>");
    source.AppendLine("public sealed class GeneratedMessageTypeCatalog : IMessageTypeCatalog {");
    source.AppendLine();

    source.AppendLine("  private static readonly IReadOnlyList<MessageTypeCatalogEntry> _all = new MessageTypeCatalogEntry[] {");
    foreach (var info in ordered) {
      var pinnedIdLiteral = info.PinnedId is null ? "null" : $"\"{info.PinnedId}\"";
      source.AppendLine($"    new(typeof({info.TypeName}), \"{info.ClrTypeName}\", \"{info.Kind}\", {pinnedIdLiteral}),");
    }
    source.AppendLine("  };");
    source.AppendLine();

    source.AppendLine("  /// <inheritdoc/>");
    source.AppendLine("  public IReadOnlyList<MessageTypeCatalogEntry> GetAll() => _all;");
    source.AppendLine("}");
    source.AppendLine();

    source.AppendLine("/// <summary>");
    source.AppendLine("/// Module initializer that wires GeneratedMessageTypeCatalog into AddWhizbang().");
    source.AppendLine("/// </summary>");
    source.AppendLine("internal static class MessageTypeCatalogModuleInitializer {");
    source.AppendLine("  [System.Runtime.CompilerServices.ModuleInitializer]");
    source.AppendLine("  internal static void Initialize() {");
    source.AppendLine("    ServiceRegistrationCallbacks.MessageTypeCatalog = static services =>");
    source.AppendLine("      services.AddSingleton<IMessageTypeCatalog, GeneratedMessageTypeCatalog>();");
    source.AppendLine("  }");
    source.AppendLine("}");

    context.AddSource("MessageTypeCatalog.g.cs", source.ToString());
  }
}

/// <summary>
/// Value type containing information about a discovered catalog entry.
/// Uses value equality for incremental generator caching.
/// </summary>
internal sealed record MessageTypeCatalogEntryInfo(
    string TypeName,
    string ClrTypeName,
    string Kind,
    string? PinnedId
);
