using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Whizbang.Generators.Utilities;

namespace Whizbang.Generators;

/// <summary>
/// Generates an AOT-safe, zero-reflection <c>IPinnedIdRegistry</c> implementation by
/// discovering <c>[PinnedId]</c> attributes on concrete <c>IMessage</c> and
/// <c>IPerspectiveFor&lt;&gt;</c> types.
/// </summary>
[Generator]
public class PinnedIdRegistryGenerator : IIncrementalGenerator {
  /// <inheritdoc/>
  public void Initialize(IncrementalGeneratorInitializationContext context) {
    var pinnedTypes = context.SyntaxProvider.CreateSyntaxProvider(
        predicate: static (node, _) =>
            node is ClassDeclarationSyntax
                 or RecordDeclarationSyntax
                 or StructDeclarationSyntax,
        transform: static (ctx, ct) => _extractPinnedInfo(ctx, ct)
    ).Where(static info => info is not null);

    var combined = context.CompilationProvider.Combine(pinnedTypes.Collect());

    context.RegisterSourceOutput(
        combined,
        static (ctx, data) => {
          var compilation = data.Left;
          var infos = data.Right;
          _generateRegistry(ctx, compilation, infos!);
        }
    );
  }

  private static PinnedIdInfo? _extractPinnedInfo(
      GeneratorSyntaxContext context,
      System.Threading.CancellationToken cancellationToken) {
    var typeDeclaration = (TypeDeclarationSyntax)context.Node;
    var semanticModel = context.SemanticModel;

    if (semanticModel.GetDeclaredSymbol(typeDeclaration, cancellationToken) is not INamedTypeSymbol typeSymbol) {
      return null;
    }

    if (typeSymbol.IsAbstract) {
      return null;
    }

    if (typeSymbol.DeclaredAccessibility != Accessibility.Public) {
      return null;
    }

    var isMessage =
        TypeNameHelper.ImplementsInterface(typeSymbol, StandardInterfaceNames.I_EVENT) ||
        TypeNameHelper.ImplementsInterface(typeSymbol, StandardInterfaceNames.I_COMMAND) ||
        TypeNameHelper.ImplementsInterface(typeSymbol, StandardInterfaceNames.I_MESSAGE);

    var isPerspective = TypeNameHelper.ImplementsGenericInterface(
        typeSymbol,
        StandardInterfaceNames.I_PERSPECTIVE_FOR) ||
      TypeNameHelper.ImplementsGenericInterface(
        typeSymbol,
        StandardInterfaceNames.I_PERSPECTIVE_WITH_ACTIONS_FOR);

    if (!isMessage && !isPerspective) {
      return null;
    }

    var pinnedIdAttribute = typeSymbol.GetAttributes()
        .FirstOrDefault(attr =>
            attr.AttributeClass is not null &&
            TypeNameHelper.GetFullyQualifiedName(attr.AttributeClass) == StandardInterfaceNames.PINNED_ID_ATTRIBUTE);

    if (pinnedIdAttribute is null) {
      return null;
    }

    if (pinnedIdAttribute.ConstructorArguments.Length == 0 ||
        pinnedIdAttribute.ConstructorArguments[0].Value is not string pinnedId ||
        string.IsNullOrWhiteSpace(pinnedId)) {
      return null;
    }

    var messageKind = TypeNameHelper.ImplementsInterface(typeSymbol, StandardInterfaceNames.I_COMMAND)
        ? "command"
        : "event";
    var kind = isPerspective ? "perspective" : messageKind;

    return new PinnedIdInfo(
        TypeName: TypeNameHelper.GetFullyQualifiedName(typeSymbol),
        PinnedId: pinnedId,
        Kind: kind
    );
  }

  private static void _generateRegistry(
      SourceProductionContext context,
      Compilation compilation,
      ImmutableArray<PinnedIdInfo> infos) {

    if (infos.IsEmpty) {
      return;
    }

    var assemblyName = compilation.AssemblyName ?? "UnknownAssembly";
    var namespaceName = $"{assemblyName}.Generated";

    var ordered = infos.OrderBy(i => i.TypeName, System.StringComparer.Ordinal).ToList();

    var source = new StringBuilder();
    source.AppendLine("// <auto-generated/>");
    source.AppendLine($"// Generated by PinnedIdRegistryGenerator ({Whizbang.Generators.Shared.Utilities.TemplateUtilities.GetDeterministicBuildStamp(typeof(PinnedIdRegistryGenerator).Assembly)})");
    source.AppendLine("// DO NOT EDIT - Changes will be overwritten");
    source.AppendLine("#nullable enable");
    source.AppendLine();
    source.AppendLine("using System;");
    source.AppendLine("using System.Collections.Generic;");
    source.AppendLine("using Microsoft.Extensions.DependencyInjection;");
    source.AppendLine("using Whizbang.Core;");
    source.AppendLine();
    source.AppendLine($"namespace {namespaceName};");
    source.AppendLine();

    source.AppendLine("/// <summary>");
    source.AppendLine($"/// Auto-generated pinned-id registry for {ordered.Count} type(s).");
    source.AppendLine("/// Provides zero-reflection lookup for the stable type identity system.");
    source.AppendLine("/// </summary>");
    source.AppendLine("public sealed class GeneratedPinnedIdRegistry : IPinnedIdRegistry {");
    source.AppendLine();

    source.AppendLine("  private static readonly IReadOnlyList<(Type Type, string PinnedId)> _all = new (Type, string)[] {");
    foreach (var info in ordered) {
      source.AppendLine($"    (typeof({info.TypeName}), \"{info.PinnedId}\"),");
    }
    source.AppendLine("  };");
    source.AppendLine();

    source.AppendLine("  /// <inheritdoc/>");
    source.AppendLine("  public string? GetPinnedId(Type type) {");
    foreach (var info in ordered) {
      source.AppendLine($"    if (type == typeof({info.TypeName})) return \"{info.PinnedId}\";");
    }
    source.AppendLine("    return null;");
    source.AppendLine("  }");
    source.AppendLine();

    source.AppendLine("  /// <inheritdoc/>");
    source.AppendLine("  public IReadOnlyList<(Type Type, string PinnedId)> GetAll() => _all;");
    source.AppendLine("}");
    source.AppendLine();

    source.AppendLine("/// <summary>");
    source.AppendLine("/// Extension methods for registering the generated pinned-id registry.");
    source.AppendLine("/// </summary>");
    source.AppendLine("public static class PinnedIdRegistryExtensions {");
    source.AppendLine("  /// <summary>");
    source.AppendLine($"  /// Registers GeneratedPinnedIdRegistry with {ordered.Count} type(s) as a singleton IPinnedIdRegistry.");
    source.AppendLine("  /// Called automatically by AddWhizbang() via a module initializer, but may be invoked");
    source.AppendLine("  /// directly when configuring DI without calling AddWhizbang().");
    source.AppendLine("  /// </summary>");
    source.AppendLine("  public static IServiceCollection AddPinnedIdRegistry(");
    source.AppendLine("      this IServiceCollection services) {");
    source.AppendLine("    services.AddSingleton<IPinnedIdRegistry, GeneratedPinnedIdRegistry>();");
    source.AppendLine("    return services;");
    source.AppendLine("  }");
    source.AppendLine("}");
    source.AppendLine();

    source.AppendLine("/// <summary>");
    source.AppendLine("/// Module initializer that wires GeneratedPinnedIdRegistry into AddWhizbang().");
    source.AppendLine("/// Fires when the consumer assembly loads, so AddWhizbang() registers IPinnedIdRegistry");
    source.AppendLine("/// automatically with no explicit call from the consumer.");
    source.AppendLine("/// </summary>");
    source.AppendLine("internal static class PinnedIdRegistryModuleInitializer {");
    source.AppendLine("  [System.Runtime.CompilerServices.ModuleInitializer]");
    source.AppendLine("  internal static void Initialize() {");
    source.AppendLine("    ServiceRegistrationCallbacks.PinnedIdRegistry = static services =>");
    source.AppendLine("      services.AddSingleton<IPinnedIdRegistry, GeneratedPinnedIdRegistry>();");
    source.AppendLine("  }");
    source.AppendLine("}");

    context.AddSource("PinnedIdRegistry.g.cs", source.ToString());
  }
}

/// <summary>
/// Value type containing information about a discovered pinned type.
/// Uses value equality for incremental generator caching.
/// </summary>
internal sealed record PinnedIdInfo(
    string TypeName,
    string PinnedId,
    string Kind
);
