using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Whizbang.Generators.Utilities;

namespace Whizbang.Generators;

/// <summary>
/// Slice 5 source-generator integration. Discovers concrete classes that implement
/// <c>Whizbang.Core.Messaging.IRawReceptor</c> in the consumer assembly and emits a
/// module initializer that registers them with DI plus a singleton
/// <c>RawReceptorRegistry</c>.
/// </summary>
/// <remarks>
/// Independent of <c>ReceptorDiscoveryGenerator</c> for cache isolation and complexity
/// containment — adding raw-receptor work to the existing 1800-line generator would risk
/// regressions in critical typed-receptor infrastructure.
/// </remarks>
[Generator]
public class RawReceptorDiscoveryGenerator : IIncrementalGenerator {
  /// <inheritdoc/>
  public void Initialize(IncrementalGeneratorInitializationContext context) {
    var entries = context.SyntaxProvider.CreateSyntaxProvider(
        predicate: static (node, _) =>
            node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 },
        transform: static (ctx, ct) => _extractEntry(ctx, ct)
    ).Where(static info => info is not null);

    var combined = context.CompilationProvider.Combine(entries.Collect());

    context.RegisterSourceOutput(
        combined,
        static (ctx, data) => {
          var compilation = data.Left;
          var infos = data.Right;
          _generate(ctx, compilation, infos!);
        }
    );
  }

  private static RawReceptorInfo? _extractEntry(
      GeneratorSyntaxContext context,
      System.Threading.CancellationToken cancellationToken) {
    var typeDeclaration = (ClassDeclarationSyntax)context.Node;
    var semanticModel = context.SemanticModel;

    if (semanticModel.GetDeclaredSymbol(typeDeclaration, cancellationToken) is not INamedTypeSymbol typeSymbol) {
      return null;
    }

    if (typeSymbol.IsAbstract || typeSymbol.DeclaredAccessibility != Accessibility.Public) {
      return null;
    }

    if (!TypeNameHelper.ImplementsInterface(typeSymbol, StandardInterfaceNames.I_RAW_RECEPTOR)) {
      return null;
    }

    var fullTypeName = TypeNameHelper.GetFullyQualifiedName(typeSymbol);
    return new RawReceptorInfo(TypeName: fullTypeName);
  }

  private static void _generate(
      SourceProductionContext context,
      Compilation compilation,
      ImmutableArray<RawReceptorInfo> infos) {
    if (infos.IsEmpty) {
      return;
    }

    var assemblyName = compilation.AssemblyName ?? "UnknownAssembly";
    var namespaceName = $"{assemblyName}.Generated";
    var ordered = infos.OrderBy(i => i.TypeName, System.StringComparer.Ordinal).ToList();

    var source = new StringBuilder();
    source.AppendLine("// <auto-generated/>");
    source.AppendLine($"// Generated by RawReceptorDiscoveryGenerator at {System.DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
    source.AppendLine("// DO NOT EDIT - Changes will be overwritten");
    source.AppendLine("#nullable enable");
    source.AppendLine();
    source.AppendLine("using System.Runtime.CompilerServices;");
    source.AppendLine("using Microsoft.Extensions.DependencyInjection;");
    source.AppendLine("using Whizbang.Core;");
    source.AppendLine("using Whizbang.Core.Messaging;");
    source.AppendLine();
    source.AppendLine($"namespace {namespaceName};");
    source.AppendLine();

    source.AppendLine("/// <summary>");
    source.AppendLine($"/// Module initializer that wires {ordered.Count} discovered IRawReceptor(s) plus a");
    source.AppendLine("/// singleton IRawReceptorRegistry into AddWhizbang().");
    source.AppendLine("/// </summary>");
    source.AppendLine("internal static class RawReceptorModuleInitializer {");
    source.AppendLine("  [ModuleInitializer]");
    source.AppendLine("  internal static void Initialize() {");
    source.AppendLine("    ServiceRegistrationCallbacks.RawReceptors = static services => {");
    foreach (var info in ordered) {
      source.AppendLine($"      services.AddSingleton<IRawReceptor, {info.TypeName}>();");
    }
    source.AppendLine("      services.AddSingleton<IRawReceptorRegistry, RawReceptorRegistry>();");
    source.AppendLine("    };");
    source.AppendLine("  }");
    source.AppendLine("}");

    context.AddSource("RawReceptors.g.cs", source.ToString());
  }
}

/// <summary>
/// Value-type record for incremental generator caching of discovered IRawReceptor implementations.
/// </summary>
internal sealed record RawReceptorInfo(string TypeName);
