using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Whizbang.Generators.Utilities;

namespace Whizbang.Generators;

/// <summary>
/// Generates a per-assembly <c>GeneratedSignalTypeSource : ISignalTypeSource</c> that lists every
/// concrete <c>ISignal</c> type in the assembly, plus a <c>[ModuleInitializer]</c> that registers it
/// into the cross-assembly <c>SignalTypeRegistry</c>. Mirrors <see cref="EventNamespaceRegistryGenerator"/>
/// (Mechanism A: static central registry, combined union across the dependency chain). Zero reflection —
/// the delivery-class / targeting metadata is read via a generic helper constrained to <c>ISignal</c>, so
/// the concrete type's static-abstract members are reachable at compile time.
/// </summary>
/// <docs>fundamentals/signal-bus/signal-bus</docs>
[Generator]
public class SignalTypeRegistryGenerator : IIncrementalGenerator {
  /// <inheritdoc/>
  public void Initialize(IncrementalGeneratorInitializationContext context) {
    var signals = context.SyntaxProvider.CreateSyntaxProvider(
        predicate: static (node, _) => node is TypeDeclarationSyntax { BaseList.Types.Count: > 0 },
        transform: static (ctx, ct) => _extractSignal(ctx, ct)
    ).Where(static info => info is not null);

    var combined = signals.Collect().Combine(context.CompilationProvider);

    context.RegisterSourceOutput(
        combined,
        static (ctx, data) => _generate(ctx, data.Right, data.Left));
  }

  private static SignalTypeInfo? _extractSignal(
      GeneratorSyntaxContext context,
      System.Threading.CancellationToken cancellationToken) {
    var declaration = (TypeDeclarationSyntax)context.Node;
    if (context.SemanticModel.GetDeclaredSymbol(declaration, cancellationToken) is not INamedTypeSymbol symbol) {
      return null;
    }
    if (symbol.IsAbstract) {
      return null;
    }
    if (symbol.IsGenericType && symbol.TypeParameters.Length > 0) {
      return null;  // open-generic definitions can't be listed by a closed typeof
    }
    // Must be reachable from the generated fragment in the same assembly.
    if (symbol.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal)) {
      return null;
    }
    if (!TypeNameHelper.ImplementsInterface(symbol, StandardInterfaceNames.I_SIGNAL)) {
      return null;
    }

    var fullyQualified = TypeNameHelper.GetFullyQualifiedName(symbol);   // "global::Ns.Type"
    var wireName = fullyQualified.StartsWith("global::", StringComparison.Ordinal)
        ? fullyQualified.Substring("global::".Length)
        : fullyQualified;
    return new SignalTypeInfo(fullyQualified, wireName);
  }

  private static void _generate(
      SourceProductionContext context,
      Compilation compilation,
      ImmutableArray<SignalTypeInfo?> infos) {
    var signals = infos
        .Where(static i => i is not null)
        .Select(static i => i!)
        .Distinct()
        .OrderBy(static i => i.FullyQualifiedName, StringComparer.Ordinal)
        .ToList();

    if (signals.Count == 0) {
      return;
    }

    var assemblyName = compilation.AssemblyName ?? "UnknownAssembly";
    var namespaceName = $"{assemblyName}.Generated";

    var source = new StringBuilder();
    source.AppendLine("// <auto-generated/>");
    source.AppendLine($"// Generated by SignalTypeRegistryGenerator at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
    source.AppendLine("// DO NOT EDIT - Changes will be overwritten");
    source.AppendLine("#nullable enable");
    source.AppendLine();
    source.AppendLine("using System.Runtime.CompilerServices;");
    source.AppendLine();
    source.AppendLine($"namespace {namespaceName};");
    source.AppendLine();

    // Module initializer — self-registers this assembly's fragment before Main().
    source.AppendLine("/// <summary>Registers this assembly's signal types into the global SignalTypeRegistry.</summary>");
    source.AppendLine("internal static class GeneratedSignalTypeSourceInitializer {");
    source.AppendLine("  // CA2255: intentional ModuleInitializer for AOT-compatible cross-assembly signal registration");
    source.AppendLine("#pragma warning disable CA2255");
    source.AppendLine("  [ModuleInitializer]");
    source.AppendLine("#pragma warning restore CA2255");
    source.AppendLine("  public static void Initialize() {");
    source.AppendLine("    global::Whizbang.Core.Signals.SignalTypeRegistry.Register(GeneratedSignalTypeSource.Instance);");
    source.AppendLine("  }");
    source.AppendLine("}");
    source.AppendLine();

    source.AppendLine($"/// <summary>Auto-generated signal-type source. Discovered {signals.Count} signal type(s).</summary>");
    source.AppendLine("internal sealed class GeneratedSignalTypeSource : global::Whizbang.Core.Signals.ISignalTypeSource {");
    source.AppendLine("  /// <summary>Singleton instance for registration.</summary>");
    source.AppendLine("  public static readonly GeneratedSignalTypeSource Instance = new();");
    source.AppendLine("  private GeneratedSignalTypeSource() { }");
    source.AppendLine();
    source.AppendLine("  private static global::Whizbang.Core.Signals.SignalTypeEntry _entry<TSignal>(string wireName)");
    source.AppendLine("      where TSignal : global::Whizbang.Core.Signals.ISignal");
    source.AppendLine("      => new(typeof(TSignal), wireName, TSignal.DeliveryClass, TSignal.Targeting);");
    source.AppendLine();
    source.AppendLine("  private static readonly global::System.Collections.Generic.IReadOnlyList<global::Whizbang.Core.Signals.SignalTypeEntry> _entries =");
    source.AppendLine("    new global::Whizbang.Core.Signals.SignalTypeEntry[] {");
    foreach (var signal in signals) {
      source.AppendLine($"      _entry<{signal.FullyQualifiedName}>(\"{signal.WireName}\"),");
    }
    source.AppendLine("    };");
    source.AppendLine();
    source.AppendLine("  /// <inheritdoc />");
    source.AppendLine("  public global::System.Collections.Generic.IReadOnlyList<global::Whizbang.Core.Signals.SignalTypeEntry> GetSignalTypes() => _entries;");
    source.AppendLine("}");

    context.AddSource("SignalTypeSource.g.cs", source.ToString());
  }

  /// <summary>Cache value-type for a discovered signal type (value equality for incremental caching).</summary>
  internal sealed record SignalTypeInfo(string FullyQualifiedName, string WireName);
}
