using Whizbang.Core.Attributes;

namespace Whizbang.Core;

/// <summary>
/// A single entry in the message type catalog — describes one concrete IMessage or
/// IPerspectiveFor&lt;&gt; type known to the current compilation.
/// </summary>
/// <param name="Type">The concrete CLR type.</param>
/// <param name="ClrTypeName">The current CLR type name as produced by <c>TypeNameFormatter.Format</c>.</param>
/// <param name="Kind">One of <c>"event"</c>, <c>"command"</c>, or <c>"perspective"</c>.</param>
/// <param name="PinnedId">The GUID from <c>[PinnedId]</c>, or null if the type is not pinned.</param>
public sealed record MessageTypeCatalogEntry(
  Type Type,
  string ClrTypeName,
  string Kind,
  string? PinnedId
) {
  /// <summary>
  /// The CLR names this pinned type was FORMERLY known by, from the committed pinned-type ledger
  /// (<c>.whizbang/pinned-type-ledger.json</c>). Empty for unpinned types or types that have never
  /// been renamed. Used by the registry populator to recognise an acknowledged rename and reconcile
  /// a stale <c>wh_message_type_registry</c> row (old name -&gt; current name) in place.
  /// </summary>
  public IReadOnlyList<string> FormerNames { get; init; } = System.Array.Empty<string>();

  /// <summary>
  /// The type's resolved ephemeral mode, or <c>null</c> when it is Sourced (the durable default). The
  /// generator resolves this from <c>[Ephemeral]</c> at compile time — whether declared directly, on a
  /// base record, or on a marker interface — so no reflection is needed to know how a message wants to
  /// be treated. Only events carry it; commands and perspectives are always Sourced here (a perspective's
  /// effective mode is <em>derived</em> from the events it applies, separately).
  /// </summary>
  public EphemeralInfo? Ephemeral { get; init; }

  /// <summary>
  /// Lowercase-hex content hash of the type's behavioral <em>settings</em> (its Sourced/Ephemeral mode +
  /// destruction/storage config), computed canonically by the generator at compile time. A change here
  /// means the type's storage/lifecycle behavior changed — the drift signal the fingerprint reconciler
  /// uses to trigger reclassification. Empty string when the generator predates this field.
  /// </summary>
  /// <docs>fundamentals/events/type-definition-fingerprint</docs>
  public string SettingsHash { get; init; } = "";

  /// <summary>
  /// Lowercase-hex content hash of the type's payload <em>schema</em> — a canonical, ordered signature of
  /// its serializable properties (name + declared type), computed by the generator at compile time. A
  /// change here means the payload shape evolved — the drift signal for versioning/upcasting and the
  /// forgotten-<c>[SchemaVersion]</c>-bump guard. One level deep (incremental-safe); deep nested-DTO
  /// changes are the job of explicit versioning. Empty string when the generator predates this field.
  /// </summary>
  /// <docs>fundamentals/events/type-definition-fingerprint</docs>
  public string SchemaHash { get; init; } = "";

  /// <summary>
  /// <c>true</c> when the type implements <c>ICollectiveEvent</c>, stamped by the generator at compile
  /// time. Load-bearing on the transport receive path: an incoming payload is a <c>JsonElement</c>
  /// there, so a runtime <c>payload is ICollectiveEvent</c> check is blind — the persisted
  /// <c>EventFlags.Collective</c> bit (which routes the event to the collective sink) must be derived
  /// from this compile-time stamp by type name instead.
  /// </summary>
  /// <docs>fundamentals/messaging/collective-events</docs>
  public bool IsCollective { get; init; }

  /// <summary>
  /// <c>true</c> when the type implements <c>ICompositeEvent</c>, stamped by the generator at compile
  /// time. Same transport-receive rationale as <see cref="IsCollective"/> for the
  /// <c>EventFlags.Composite</c> bit.
  /// </summary>
  /// <docs>fundamentals/messaging/composite-events</docs>
  public bool IsComposite { get; init; }

  /// <summary>
  /// <c>true</c> when the type implements <c>ICompactedEvent</c> (a permanent StateBased carry-forward
  /// origin), stamped by the generator at compile time. Same transport-receive rationale as
  /// <see cref="IsCollective"/> for the <c>EventFlags.Compacted</c> bit — a compaction summary crossing
  /// a service boundary must stay Compacted (guarded, never reaped) on the receiving side too.
  /// </summary>
  /// <docs>fundamentals/events/carry-forward-tier2</docs>
  public bool IsCompacted { get; init; }
}

/// <summary>
/// Zero-reflection, AOT-safe enumeration of every concrete IMessage and IPerspectiveFor&lt;&gt;
/// type in the consumer assembly. Implementations are source-generated by
/// <c>MessageTypeCatalogGenerator</c>.
/// </summary>
/// <remarks>
/// Used by <c>IMessageTypeRegistryPopulator</c> at startup to upsert rows into
/// <c>wh_message_type_registry</c>, and by the rename tool (Phase 5) to detect
/// pinned-id drift.
/// </remarks>
/// <docs>core-concepts/pinned-identity</docs>
public interface IMessageTypeCatalog {
  /// <summary>
  /// Returns every known concrete message / perspective type with its metadata.
  /// </summary>
  IReadOnlyList<MessageTypeCatalogEntry> GetAll();
}
