using Whizbang.Core.Attributes;

namespace Whizbang.Core;

/// <summary>
/// A single entry in the message type catalog — describes one concrete IMessage or
/// IPerspectiveFor&lt;&gt; type known to the current compilation.
/// </summary>
/// <param name="Type">The concrete CLR type.</param>
/// <param name="ClrTypeName">The current CLR type name as produced by <c>TypeNameFormatter.Format</c>.</param>
/// <param name="Kind">One of <c>"event"</c>, <c>"command"</c>, or <c>"perspective"</c>.</param>
/// <param name="PinnedId">The GUID from <c>[PinnedId]</c>, or null if the type is not pinned.</param>
public sealed record MessageTypeCatalogEntry(
  Type Type,
  string ClrTypeName,
  string Kind,
  string? PinnedId
) {
  /// <summary>
  /// The CLR names this pinned type was FORMERLY known by, from the committed pinned-type ledger
  /// (<c>.whizbang/pinned-type-ledger.json</c>). Empty for unpinned types or types that have never
  /// been renamed. Used by the registry populator to recognise an acknowledged rename and reconcile
  /// a stale <c>wh_message_type_registry</c> row (old name -&gt; current name) in place.
  /// </summary>
  public IReadOnlyList<string> FormerNames { get; init; } = System.Array.Empty<string>();

  /// <summary>
  /// The type's resolved ephemeral mode, or <c>null</c> when it is Sourced (the durable default). The
  /// generator resolves this from <c>[Ephemeral]</c> at compile time — whether declared directly, on a
  /// base record, or on a marker interface — so no reflection is needed to know how a message wants to
  /// be treated. Only events carry it; commands and perspectives are always Sourced here (a perspective's
  /// effective mode is <em>derived</em> from the events it applies, separately).
  /// </summary>
  public EphemeralInfo? Ephemeral { get; init; }
}

/// <summary>
/// Zero-reflection, AOT-safe enumeration of every concrete IMessage and IPerspectiveFor&lt;&gt;
/// type in the consumer assembly. Implementations are source-generated by
/// <c>MessageTypeCatalogGenerator</c>.
/// </summary>
/// <remarks>
/// Used by <c>IMessageTypeRegistryPopulator</c> at startup to upsert rows into
/// <c>wh_message_type_registry</c>, and by the rename tool (Phase 5) to detect
/// pinned-id drift.
/// </remarks>
/// <docs>core-concepts/pinned-identity</docs>
public interface IMessageTypeCatalog {
  /// <summary>
  /// Returns every known concrete message / perspective type with its metadata.
  /// </summary>
  IReadOnlyList<MessageTypeCatalogEntry> GetAll();
}
