namespace Whizbang.Core;

/// <summary>
/// Zero-reflection, AOT-safe lookup for pinned identities declared via <c>[PinnedId]</c>.
/// Implementations are source-generated by <c>PinnedIdRegistryGenerator</c>.
/// </summary>
/// <remarks>
/// A pinned ID is a stable GUID per concrete <c>IMessage</c> or <c>IPerspectiveFor&lt;&gt;</c> type
/// that survives namespace renames. Stored data keeps the current CLR type name; the registry's
/// role is to expose the pinned identity to the runtime without reflection.
/// </remarks>
/// <docs>core-concepts/pinned-identity</docs>
public interface IPinnedIdRegistry {
  /// <summary>
  /// Gets the pinned ID GUID string for the given type, or null if the type is not pinned.
  /// </summary>
  /// <param name="type">The concrete message or perspective type.</param>
  /// <returns>The GUID string declared on the type's <c>[PinnedId]</c> attribute, or null.</returns>
  string? GetPinnedId(Type type);

  /// <summary>
  /// Returns every known pinned (type, pinned ID) pair, used by the registry populator and rename tool.
  /// </summary>
  IReadOnlyList<(Type Type, string PinnedId)> GetAll();
}
