namespace Whizbang.Core;

/// <summary>
/// Provides strongly-typed ID generation for a specific WhizbangId type.
/// Implemented by source-generated provider classes for AOT compatibility.
/// </summary>
/// <typeparam name="TId">The WhizbangId struct type (e.g., OrderId, ProductId)</typeparam>
/// <remarks>
/// <para>
/// This interface enables type-safe ID generation in dependency injection scenarios,
/// allowing per-type customization while maintaining AOT compatibility.
/// </para>
/// <para>
/// <strong>Automatic Registration:</strong>
/// Provider implementations are automatically generated by WhizbangIdGenerator and
/// registered via ModuleInitializer. Use <see cref="Microsoft.Extensions.DependencyInjection.WhizbangIdServiceCollectionExtensions.AddWhizbangIdProviders"/>
/// to register all providers in the DI container.
/// </para>
/// <para>
/// <strong>Example - DI Usage:</strong>
/// <code>
/// // In Program.cs
/// services.AddWhizbangIdProviders();
///
/// // In your service
/// public class OrderService {
///   private readonly IWhizbangIdProvider&lt;OrderId&gt; _idProvider;
///
///   public OrderService(IWhizbangIdProvider&lt;OrderId&gt; idProvider) {
///     _idProvider = idProvider;
///   }
///
///   public Order CreateOrder() {
///     var orderId = _idProvider.NewId();  // Type-safe!
///     return new Order { Id = orderId };
///   }
/// }
/// </code>
/// </para>
/// </remarks>
/// <docs>core-concepts/whizbang-ids</docs>
public interface IWhizbangIdProvider<TId> where TId : struct {
  /// <summary>
  /// Creates a new instance of the strongly-typed ID.
  /// </summary>
  /// <returns>A new TId instance with a unique value.</returns>
  /// <remarks>
  /// The underlying Guid generation logic is determined by the base <see cref="IWhizbangIdProvider"/>
  /// configured in the DI container or via <see cref="WhizbangIdProvider.SetProvider"/>.
  /// </remarks>
  TId NewId();
}
