#region HEADER
// <auto-generated/>
// Generated at: __TIMESTAMP__
#endregion
#nullable enable

using System;
using Microsoft.Extensions.DependencyInjection;
using Whizbang.Core;

namespace Whizbang.Core.Generated;

/// <summary>
/// Internal static extractor for compile-time aggregate ID extraction.
/// Zero reflection - uses compile-time type switches.
/// </summary>
internal static class AggregateIdExtractors {
  /// <summary>
  /// Extracts aggregate ID from a message using compile-time type information.
  /// </summary>
  internal static Guid? ExtractAggregateId(object message, Type messageType) {
    #region EXTRACTORS
    // Type-based dispatch to extract aggregate IDs
    #endregion

    return null;
  }
}

/// <summary>
/// DI-compatible aggregate ID extractor implementation.
/// Wraps the static extractor for dependency injection.
/// </summary>
internal sealed class AggregateIdExtractor : IAggregateIdExtractor {
  /// <inheritdoc />
  public Guid? ExtractAggregateId(object message, Type messageType) {
    return AggregateIdExtractors.ExtractAggregateId(message, messageType);
  }
}

/// <summary>
/// Extension methods for registering Whizbang aggregate ID extraction.
/// </summary>
public static class ServiceCollectionExtensions {
  #region DI_REGISTRATION
  // DI registration method
  #endregion
}
