#region HEADER
// <auto-generated/>
// Generated at: __TIMESTAMP__
#endregion

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Whizbang.Core;
using Whizbang.Core.Data;
using Whizbang.Core.Messaging;
using Whizbang.Core.Observability;
using Whizbang.Core.Perspectives;
using Whizbang.Core.Routing;
using Whizbang.Core.Security;
using Whizbang.Core.Transports;

#region NAMESPACE
namespace Whizbang.Core.Generated {
#endregion
  /// <summary>
  /// Auto-generated registrations for receptors, dispatcher, and perspective invoker.
  /// </summary>
  [ExcludeFromCodeCoverage]
  [DebuggerNonUserCode]
  public static class DispatcherRegistrations {
    /// <summary>
    /// Registers all {{RECEPTOR_COUNT}} discovered receptors with the service collection.
    /// </summary>
    [ExcludeFromCodeCoverage]
    [DebuggerNonUserCode]
    public static IServiceCollection AddReceptors(this IServiceCollection services) {
      #region RECEPTOR_REGISTRATIONS
      // This region will be replaced with receptor registration calls
      #endregion
      return services;
    }

    /// <summary>
    /// Registers the generated IPerspectiveInvoker as a Scoped service.
    /// One instance per HTTP request or message batch for proper unit of work scoping.
    /// </summary>
    [ExcludeFromCodeCoverage]
    [DebuggerNonUserCode]
    public static IServiceCollection AddWhizbangPerspectiveInvoker(this IServiceCollection services) {
      services.AddScoped<IPerspectiveInvoker, GeneratedPerspectiveInvoker>();
      return services;
    }

    /// <summary>
    /// Registers the generated zero-reflection dispatcher and receptor registry.
    /// Automatically resolves optional Singleton dependencies: ITraceStore, ITransport, JsonSerializerOptions, ITopicRegistry, ITopicRoutingStrategy, IEnvelopeSerializer, IOutboxRoutingStrategy.
    /// NOTE: IEventStore and IWorkCoordinatorStrategy are resolved per-call from the active scope, not captured in constructor.
    /// This is required because they may be registered as Scoped (e.g., EF Core implementations).
    /// </summary>
    /// <remarks>
    /// <para>
    /// This method also registers IReceptorRegistry and IReceptorInvoker for lifecycle stage invocation.
    /// You don't need to call AddWhizbangReceptorRegistry() separately.
    /// </para>
    /// <para>
    /// <strong>Security Context Propagation</strong>: Registers IScopeContextAccessor by default for automatic
    /// security context propagation to outgoing messages. To disable propagation, configure MessageSecurityOptions:
    /// <code>options.PropagateToOutgoingMessages = false;</code>
    /// </para>
    /// </remarks>
    [ExcludeFromCodeCoverage]
    [DebuggerNonUserCode]
    public static IServiceCollection AddWhizbangDispatcher(this IServiceCollection services) {
      // Register receptor registry first (dispatcher depends on IReceptorInvoker)
      services.AddWhizbangReceptorRegistry();

      // Register IScopeContextAccessor for automatic security context propagation
      // Uses TryAdd to allow user override if needed
      services.TryAddSingleton<IScopeContextAccessor, ScopeContextAccessor>();

      services.AddSingleton<IDispatcher>(sp => {
        var instanceProvider = sp.GetRequiredService<IServiceInstanceProvider>();
        var traceStore = sp.GetService<ITraceStore>();
        var jsonOptions = sp.GetService<JsonSerializerOptions>();
        var topicRegistry = sp.GetService<ITopicRegistry>();
        var topicRoutingStrategy = sp.GetService<ITopicRoutingStrategy>();
        var envelopeSerializer = sp.GetService<IEnvelopeSerializer>();
        var envelopeRegistry = sp.GetService<IEnvelopeRegistry>();
        var outboxRoutingStrategy = sp.GetService<IOutboxRoutingStrategy>();
        var lifecycleInvoker = sp.GetService<ILifecycleInvoker>();
        // IReceptorRegistry is singleton - safe to resolve here
        // IReceptorInvoker is scoped - resolved by workers per-message, not by Dispatcher
        var receptorRegistry = sp.GetService<IReceptorRegistry>();

        // Do NOT resolve IEventStore or IWorkCoordinatorStrategy here - they may be Scoped
        // The Dispatcher will resolve them per-call from the active service provider
        return new GeneratedDispatcher(sp, instanceProvider, traceStore, jsonOptions, topicRegistry, topicRoutingStrategy, envelopeSerializer, envelopeRegistry, outboxRoutingStrategy, lifecycleInvoker, receptorRegistry);
      });
      services.AddSingleton<global::Whizbang.Core.Dispatcher>(sp => (GeneratedDispatcher)sp.GetRequiredService<IDispatcher>());
      return services;
    }

    /// <summary>
    /// Registers the generated zero-reflection lifecycle invoker.
    /// Stateless routing component registered as Singleton for optimal performance.
    /// Routes lifecycle invocations based on message type and lifecycle stage from [FireAt] attributes.
    /// </summary>
    [ExcludeFromCodeCoverage]
    [DebuggerNonUserCode]
    public static IServiceCollection AddWhizbangLifecycleInvoker(this IServiceCollection services) {
      services.AddSingleton<ILifecycleInvoker, GeneratedLifecycleInvoker>();
      return services;
    }

    /// <summary>
    /// Registers the lifecycle message deserializer for reconstructing messages at Distribute/Outbox/Inbox stages.
    /// Deserializes messages from JsonElement payloads in OutboxMessage/InboxMessage records.
    /// Registered as Singleton since it's stateless (JsonSerializerOptions resolved from DI).
    /// </summary>
    [ExcludeFromCodeCoverage]
    [DebuggerNonUserCode]
    public static IServiceCollection AddWhizbangLifecycleMessageDeserializer(this IServiceCollection services) {
      services.AddSingleton<ILifecycleMessageDeserializer>(sp => {
        var jsonOptions = sp.GetService<JsonSerializerOptions>();
        return new JsonLifecycleMessageDeserializer(jsonOptions);
      });
      return services;
    }

    /// <summary>
    /// Registers the generated zero-reflection receptor registry and invoker.
    /// Pre-categorizes ALL receptors by lifecycle stage at compile time:
    /// - Receptors WITH [FireAt(X)] are registered at stage X only
    /// - Receptors WITHOUT [FireAt] are registered at LocalImmediateInline, PreOutboxInline, PostInboxInline
    /// </summary>
    /// <remarks>
    /// <para>
    /// <strong>IReceptorRegistry</strong> is registered as Singleton since it's stateless (delegates are pre-compiled).
    /// </para>
    /// <para>
    /// <strong>IReceptorInvoker</strong> is registered as Scoped to ensure receptors can resolve scoped dependencies.
    /// Workers create a scope per message, resolve the invoker from that scope, and the invoker uses
    /// the ambient scoped provider for resolving receptors. This follows the MediatR/MassTransit pattern.
    /// </para>
    /// </remarks>
    [ExcludeFromCodeCoverage]
    [DebuggerNonUserCode]
    public static IServiceCollection AddWhizbangReceptorRegistry(this IServiceCollection services) {
      services.AddSingleton<IReceptorRegistry, GeneratedReceptorRegistry>();
      services.AddScoped<IReceptorInvoker, ReceptorInvoker>();
      return services;
    }
  }
}
