#region HEADER
// <auto-generated/>
// Generated at: __TIMESTAMP__
#endregion
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Whizbang.Core.Observability;

namespace Whizbang.Core.Generated;

/// <summary>
/// Generated Dispatcher implementation with zero-reflection routing for {{RECEPTOR_COUNT}} receptor(s).
/// Derives from Whizbang.Core.Dispatcher and implements abstract methods that return delegates.
/// The delegates provide strongly-typed invocation without any reflection.
/// </summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal sealed class GeneratedDispatcher : Dispatcher {
  public GeneratedDispatcher(IServiceProvider serviceProvider, ITraceStore? traceStore = null)
    : base(serviceProvider, traceStore) {
  }

  /// <summary>
  /// Generated lookup - returns a strongly-typed delegate that invokes the appropriate receptor.
  /// Zero reflection - uses compile-time type matching and lambda expressions.
  /// </summary>
  [DebuggerStepThrough]
  protected override ReceptorInvoker<TResult>? _getReceptorInvoker<TResult>(object message, Type messageType) {
    // Generated routing - zero reflection!
    #region SEND_ROUTING
    // This region will be replaced with generated routing code
    #endregion

    return null;
  }

  /// <summary>
  /// Generated lookup - returns a strongly-typed delegate that invokes the appropriate void receptor.
  /// Zero reflection - uses compile-time type matching and lambda expressions.
  /// </summary>
  [DebuggerStepThrough]
  protected override VoidReceptorInvoker? _getVoidReceptorInvoker(object message, Type messageType) {
    // Generated routing - zero reflection!
    #region VOID_SEND_ROUTING
    // This region will be replaced with generated void receptor routing code
    #endregion

    return null;
  }

  /// <summary>
  /// Generated lookup - returns a strongly-typed delegate that publishes to all receptors.
  /// Zero reflection - uses compile-time type matching and lambda expressions.
  /// </summary>
  [DebuggerStepThrough]
  protected override ReceptorPublisher<TEvent> _getReceptorPublisher<TEvent>(TEvent @event, Type eventType) {
    // Generated routing - zero reflection!
    #region PUBLISH_ROUTING
    // This region will be replaced with generated publish routing code
    #endregion

    return _ => Task.CompletedTask;
  }
}
