#region HEADER
// <auto-generated/>
// Generated at: __TIMESTAMP__
#endregion

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Whizbang.Core;
using Whizbang.Core.Messaging;
using Whizbang.Core.Observability;
using Whizbang.Core.Routing;
using Whizbang.Core.Transports;

#region NAMESPACE
namespace Whizbang.Core.Generated;
#endregion

/// <summary>
/// Generated Dispatcher implementation with zero-reflection routing for {{RECEPTOR_COUNT}} receptor(s).
/// Derives from Whizbang.Core.Dispatcher and implements abstract methods that return delegates.
/// The delegates provide strongly-typed invocation without any reflection.
/// </summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal sealed class GeneratedDispatcher : global::Whizbang.Core.Dispatcher {
  private readonly IServiceScopeFactory _scopeFactory;

  public GeneratedDispatcher(
    IServiceProvider serviceProvider,
    IServiceInstanceProvider instanceProvider,
    ITraceStore? traceStore = null,
    JsonSerializerOptions? jsonOptions = null,
    ITopicRegistry? topicRegistry = null,
    ITopicRoutingStrategy? topicRoutingStrategy = null,
    IAggregateIdExtractor? aggregateIdExtractor = null,
    IReceptorInvoker? receptorInvoker = null,
    IEnvelopeSerializer? envelopeSerializer = null,
    IEnvelopeRegistry? envelopeRegistry = null,
    IOutboxRoutingStrategy? outboxRoutingStrategy = null,
    ILifecycleInvoker? lifecycleInvoker = null
  ) : base(serviceProvider, instanceProvider, traceStore, jsonOptions, topicRegistry, topicRoutingStrategy, aggregateIdExtractor, receptorInvoker, envelopeSerializer, envelopeRegistry, outboxRoutingStrategy, lifecycleInvoker) {
    _scopeFactory = serviceProvider.GetRequiredService<IServiceScopeFactory>();
  }

  /// <summary>
  /// Generated lookup - returns a strongly-typed delegate that invokes the appropriate receptor.
  /// Zero reflection - uses compile-time type matching and lambda expressions.
  /// </summary>
  [DebuggerStepThrough]
  protected override ReceptorInvoker<TResult>? GetReceptorInvoker<TResult>(object message, Type messageType) {
    // Generated routing - zero reflection!
    #region SEND_ROUTING
    // This region will be replaced with generated routing code
    #endregion

    return null;
  }

  /// <summary>
  /// Generated lookup - returns a strongly-typed delegate that invokes the appropriate void receptor.
  /// Zero reflection - uses compile-time type matching and lambda expressions.
  /// </summary>
  [DebuggerStepThrough]
  protected override VoidReceptorInvoker? GetVoidReceptorInvoker(object message, Type messageType) {
    // Generated routing - zero reflection!
    #region VOID_SEND_ROUTING
    // This region will be replaced with generated void receptor routing code
    #endregion

    return null;
  }

  /// <summary>
  /// Generated lookup - returns a strongly-typed delegate that publishes to all receptors.
  /// Zero reflection - uses compile-time type matching and lambda expressions.
  /// </summary>
  [DebuggerStepThrough]
  protected override ReceptorPublisher<TEvent> GetReceptorPublisher<TEvent>(TEvent @event, Type eventType) {
    // Generated routing - zero reflection!
    #region PUBLISH_ROUTING
    // This region will be replaced with generated publish routing code
    #endregion

    return _ => Task.CompletedTask;
  }

  /// <summary>
  /// Generated lookup - returns a type-erased delegate that publishes to all receptors.
  /// Used by auto-cascade to publish events extracted from receptor return values.
  /// Zero reflection - uses compile-time type matching and lambda expressions.
  /// </summary>
  [DebuggerStepThrough]
  protected override Func<object, Task>? GetUntypedReceptorPublisher(Type eventType) {
    // Generated routing - zero reflection!
    #region UNTYPED_PUBLISH_ROUTING
    // This region will be replaced with generated untyped publish routing code
    #endregion

    return null;
  }

  /// <summary>
  /// Generated lookup - returns a sync delegate that invokes the appropriate sync receptor.
  /// Zero reflection - uses compile-time type matching and lambda expressions.
  /// </summary>
  [DebuggerStepThrough]
  protected override SyncReceptorInvoker<TResult>? GetSyncReceptorInvoker<TResult>(object message, Type messageType) {
    // Generated routing for sync receptors - zero reflection!
    #region SYNC_SEND_ROUTING
    // This region will be replaced with generated sync receptor routing code
    #endregion

    return null;
  }

  /// <summary>
  /// Generated lookup - returns a void sync delegate that invokes the appropriate void sync receptor.
  /// Zero reflection - uses compile-time type matching and lambda expressions.
  /// </summary>
  [DebuggerStepThrough]
  protected override VoidSyncReceptorInvoker? GetVoidSyncReceptorInvoker(object message, Type messageType) {
    // Generated routing for void sync receptors - zero reflection!
    #region VOID_SYNC_SEND_ROUTING
    // This region will be replaced with generated void sync receptor routing code
    #endregion

    return null;
  }

  /// <summary>
  /// Generated lookup - returns a type-erased delegate for invoking ANY receptor (void or non-void).
  /// Used by void LocalInvokeAsync paths to cascade events from non-void receptors.
  /// Priority order: non-void async > non-void sync > void async > void sync.
  /// Zero reflection - uses compile-time type matching and lambda expressions.
  /// </summary>
  [DebuggerStepThrough]
  protected override Func<object, ValueTask<object?>>? GetReceptorInvokerAny(object message, Type messageType) {
    // Generated routing for any receptor (cascade support) - zero reflection!
    #region ANY_SEND_ROUTING
    // This region will be replaced with generated any receptor routing code
    #endregion

    return null;
  }

  /// <summary>
  /// Generated lookup - returns the default dispatch routing for a message type based on receptor [DefaultRouting] attribute.
  /// Used by cascade to apply receptor-level routing policy to all returned messages.
  /// Zero reflection - uses compile-time type matching.
  /// </summary>
  [DebuggerStepThrough]
  protected override global::Whizbang.Core.Dispatch.DispatchMode? GetReceptorDefaultRouting(Type messageType) {
    // Generated routing metadata - zero reflection!
    #region RECEPTOR_DEFAULT_ROUTING
    // This region will be replaced with generated routing lookup code
    #endregion

    return null;
  }

  /// <summary>
  /// Generated override - publishes cascaded events to outbox using type-switch dispatch.
  /// Zero reflection - uses compile-time type matching for AOT compatibility.
  /// </summary>
  /// <docs>core-concepts/dispatcher#auto-cascade-to-outbox</docs>
  [DebuggerStepThrough]
  protected override Task CascadeToOutboxAsync(global::Whizbang.Core.IMessage message, Type messageType) {
    // Generated type-switch dispatch - zero reflection!
    #region OUTBOX_CASCADE
    // This region will be replaced with generated cascade code
    #endregion

    return Task.CompletedTask;
  }
}
