#region HEADER
// <auto-generated/>
// Generated at: __TIMESTAMP__
#endregion
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Whizbang.Core;
using Whizbang.Core.Messaging;
using Whizbang.Core.Observability;
using Whizbang.Core.Transports;

#region NAMESPACE
namespace Whizbang.Core.Generated;
#endregion

/// <summary>
/// Generated Dispatcher implementation with zero-reflection routing for {{RECEPTOR_COUNT}} receptor(s).
/// Derives from Whizbang.Core.Dispatcher and implements abstract methods that return delegates.
/// The delegates provide strongly-typed invocation without any reflection.
/// </summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal sealed class GeneratedDispatcher : global::Whizbang.Core.Dispatcher {
  public GeneratedDispatcher(
    IServiceProvider serviceProvider,
    IServiceInstanceProvider instanceProvider,
    ITraceStore? traceStore = null,
    ITransport? transport = null,
    JsonSerializerOptions? jsonOptions = null,
    global::Whizbang.Core.Routing.ITopicRegistry? topicRegistry = null,
    global::Whizbang.Core.Routing.ITopicRoutingStrategy? topicRoutingStrategy = null,
    IAggregateIdExtractor? aggregateIdExtractor = null,
    ILifecycleInvoker? lifecycleInvoker = null
  ) : base(serviceProvider, instanceProvider, traceStore, transport, jsonOptions, topicRegistry, topicRoutingStrategy, aggregateIdExtractor, lifecycleInvoker) {
  }

  /// <summary>
  /// Generated lookup - returns a strongly-typed delegate that invokes the appropriate receptor.
  /// Zero reflection - uses compile-time type matching and lambda expressions.
  /// </summary>
  [DebuggerStepThrough]
  protected override ReceptorInvoker<TResult>? GetReceptorInvoker<TResult>(object message, Type messageType) {
    // Generated routing - zero reflection!
    #region SEND_ROUTING
    // This region will be replaced with generated routing code
    #endregion

    return null;
  }

  /// <summary>
  /// Generated lookup - returns a strongly-typed delegate that invokes the appropriate void receptor.
  /// Zero reflection - uses compile-time type matching and lambda expressions.
  /// </summary>
  [DebuggerStepThrough]
  protected override VoidReceptorInvoker? GetVoidReceptorInvoker(object message, Type messageType) {
    // Generated routing - zero reflection!
    #region VOID_SEND_ROUTING
    // This region will be replaced with generated void receptor routing code
    #endregion

    return null;
  }

  /// <summary>
  /// Generated lookup - returns a strongly-typed delegate that publishes to all receptors.
  /// Zero reflection - uses compile-time type matching and lambda expressions.
  /// </summary>
  [DebuggerStepThrough]
  protected override ReceptorPublisher<TEvent> GetReceptorPublisher<TEvent>(TEvent @event, Type eventType) {
    // Generated routing - zero reflection!
    #region PUBLISH_ROUTING
    // This region will be replaced with generated publish routing code
    #endregion

    return _ => Task.CompletedTask;
  }
}
