#region HEADER
// <auto-generated/>
// Generated at: __TIMESTAMP__
#endregion
#nullable enable

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Whizbang.Core;
using Whizbang.Core.Data;
using Whizbang.Core.Messaging;
using Whizbang.Core.Observability;
using Whizbang.Core.Perspectives;
using Whizbang.Core.Transports;

#region NAMESPACE
namespace Whizbang.Core.Generated {
#endregion
  /// <summary>
  /// Auto-generated registrations for receptors, dispatcher, and perspective invoker.
  /// </summary>
  [ExcludeFromCodeCoverage]
  [DebuggerNonUserCode]
  public static class DispatcherRegistrations {
    /// <summary>
    /// Registers all {{RECEPTOR_COUNT}} discovered receptors with the service collection.
    /// </summary>
    [ExcludeFromCodeCoverage]
    [DebuggerNonUserCode]
    public static IServiceCollection AddReceptors(this IServiceCollection services) {
      #region RECEPTOR_REGISTRATIONS
      // This region will be replaced with receptor registration calls
      #endregion
      return services;
    }

    /// <summary>
    /// Registers the generated IPerspectiveInvoker as a Scoped service.
    /// One instance per HTTP request or message batch for proper unit of work scoping.
    /// </summary>
    [ExcludeFromCodeCoverage]
    [DebuggerNonUserCode]
    public static IServiceCollection AddWhizbangPerspectiveInvoker(this IServiceCollection services) {
      services.AddScoped<IPerspectiveInvoker, GeneratedPerspectiveInvoker>();
      return services;
    }

    /// <summary>
    /// Registers the generated zero-reflection dispatcher.
    /// Automatically resolves optional Singleton dependencies: ITraceStore, ITransport, JsonSerializerOptions, ITopicRegistry, ITopicRoutingStrategy.
    /// NOTE: IEventStore, IAggregateIdExtractor, and IWorkCoordinatorStrategy are resolved per-call from the active scope, not captured in constructor.
    /// This is required because they may be registered as Scoped (e.g., EF Core implementations).
    /// </summary>
    [ExcludeFromCodeCoverage]
    [DebuggerNonUserCode]
    public static IServiceCollection AddWhizbangDispatcher(this IServiceCollection services) {
      services.AddSingleton<IDispatcher>(sp => {
        var instanceProvider = sp.GetRequiredService<IServiceInstanceProvider>();
        var traceStore = sp.GetService<ITraceStore>();
        var transport = sp.GetService<ITransport>();
        var jsonOptions = sp.GetService<JsonSerializerOptions>();
        var topicRegistry = sp.GetService<Whizbang.Core.Routing.ITopicRegistry>();
        var topicRoutingStrategy = sp.GetService<Whizbang.Core.Routing.ITopicRoutingStrategy>();

        // Do NOT resolve IEventStore, IAggregateIdExtractor, or IWorkCoordinatorStrategy here - they may be Scoped
        // The Dispatcher will resolve them per-call from the active service provider
        return new GeneratedDispatcher(sp, instanceProvider, traceStore, transport, jsonOptions, topicRegistry, topicRoutingStrategy);
      });
      services.AddSingleton<global::Whizbang.Core.Dispatcher>(sp => (GeneratedDispatcher)sp.GetRequiredService<IDispatcher>());
      return services;
    }
  }
}
