#region HEADER
// <auto-generated/>
// Generated at: __TIMESTAMP__
#endregion

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Whizbang.Core;
using Whizbang.Core.Messaging;

#region NAMESPACE
namespace Whizbang.Core.Generated;
#endregion

/// <summary>
/// Generated IReceptorRegistry implementation with zero-reflection routing for {{RECEPTOR_COUNT}} receptor(s).
/// Pre-categorizes ALL receptors by lifecycle stage at compile time:
/// - Receptors WITH [FireAt(X)] are registered at stage X only
/// - Receptors WITHOUT [FireAt] are registered at LocalImmediateInline, PreOutboxInline, and PostInboxInline
/// </summary>
/// <remarks>
/// <para>
/// This registry does not hold an IServiceProvider. Instead, the InvokeAsync delegate
/// accepts a scoped IServiceProvider as its first parameter. This allows the ReceptorInvoker
/// to create a scope and pass the scoped provider, enabling receptors with scoped dependencies
/// (like IEventStore, DbContext) to be resolved correctly even when called from singleton services.
/// </para>
/// </remarks>
/// <docs>core-concepts/lifecycle-receptors</docs>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public sealed class GeneratedReceptorRegistry : global::Whizbang.Core.Messaging.IReceptorRegistry {
  // Pre-allocated empty list for cache-friendly returns
  private static readonly IReadOnlyList<global::Whizbang.Core.Messaging.ReceptorInfo> _emptyList =
      Array.Empty<global::Whizbang.Core.Messaging.ReceptorInfo>();

  /// <summary>
  /// Gets all receptors registered to handle the specified message type at the specified lifecycle stage.
  /// This is a compile-time generated switch statement for optimal performance.
  /// </summary>
  [DebuggerStepThrough]
  public IReadOnlyList<global::Whizbang.Core.Messaging.ReceptorInfo> GetReceptorsFor(Type messageType, LifecycleStage stage) {
    if (messageType is null) {
      throw new ArgumentNullException(nameof(messageType));
    }

    // Generated routing: switch on (messageType, stage) combinations
    #region RECEPTOR_ROUTING
    // This region will be replaced with generated routing code
    #endregion

    return _emptyList;
  }
}
