#region HEADER
// <auto-generated/>
// Generated at: __TIMESTAMP__
#endregion
#nullable enable

using System.Diagnostics;

namespace Whizbang.Core.Generated {
  /// <summary>
  /// Registers receptor discovery diagnostics with the central diagnostics collector.
  /// This class is auto-generated and registers its information during static initialization.
  /// </summary>
  public static class ReceptorDiscoveryDiagnostics {
    [DebuggerNonUserCode]
    static ReceptorDiscoveryDiagnostics() {
      // Build a detailed message about discovered receptors
      var message = new System.Text.StringBuilder();
      message.AppendLine("Discovered {{RECEPTOR_COUNT}} receptor(s):");
      #region DIAGNOSTIC_MESSAGES
      // This region will be replaced with diagnostic message generation
      #endregion

      // Register this diagnostic entry
      WhizbangDiagnostics.AddEntry(new DiagnosticEntry(
          GeneratorName: "ReceptorDiscoveryGenerator",
          Timestamp: "{{TIMESTAMP}}",
          Category: DiagnosticCategory.ReceptorDiscovery,
          Message: message.ToString()
      ));
    }

    /// <summary>
    /// Forces static initialization of this class.
    /// Call this method to ensure diagnostics are registered.
    /// </summary>
    [DebuggerNonUserCode]
    public static void Register() {
      // Method body intentionally empty.
      // The static constructor does the real work.
    }
  }
}
