using System;
using Microsoft.Extensions.DependencyInjection;
using Whizbang.Core;
using Whizbang.Core.Configuration;

#region NAMESPACE
namespace Whizbang.Core.Generated;
#endregion

#region HEADER
// This region gets replaced with generated header + timestamp
#endregion

/// <summary>
/// Auto-registration initializer for discovered lens and perspective services.
/// Registers callbacks with <see cref="ServiceRegistrationCallbacks"/> when the assembly loads.
/// </summary>
internal static class ServiceRegistrationInitializer {
  /// <summary>
  /// Module initializer that registers service callbacks with the global registry.
  /// Runs automatically when the assembly is loaded - no explicit call needed.
  /// </summary>
  [System.Runtime.CompilerServices.ModuleInitializer]
  internal static void Initialize() {
    // Register lens services callback
    global::Whizbang.Core.ServiceRegistrationCallbacks.LensServices = (services, options) => {
      services.AddLensServices(o => o.IncludeSelfRegistration = options.IncludeSelfRegistration);
    };

    // Register perspective services callback
    global::Whizbang.Core.ServiceRegistrationCallbacks.PerspectiveServices = (services, options) => {
      services.AddPerspectiveServices(o => o.IncludeSelfRegistration = options.IncludeSelfRegistration);
    };
  }
}

/// <summary>
/// Options for configuring service registration behavior.
/// This class mirrors <see cref="Whizbang.Core.Configuration.ServiceRegistrationOptions"/>
/// for use with the explicit AddLensServices/AddPerspectiveServices methods.
/// </summary>
/// <docs>operations/configuration/service-registration-options</docs>
public sealed class ServiceRegistrationOptions {
  /// <summary>
  /// If true, registers concrete types as themselves in addition to their interfaces.
  /// Default: true.
  /// </summary>
  /// <example>
  /// <code>
  /// // When IncludeSelfRegistration = true (default):
  /// services.AddTransient&lt;IOrderLens, OrderLens&gt;();  // Interface registration
  /// services.AddTransient&lt;OrderLens&gt;();               // Self-registration
  ///
  /// // When IncludeSelfRegistration = false:
  /// services.AddTransient&lt;IOrderLens, OrderLens&gt;();  // Interface registration only
  /// </code>
  /// </example>
  public bool IncludeSelfRegistration { get; set; } = true;
}

/// <summary>
/// Extension methods for registering {{PERSPECTIVE_SERVICE_COUNT}} discovered perspective service(s)
/// and {{LENS_SERVICE_COUNT}} discovered lens service(s) with the DI container.
/// All services are registered as Transient.
/// Generated by Whizbang.Generators.ServiceRegistrationGenerator.
/// </summary>
/// <docs>operations/configuration/service-registration</docs>
public static class ServiceRegistrationExtensions {
  /// <summary>
  /// Registers all discovered perspective implementations with the service collection.
  /// Each perspective is registered as Transient.
  /// Self-registration is included by default (configurable via options).
  /// </summary>
  /// <param name="services">The service collection to add registrations to</param>
  /// <param name="configure">Optional configuration action for registration behavior</param>
  /// <returns>The service collection for chaining</returns>
  /// <example>
  /// <code>
  /// // Default: registers both interface and concrete type
  /// services.AddPerspectiveServices();
  ///
  /// // Disable self-registration
  /// services.AddPerspectiveServices(options => options.IncludeSelfRegistration = false);
  /// </code>
  /// </example>
  /// <docs>operations/configuration/perspective-services</docs>
  public static IServiceCollection AddPerspectiveServices(
      this IServiceCollection services,
      Action<ServiceRegistrationOptions>? configure = null) {

    var options = new ServiceRegistrationOptions();
    configure?.Invoke(options);

    #region PERSPECTIVE_REGISTRATIONS
    // This region gets replaced with generated perspective registration code
    #endregion

    return services;
  }

  /// <summary>
  /// Registers all discovered lens implementations with the service collection.
  /// Each lens is registered as Transient.
  /// Self-registration is included by default (configurable via options).
  /// </summary>
  /// <param name="services">The service collection to add registrations to</param>
  /// <param name="configure">Optional configuration action for registration behavior</param>
  /// <returns>The service collection for chaining</returns>
  /// <example>
  /// <code>
  /// // Default: registers both interface and concrete type
  /// services.AddLensServices();
  ///
  /// // Disable self-registration
  /// services.AddLensServices(options => options.IncludeSelfRegistration = false);
  /// </code>
  /// </example>
  /// <docs>operations/configuration/lens-services</docs>
  public static IServiceCollection AddLensServices(
      this IServiceCollection services,
      Action<ServiceRegistrationOptions>? configure = null) {

    var options = new ServiceRegistrationOptions();
    configure?.Invoke(options);

    #region LENS_REGISTRATIONS
    // This region gets replaced with generated lens registration code
    #endregion

    return services;
  }

  /// <summary>
  /// Registers all discovered perspective and lens implementations with the service collection.
  /// Convenience method that calls both AddPerspectiveServices and AddLensServices.
  /// </summary>
  /// <param name="services">The service collection to add registrations to</param>
  /// <param name="configure">Optional configuration action for registration behavior</param>
  /// <returns>The service collection for chaining</returns>
  /// <example>
  /// <code>
  /// // Register all Whizbang services with default options
  /// services.AddWhizbang()
  ///         .AddWhizbangPerspectives()
  ///         .AddAllWhizbangServices();
  ///
  /// // Or with configuration
  /// services.AddAllWhizbangServices(options => options.IncludeSelfRegistration = false);
  /// </code>
  /// </example>
  /// <docs>operations/configuration/all-services</docs>
  public static IServiceCollection AddAllWhizbangServices(
      this IServiceCollection services,
      Action<ServiceRegistrationOptions>? configure = null) {

    services.AddPerspectiveServices(configure);
    services.AddLensServices(configure);
    return services;
  }
}
