#region HEADER
// <auto-generated/>
// Generated at: __TIMESTAMP__
#endregion
#nullable enable

using System;

#region NAMESPACE
namespace Whizbang.Core.Generated;
#endregion

/// <summary>
/// Generated stream key extractors for zero-reflection AOT compatibility.
/// </summary>
public static partial class StreamKeyExtractors {

  /// <summary>
  /// Resolves the stream key from an event using generated extractors.
  /// Zero-reflection alternative to StreamKeyResolver.Resolve().
  /// </summary>
  public static string Resolve(global::Whizbang.Core.IEvent @event) {
    System.ArgumentNullException.ThrowIfNull(@event);

    #region RESOLVE_DISPATCH
    // Type-based dispatch to correct extractor
    #endregion

    throw new System.InvalidOperationException(
      $"No stream key extractor found for event type '{@event.GetType().Name}'. " +
      "Ensure the event type has a property or parameter marked with [StreamKey].");
  }

  #region EXTRACTORS
  // Individual extractor methods for each event type
  #endregion
}
