#region HEADER
// <auto-generated/>
// Generated at: __TIMESTAMP__
#endregion

using global::System;

#region NAMESPACE
namespace Whizbang.Core.Generated;
#endregion

/// <summary>
/// Generated stream key extractors for zero-reflection AOT compatibility.
/// </summary>
public static partial class StreamKeyExtractors {

  /// <summary>
  /// Resolves the stream key from an event using generated extractors.
  /// Zero-reflection alternative to StreamKeyResolver.Resolve().
  /// </summary>
  public static string Resolve(global::Whizbang.Core.IEvent @event) {
    global::System.ArgumentNullException.ThrowIfNull(@event);

    #region RESOLVE_DISPATCH
    // Type-based dispatch to correct extractor
    #endregion

    throw new global::System.InvalidOperationException(
      $"No stream key extractor found for event type '{@event.GetType().Name}'. " +
      "Ensure the event type has a property or parameter marked with [StreamKey].");
  }

  /// <summary>
  /// Tries to resolve the stream key from an event and parse it as a Guid.
  /// Returns null if the event has no [StreamKey] or the key is not a valid Guid.
  /// Used by IDeliveryReceipt.StreamId extraction.
  /// </summary>
  /// <param name="event">The event to extract the stream key from</param>
  /// <returns>The stream key as a Guid if found and parseable, otherwise null</returns>
  public static global::System.Guid? TryResolveAsGuid(global::Whizbang.Core.IEvent? @event) {
    if (@event == null) return null;

    #region TRY_RESOLVE_DISPATCH
    // Type-based dispatch returning Guid?
    #endregion

    return null;
  }

  #region EXTRACTORS
  // Individual extractor methods for each event type
  #endregion

  #region TRY_EXTRACT_METHODS
  // Individual TryExtractAsGuid methods for each event type
  #endregion
}
