using System;
using System.Runtime.CompilerServices;
using Whizbang.Core.Perspectives.Sync;

#region NAMESPACE
namespace Whizbang.Core.Generated;
#endregion

#region HEADER
// This region gets replaced with generated header + timestamp
#endregion

/// <summary>
/// Auto-registers event type to perspective mappings for perspective sync tracking.
/// Generated by Whizbang.Generators.SyncEventTypeRegistryGenerator.
/// </summary>
/// <remarks>
/// <para>
/// This class uses a module initializer to automatically register event type mappings
/// before <c>AddWhizbang()</c> is called. No manual registration is required.
/// </para>
/// <para>
/// The registry maps event types discovered from [AwaitPerspectiveSync] attributes
/// to their corresponding perspective types for cross-scope synchronization.
/// </para>
/// <para>
/// {{EVENT_TYPE_COUNT}} event type(s) mapped to {{PERSPECTIVE_COUNT}} perspective(s).
/// </para>
/// </remarks>
/// <docs>core-concepts/perspectives/perspective-sync#auto-registration</docs>
internal static class SyncEventTypeAutoRegistration {
  /// <summary>
  /// Module initializer that registers all event type mappings.
  /// Called automatically before any code in the assembly runs.
  /// </summary>
  [ModuleInitializer]
  internal static void Initialize() {
    System.Console.WriteLine("[SyncEventTypeAutoRegistration] ModuleInitializer running for assembly: " + typeof(SyncEventTypeAutoRegistration).Assembly.GetName().Name);
    #region EVENT_TYPE_REGISTRATIONS
    // This region gets replaced with generated registration calls
    #endregion
    System.Console.WriteLine("[SyncEventTypeAutoRegistration] ModuleInitializer complete");
  }
}
