#region HEADER
// <auto-generated/>
// Generated at: __TIMESTAMP__
#endregion
#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Whizbang.Core;
using Whizbang.Core.Lenses;
using Whizbang.Data.EFCore.Postgres.Configuration;
using Whizbang.Data.Schema;

namespace Whizbang.Data.EFCore.Postgres.Generated;

/// <summary>
/// Extension methods for configuring Whizbang entities in EF Core.
/// </summary>
public static class WhizbangModelBuilderExtensions {
  /// <summary>
  /// Configures all Whizbang entities (__PERSPECTIVE_COUNT__ perspective(s) + inbox/outbox/eventstore/serviceinstance).
  /// Auto-generated - call from DbContext.OnModelCreating().
  /// Uses EF Core 10 ComplexProperty().ToJson() for JSONB columns (Postgres).
  /// </summary>
  /// <param name="modelBuilder">The ModelBuilder instance</param>
  /// <returns>The ModelBuilder for method chaining</returns>
  public static ModelBuilder ConfigureWhizbang(this ModelBuilder modelBuilder) {

    // Configure infrastructure entities (static configuration from library)
    modelBuilder.ConfigureWhizbangInfrastructure();

    #region PERSPECTIVE_CONFIGURATIONS
    // ===== Discovered Perspective Entities =====
    // Perspective configurations injected here by source generator
    #endregion

    return modelBuilder;
  }

  /// <summary>
  /// Diagnostic information about Whizbang entity discovery.
  /// Provides consistent API for querying what was discovered during source generation.
  /// Implements IWhizbangDiscoveryDiagnostics via a private implementation class.
  /// </summary>
  public static class Diagnostics {
    /// <summary>
    /// Gets the implementation instance that implements IWhizbangDiscoveryDiagnostics.
    /// </summary>
    public static IWhizbangDiscoveryDiagnostics Instance { get; } = new DiagnosticsImpl();

    /// <summary>
    /// Gets the name of the generator that produced this configuration.
    /// </summary>
    public static string GeneratorName => Instance.GeneratorName;

    /// <summary>
    /// Gets the timestamp when the code was generated.
    /// </summary>
    public static string GeneratedTimestamp => Instance.GeneratedTimestamp;

    /// <summary>
    /// Gets the total count of entities configured (perspectives + fixed entities).
    /// </summary>
    public static int TotalDiscoveredCount => Instance.TotalDiscoveredCount;

    /// <summary>
    /// Logs diagnostic information about discovered Whizbang entities.
    /// Call this method during application startup to verify source generation discovered all expected types.
    /// </summary>
    /// <param name="logger">Logger instance for output</param>
    public static void LogDiscoveryDiagnostics(ILogger logger) => Instance.LogDiscoveryDiagnostics(logger);

    /// <summary>
    /// Private implementation of IWhizbangDiscoveryDiagnostics.
    /// </summary>
    private sealed class DiagnosticsImpl : IWhizbangDiscoveryDiagnostics {
      public string GeneratorName => "EFCorePerspectiveConfigurationGenerator";

      public string GeneratedTimestamp => "__TIMESTAMP__";

      public int TotalDiscoveredCount => __TOTAL_ENTITY_COUNT__;

      public void LogDiscoveryDiagnostics(ILogger logger) {
        logger.LogInformation("========== Whizbang EF Core Discovery Diagnostics ==========");
        logger.LogInformation("Generator: {GeneratorName}", GeneratorName);
        logger.LogInformation("Timestamp: {Timestamp}", GeneratedTimestamp);
        logger.LogInformation("");

        #region DIAGNOSTIC_PERSPECTIVE_LIST
        // Perspective list - this region will be replaced
        #endregion

        logger.LogInformation("");
        logger.LogInformation("Fixed Whizbang Entities:");
        logger.LogInformation("  - InboxRecord (table: wh_inbox)");
        logger.LogInformation("  - OutboxRecord (table: wh_outbox)");
        logger.LogInformation("  - EventStoreRecord (table: wh_events)");
        logger.LogInformation("  - ServiceInstanceRecord (table: wh_service_instances)");
        logger.LogInformation("");
        logger.LogInformation("Total Entities Configured: {TotalCount}", TotalDiscoveredCount);
        logger.LogInformation("============================================================");
      }
    }
  }
}
