// Whizbang Message Registry Snippets
// Reusable JSON structure blocks for message registry generation

namespace Whizbang.Generators.Templates.Snippets;

internal static class MessageRegistrySnippets {

  #region MESSAGE_ENTRY_HEADER
    {
      "type": "__MESSAGE_TYPE__",
      "isCommand": __IS_COMMAND__,
      "isEvent": __IS_EVENT__,
      "filePath": "__FILE_PATH__",
      "lineNumber": __LINE_NUMBER__,
  #endregion

  #region DISPATCHER_ENTRY
        {
          "class": "__CLASS_NAME__",
          "method": "__METHOD_NAME__",
          "filePath": "__FILE_PATH__",
          "lineNumber": __LINE_NUMBER__
        }
  #endregion

  #region RECEPTOR_ENTRY
        {
          "class": "__CLASS_NAME__",
          "method": "__METHOD_NAME__",
          "filePath": "__FILE_PATH__",
          "lineNumber": __LINE_NUMBER__
        }
  #endregion

  #region PERSPECTIVE_ENTRY
        {
          "class": "__CLASS_NAME__",
          "method": "Update",
          "filePath": "__FILE_PATH__",
          "lineNumber": __LINE_NUMBER__
        }
  #endregion

  #region MESSAGE_ENTRY_FOOTER
      "dispatchers": [
__DISPATCHERS__
      ],
      "receptors": [
__RECEPTORS__
      ],
      "perspectives": [
__PERSPECTIVES__
      ]
    }
  #endregion

  #region JSON_ARRAY_WRAPPER
{
  "messages": [
__MESSAGES__
  ]
}
  #endregion

  #region CSHARP_WRAPPER
// <auto-generated/>
// Generated by Whizbang.Generators.MessageRegistryGenerator
#nullable enable

namespace Whizbang.Generated;

/// <summary>
/// Auto-generated message registry containing metadata about all discovered messages,
/// dispatchers, receptors, and perspectives in the application.
/// </summary>
internal static class MessageRegistry {
  /// <summary>
  /// JSON representation of the message registry.
  /// Used by the VSCode extension for code navigation and visualization.
  /// </summary>
  internal const string Json = @"__JSON__";
}
  #endregion
}
