using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Logging;
using Whizbang.Core;
using Whizbang.Core.Data;
using Whizbang.Core.Messaging;
using Whizbang.Core.Policies;
using Whizbang.Core.Sequencing;
using Whizbang.Data.Dapper.Custom;
using Whizbang.Data.Postgres;

namespace Whizbang.Data.Dapper.Postgres;

/// <summary>
/// Extension methods for registering Whizbang PostgreSQL stores with dependency injection.
/// </summary>
/// <tests>tests/Whizbang.Data.Postgres.Tests/ServiceCollectionExtensionsTests.cs:AddWhizbangPostgres_InitializeSchemaFalse_DoesNotInitializeAsync</tests>
/// <tests>tests/Whizbang.Data.Postgres.Tests/ServiceCollectionExtensionsTests.cs:AddWhizbangPostgres_InitializeSchemaTrue_NoPerspective_InitializesInfraOnlyAsync</tests>
/// <tests>tests/Whizbang.Data.Postgres.Tests/ServiceCollectionExtensionsTests.cs:AddWhizbangPostgres_InitializeSchemaTrue_WithPerspective_InitializesBothAsync</tests>
public static class ServiceCollectionExtensions {
  /// <summary>
  /// Registers all Whizbang PostgreSQL stores (EventStore, WorkCoordinator, RequestResponseStore, SequenceProvider)
  /// along with the required database infrastructure (connection factory and executor).
  /// </summary>
  /// <param name="services">The service collection to register services with.</param>
  /// <param name="connectionString">The PostgreSQL connection string.</param>
  /// <param name="jsonOptions">The JSON serializer options configured with the application's WhizbangJsonContext.</param>
  /// <param name="initializeSchema">Whether to automatically initialize the Whizbang schema on startup. Default is false.</param>
  /// <param name="perspectiveSchemaSql">Optional perspective schema SQL generated by PerspectiveSchemaGenerator. Pass Whizbang.Generated.PerspectiveSchemas.Sql to auto-create perspective tables.</param>
  /// <returns>The service collection for chaining.</returns>
  /// <tests>tests/Whizbang.Data.Postgres.Tests/ServiceCollectionExtensionsTests.cs:AddWhizbangPostgres_InitializeSchemaFalse_DoesNotInitializeAsync</tests>
  /// <tests>tests/Whizbang.Data.Postgres.Tests/ServiceCollectionExtensionsTests.cs:AddWhizbangPostgres_InitializeSchemaTrue_NoPerspective_InitializesInfraOnlyAsync</tests>
  /// <tests>tests/Whizbang.Data.Postgres.Tests/ServiceCollectionExtensionsTests.cs:AddWhizbangPostgres_InitializeSchemaTrue_WithPerspective_InitializesBothAsync</tests>
  public static IServiceCollection AddWhizbangPostgres(
    this IServiceCollection services,
    string connectionString,
    JsonSerializerOptions jsonOptions,
    bool initializeSchema = false,
    string? perspectiveSchemaSql = null) {
    return AddWhizbangPostgres(services, connectionString, jsonOptions, initializeSchema, perspectiveSchemaSql, configureOptions: null);
  }

  /// <summary>
  /// Registers all Whizbang PostgreSQL stores with per-perspective hash tracking.
  /// Uses PerspectiveSchemas.Entries for individual perspective change detection.
  /// </summary>
  /// <param name="services">The service collection to register services with.</param>
  /// <param name="connectionString">The PostgreSQL connection string.</param>
  /// <param name="jsonOptions">The JSON serializer options configured with the application's WhizbangJsonContext.</param>
  /// <param name="initializeSchema">Whether to automatically initialize the Whizbang schema on startup.</param>
  /// <param name="perspectiveEntries">Per-perspective SQL entries from PerspectiveSchemas.Entries for individual hash tracking.</param>
  /// <returns>The service collection for chaining.</returns>
  public static IServiceCollection AddWhizbangPostgres(
    this IServiceCollection services,
    string connectionString,
    JsonSerializerOptions jsonOptions,
    bool initializeSchema,
    KeyValuePair<string, string>[] perspectiveEntries) {
    return AddWhizbangPostgres(services, connectionString, jsonOptions, initializeSchema, perspectiveEntries, configureOptions: null);
  }

  /// <summary>
  /// Registers all Whizbang PostgreSQL stores with per-perspective hash tracking and configurable options.
  /// </summary>
  [SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "Startup logging doesn't need high performance optimization")]
  public static IServiceCollection AddWhizbangPostgres(
    this IServiceCollection services,
    string connectionString,
    JsonSerializerOptions jsonOptions,
    bool initializeSchema,
    KeyValuePair<string, string>[] perspectiveEntries,
    Action<PostgresOptions>? configureOptions) {
    ArgumentException.ThrowIfNullOrWhiteSpace(connectionString);
    ArgumentNullException.ThrowIfNull(jsonOptions);
    ArgumentNullException.ThrowIfNull(perspectiveEntries);

    // Configure options
    var options = new PostgresOptions();
    configureOptions?.Invoke(options);

    // Build a temporary service provider to get logger (if logging is configured)
    var tempProvider = services.BuildServiceProvider();
    var logger = tempProvider.GetService<ILogger<PostgresConnectionRetry>>();

    // Wait for database connection with retry
    if (logger?.IsEnabled(LogLevel.Information) == true) {
      var initialRetryAttempts = options.InitialRetryAttempts;
      var retryIndefinitely = options.RetryIndefinitely;
      logger.LogInformation("Waiting for PostgreSQL connection (initial {InitialAttempts} attempts, then indefinitely={RetryIndefinitely})", initialRetryAttempts, retryIndefinitely);
    }
    var connectionRetry = new PostgresConnectionRetry(options, logger);
    connectionRetry.WaitForConnectionAsync(connectionString).GetAwaiter().GetResult();

    // Initialize schema with per-perspective hash tracking
    if (initializeSchema) {
      logger?.LogInformation("Initializing PostgreSQL schema with per-perspective tracking...");
      var initializer = new PostgresSchemaInitializer(connectionString, perspectiveEntries);
      initializer.InitializeSchema();
      logger?.LogInformation("PostgreSQL schema initialized");

      logger?.LogInformation("Waiting for PostgreSQL schema to be ready...");
      connectionRetry.WaitForSchemaReadyAsync(connectionString).GetAwaiter().GetResult();
      logger?.LogInformation("PostgreSQL database ready");
    }

    // Register database infrastructure
    services.AddSingleton<IDbConnectionFactory>(sp =>
      new PostgresConnectionFactory(connectionString));
    services.AddSingleton<IDbExecutor, DapperDbExecutor>();

    services.AddSingleton(options);
    services.AddSingleton(jsonOptions);

    services.TryAddSingleton<IPolicyEngine, PolicyEngine>();

    services.AddSingleton<IJsonbPersistenceAdapter<Whizbang.Core.Observability.IMessageEnvelope>, EventEnvelopeJsonbAdapter>();
    services.AddSingleton<JsonbSizeValidator>();

    services.AddSingleton<IDatabaseReadinessCheck>(sp => {
      var readinessLogger = sp.GetService<ILogger<PostgresDatabaseReadinessCheck>>();
      return new PostgresDatabaseReadinessCheck(connectionString, readinessLogger!);
    });

    services.AddScoped<IEventStore, DapperPostgresEventStore>();
    services.AddSingleton<IWorkCoordinator, DapperWorkCoordinator>();
    services.AddSingleton<IRequestResponseStore, DapperPostgresRequestResponseStore>();
    services.AddSingleton<ISequenceProvider, DapperPostgresSequenceProvider>();

    services.DecorateEventStoreWithSyncTracking();

    return services;
  }

  /// <summary>
  /// Registers all Whizbang PostgreSQL stores with configurable connection retry options.
  /// Waits for database connection and schema to be ready before completing registration.
  /// </summary>
  /// <param name="services">The service collection to register services with.</param>
  /// <param name="connectionString">The PostgreSQL connection string.</param>
  /// <param name="jsonOptions">The JSON serializer options configured with the application's WhizbangJsonContext.</param>
  /// <param name="initializeSchema">Whether to automatically initialize the Whizbang schema on startup. Default is false.</param>
  /// <param name="perspectiveSchemaSql">Optional perspective schema SQL generated by PerspectiveSchemaGenerator.</param>
  /// <param name="configureOptions">Optional configuration callback for PostgreSQL options (retry settings, etc.).</param>
  /// <returns>The service collection for chaining.</returns>
  [SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "Startup logging doesn't need high performance optimization")]
  public static IServiceCollection AddWhizbangPostgres(
    this IServiceCollection services,
    string connectionString,
    JsonSerializerOptions jsonOptions,
    bool initializeSchema,
    string? perspectiveSchemaSql,
    Action<PostgresOptions>? configureOptions) {
    ArgumentException.ThrowIfNullOrWhiteSpace(connectionString);
    ArgumentNullException.ThrowIfNull(jsonOptions);

    // Configure options
    var options = new PostgresOptions();
    configureOptions?.Invoke(options);

    // Build a temporary service provider to get logger (if logging is configured)
    var tempProvider = services.BuildServiceProvider();
    var logger = tempProvider.GetService<ILogger<PostgresConnectionRetry>>();

    // Wait for database connection with retry
    if (logger?.IsEnabled(LogLevel.Information) == true) {
      var initialRetryAttempts = options.InitialRetryAttempts;
      var retryIndefinitely = options.RetryIndefinitely;
      logger.LogInformation("Waiting for PostgreSQL connection (initial {InitialAttempts} attempts, then indefinitely={RetryIndefinitely})", initialRetryAttempts, retryIndefinitely);
    }
    var connectionRetry = new PostgresConnectionRetry(options, logger);
    connectionRetry.WaitForConnectionAsync(connectionString).GetAwaiter().GetResult();

    // Initialize schema if requested
    if (initializeSchema) {
      logger?.LogInformation("Initializing PostgreSQL schema...");
      var initializer = new PostgresSchemaInitializer(connectionString, perspectiveSchemaSql);
      initializer.InitializeSchema();
      logger?.LogInformation("PostgreSQL schema initialized");

      // Wait for schema to be ready (tables and functions exist)
      // This ensures workers don't start until schema is fully initialized
      logger?.LogInformation("Waiting for PostgreSQL schema to be ready...");
      connectionRetry.WaitForSchemaReadyAsync(connectionString).GetAwaiter().GetResult();
      logger?.LogInformation("PostgreSQL database ready");
    }

    // Register database infrastructure
    services.AddSingleton<IDbConnectionFactory>(sp =>
      new PostgresConnectionFactory(connectionString));
    services.AddSingleton<IDbExecutor, DapperDbExecutor>();

    // Register PostgresOptions for components that need retry settings
    services.AddSingleton(options);

    // Register JSON serialization options
    services.AddSingleton(jsonOptions);

    // Register policy engine if not already registered
    services.TryAddSingleton<IPolicyEngine, PolicyEngine>();

    // Register JSONB persistence infrastructure
    services.AddSingleton<IJsonbPersistenceAdapter<Whizbang.Core.Observability.IMessageEnvelope>, EventEnvelopeJsonbAdapter>();
    services.AddSingleton<JsonbSizeValidator>();

    // Register database readiness check - CRITICAL for worker startup
    // This prevents workers from starting before schema is initialized
    services.AddSingleton<IDatabaseReadinessCheck>(sp => {
      var readinessLogger = sp.GetService<ILogger<PostgresDatabaseReadinessCheck>>();
      return new PostgresDatabaseReadinessCheck(connectionString, readinessLogger!);
    });

    // Register Whizbang stores
    // IEventStore is registered as Scoped to allow injection of scoped IPerspectiveInvoker
    services.AddScoped<IEventStore, DapperPostgresEventStore>();
    services.AddSingleton<IWorkCoordinator, DapperWorkCoordinator>();
    services.AddSingleton<IRequestResponseStore, DapperPostgresRequestResponseStore>();
    services.AddSingleton<ISequenceProvider, DapperPostgresSequenceProvider>();

    // TURNKEY: Wrap IEventStore with sync tracking decorator
    // This enables perspective synchronization by tracking emitted events
    // before they reach the database (cross-scope sync support)
    services.DecorateEventStoreWithSyncTracking();

    return services;
  }

  /// <summary>
  /// Registers health checks for PostgreSQL connectivity.
  /// Requires Microsoft.Extensions.Diagnostics.HealthChecks package.
  /// </summary>
  /// <param name="services">The service collection to register health checks with.</param>
  /// <returns>The service collection for chaining.</returns>
  /// <tests>tests/Whizbang.Data.Postgres.Tests/ServiceCollectionExtensionsTests.cs:AddWhizbangPostgresHealthChecks_RegistersHealthCheckAsync</tests>
  public static IServiceCollection AddWhizbangPostgresHealthChecks(this IServiceCollection services) {
    services.AddHealthChecks()
      .AddCheck<PostgresHealthCheck>("whizbang_postgres");

    return services;
  }
}
