using System.Text.Json;
using Whizbang.Core.Attributes;

namespace Whizbang.Core.Tags;

/// <summary>
/// Registration entry for a message type with tag attributes.
/// Generated by the MessageTagDiscoveryGenerator for AOT-compatible tag discovery.
/// </summary>
/// <remarks>
/// <para>
/// This record is populated by the source generator at compile time.
/// It provides pre-compiled payload builders for efficient runtime execution.
/// </para>
/// </remarks>
/// <docs>fundamentals/messages/message-tags#registration</docs>
/// <tests>Whizbang.Core.Tests/Tags/MessageTagRegistrationTests.cs</tests>
/// <tests>tests/Whizbang.Core.Tests/Tags/MessageTagProcessorTests.cs:ProcessTagsAsync_WithMatchingTag_InvokesHookAsync</tests>
/// <tests>tests/Whizbang.Core.Tests/Tags/MessageTagProcessorTests.cs:ProcessTagsAsync_WithMultipleTags_ProcessesAllAsync</tests>
/// <tests>tests/Whizbang.Core.Tests/Tags/TagHookStageFilteringAndScopeTests.cs:ProcessTagsAsync_TwoHooksAtDifferentStages_EachFiresOnlyAtItsStageAsync</tests>
public sealed record MessageTagRegistration {
  /// <summary>
  /// The message type that has the tag attribute.
  /// </summary>
  public required Type MessageType { get; init; }

  /// <summary>
  /// The tag attribute type (e.g., SignalTagAttribute, TelemetryTagAttribute).
  /// </summary>
  public required Type AttributeType { get; init; }

  /// <summary>
  /// The tag value from the attribute.
  /// </summary>
  public required string Tag { get; init; }

  /// <summary>
  /// Properties to extract from the message for the payload.
  /// </summary>
  public string[]? Properties { get; init; }

  /// <summary>
  /// Extra JSON to merge into the payload.
  /// </summary>
  public string? ExtraJson { get; init; }

  /// <summary>
  /// Source-generated delegate that builds the payload JsonElement from a message.
  /// Compiled at compile-time for AOT compatibility - no reflection at runtime.
  /// </summary>
  public required Func<object, JsonElement> PayloadBuilder { get; init; }

  /// <summary>
  /// Source-generated factory that creates the attribute instance.
  /// </summary>
  public required Func<MessageTagAttribute> AttributeFactory { get; init; }
}
