using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Whizbang.Sagas.Generators;

/// <summary>
/// Incremental source generator for <c>[Saga&lt;TBase&gt;("Name")]</c> and
/// <c>[Saga("Name")]</c>. Discovers partial classes carrying the
/// attribute and emits nine nested event classes, a typed
/// <c>Service</c> subclass of <c>BaseSagaService</c>, and a
/// <c>Add{SagaName}Saga</c> extension method.
/// </summary>
[Generator]
public sealed class SagaGenerator : IIncrementalGenerator {

  // SagaAttribute and SagaAttribute<TEventBase> live in
  // Whizbang.Sagas.Contracts as regular runtime types — not emitted via
  // post-init source. dotnet format and other tools that don't fully
  // execute generators see them like any other declared attribute,
  // which keeps the build-then-verify-format pipeline clean.

  private static readonly DiagnosticDescriptor _wsaga004NotPartial = new(
    id: "WSAGA004",
    title: "[Saga] type must be partial",
    messageFormat: "The [Saga]-marked type '{0}' must be declared 'partial' so the generator can emit nested event classes into it",
    category: "Whizbang.Sagas",
    defaultSeverity: DiagnosticSeverity.Error,
    isEnabledByDefault: true);

  public void Initialize(IncrementalGeneratorInitializationContext context) {
    var sagaDecls = context.SyntaxProvider
      .ForAttributeWithMetadataName(
        "Whizbang.Sagas.SagaAttribute",
        predicate: static (node, _) => node is ClassDeclarationSyntax,
        transform: static (ctx, _) => _extractSagaInfo(ctx, hasTypeArg: false))
      .Where(static info => info is not null)
      .Select(static (info, _) => info!);

    var genericDecls = context.SyntaxProvider
      .ForAttributeWithMetadataName(
        "Whizbang.Sagas.SagaAttribute`1",
        predicate: static (node, _) => node is ClassDeclarationSyntax,
        transform: static (ctx, _) => _extractSagaInfo(ctx, hasTypeArg: true))
      .Where(static info => info is not null)
      .Select(static (info, _) => info!);

    var allDecls = sagaDecls.Collect().Combine(genericDecls.Collect());

    context.RegisterSourceOutput(allDecls, (spc, tuple) => {
      var (plain, generic) = tuple;
      foreach (var info in plain) {
        _emit(spc, info);
      }
      foreach (var info in generic) {
        _emit(spc, info);
      }
    });
  }

  private static SagaInfo? _extractSagaInfo(GeneratorAttributeSyntaxContext ctx, bool hasTypeArg) {
    if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) {
      return null;
    }
    var classDecl = (ClassDeclarationSyntax)ctx.TargetNode;
    var isPartial = classDecl.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword));

    var attrData = ctx.Attributes.FirstOrDefault();
    if (attrData is null) {
      return null;
    }

    var sagaName = attrData.ConstructorArguments.Length > 0
      ? attrData.ConstructorArguments[0].Value as string
      : null;
    if (string.IsNullOrWhiteSpace(sagaName)) {
      return null;
    }

    bool includeHooks = true, generateService = true;
    foreach (var na in attrData.NamedArguments) {
      if (na.Key == "IncludeHooks") {
        includeHooks = (bool)(na.Value.Value ?? true);
      }
      if (na.Key == "GenerateService") {
        generateService = (bool)(na.Value.Value ?? true);
      }
    }

    string eventBaseFullName = "global::Whizbang.Sagas.SagaEventBase";
    if (hasTypeArg && attrData.AttributeClass is { TypeArguments: { Length: 1 } typeArgs } && typeArgs[0] is INamedTypeSymbol baseSymbol) {
      eventBaseFullName = "global::" + baseSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", "");
    }

    return new SagaInfo(
      @namespace: typeSymbol.ContainingNamespace.IsGlobalNamespace ? null : typeSymbol.ContainingNamespace.ToDisplayString(),
      className: typeSymbol.Name,
      sagaName: sagaName!,
      eventBaseFullName: eventBaseFullName,
      includeHooks: includeHooks,
      generateService: generateService,
      isPartial: isPartial,
      location: classDecl.Identifier.GetLocation());
  }

  private static void _emit(SourceProductionContext spc, SagaInfo info) {
    if (!info.IsPartial) {
      spc.ReportDiagnostic(Diagnostic.Create(_wsaga004NotPartial, info.Location, info.ClassName));
      return;
    }

    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("#nullable enable");
    if (info.Namespace is not null) {
      sb.Append("namespace ").Append(info.Namespace).AppendLine(";");
      sb.AppendLine();
    }
    sb.Append("partial class ").Append(info.ClassName).AppendLine(" {");
    sb.Append("  public const string SagaName = \"").Append(info.SagaName).AppendLine("\";");
    sb.AppendLine();

    _emitInitiated(sb, info);
    _emitItemsDispatched(sb, info);
    _emitItemStarted(sb, info);
    _emitItemCompleted(sb, info);
    _emitItemFailed(sb, info);
    _emitCompleted(sb, info);
    _emitReset(sb, info);
    if (info.IncludeHooks) {
      _emitHookStarted(sb, info);
      _emitHookCompleted(sb, info);
    }

    if (info.GenerateService) {
      _emitService(sb, info);
    }

    sb.AppendLine("}");

    if (info.GenerateService) {
      _emitServiceCollectionExtension(sb, info);
    }

    var fileName = (info.Namespace is null ? "" : info.Namespace + ".") + info.ClassName + ".g.cs";
    spc.AddSource(fileName, SourceText.From(sb.ToString(), Encoding.UTF8));
  }

  // ── Per-event emitters ───────────────────────────────────────────────

  private static void _emitInitiated(StringBuilder sb, SagaInfo info) {
    sb.Append("  public sealed partial class InitiatedEvent : ").Append(info.EventBaseFullName).AppendLine(", global::Whizbang.Sagas.ISagaInitiatedEvent {");
    sb.Append("    public string SagaName { get; set; } = \"").Append(info.SagaName).AppendLine("\";");
    sb.AppendLine("    [global::Whizbang.Core.StreamId] public global::System.Guid EntityId { get; set; }");
    sb.AppendLine("    public global::System.Collections.Generic.IReadOnlyList<string> ItemIdentifiers { get; set; } = global::System.Array.Empty<string>();");
    sb.AppendLine("    public int TotalItems { get; set; }");
    sb.AppendLine("    public global::System.Collections.Generic.IReadOnlyList<string>? HookNames { get; set; }");
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static void _emitItemsDispatched(StringBuilder sb, SagaInfo info) {
    sb.Append("  public sealed partial class ItemsDispatchedEvent : ").Append(info.EventBaseFullName).AppendLine(", global::Whizbang.Sagas.ISagaItemsDispatchedEvent {");
    sb.Append("    public string SagaName { get; set; } = \"").Append(info.SagaName).AppendLine("\";");
    sb.AppendLine("    [global::Whizbang.Core.StreamId] public global::System.Guid EntityId { get; set; }");
    sb.AppendLine("    public int TotalItems { get; set; }");
    sb.AppendLine("    public int SuccessfullyDispatched { get; set; }");
    sb.AppendLine("    public int FailedToDispatch { get; set; }");
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static void _emitItemStarted(StringBuilder sb, SagaInfo info) {
    sb.Append("  public sealed partial class ItemStartedEvent : ").Append(info.EventBaseFullName).AppendLine(", global::Whizbang.Sagas.ISagaItemStartedEvent {");
    sb.Append("    public string SagaName { get; set; } = \"").Append(info.SagaName).AppendLine("\";");
    sb.AppendLine("    [global::Whizbang.Core.StreamId] public global::System.Guid EntityId { get; set; }");
    sb.AppendLine("    public global::System.Guid SagaId { get; set; }");
    sb.AppendLine("    public string ItemIdentifier { get; set; } = \"\";");
    sb.AppendLine("    public string? DisplayName { get; set; }");
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static void _emitItemCompleted(StringBuilder sb, SagaInfo info) {
    sb.Append("  public sealed partial class ItemCompletedEvent : ").Append(info.EventBaseFullName).AppendLine(", global::Whizbang.Sagas.ISagaItemCompletedEvent {");
    sb.Append("    public string SagaName { get; set; } = \"").Append(info.SagaName).AppendLine("\";");
    sb.AppendLine("    [global::Whizbang.Core.StreamId] public global::System.Guid EntityId { get; set; }");
    sb.AppendLine("    public global::System.Guid SagaId { get; set; }");
    sb.AppendLine("    public string ItemIdentifier { get; set; } = \"\";");
    sb.AppendLine("    public string? DisplayName { get; set; }");
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static void _emitItemFailed(StringBuilder sb, SagaInfo info) {
    sb.Append("  public sealed partial class ItemFailedEvent : ").Append(info.EventBaseFullName).AppendLine(", global::Whizbang.Sagas.ISagaItemFailedEvent {");
    sb.Append("    public string SagaName { get; set; } = \"").Append(info.SagaName).AppendLine("\";");
    sb.AppendLine("    [global::Whizbang.Core.StreamId] public global::System.Guid EntityId { get; set; }");
    sb.AppendLine("    public global::System.Guid SagaId { get; set; }");
    sb.AppendLine("    public string ItemIdentifier { get; set; } = \"\";");
    sb.AppendLine("    public string? DisplayName { get; set; }");
    sb.AppendLine("    public string ErrorMessage { get; set; } = \"\";");
    sb.AppendLine("    public string? ErrorDetails { get; set; }");
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static void _emitCompleted(StringBuilder sb, SagaInfo info) {
    sb.Append("  public sealed partial class CompletedEvent : ").Append(info.EventBaseFullName).AppendLine(", global::Whizbang.Sagas.ISagaCompletedEvent {");
    sb.Append("    public string SagaName { get; set; } = \"").Append(info.SagaName).AppendLine("\";");
    sb.AppendLine("    [global::Whizbang.Core.StreamId] public global::System.Guid EntityId { get; set; }");
    sb.AppendLine("    public global::Whizbang.Sagas.SagaStatus FinalStatus { get; set; }");
    sb.AppendLine("    public string? CompletedByItemIdentifier { get; set; }");
    sb.AppendLine("    public int CompletedItems { get; set; }");
    sb.AppendLine("    public int FailedItems { get; set; }");
    sb.AppendLine("    public int TotalItems { get; set; }");
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static void _emitReset(StringBuilder sb, SagaInfo info) {
    sb.Append("  public sealed partial class ResetEvent : ").Append(info.EventBaseFullName).AppendLine(", global::Whizbang.Sagas.ISagaResetEvent {");
    sb.Append("    public string SagaName { get; set; } = \"").Append(info.SagaName).AppendLine("\";");
    sb.AppendLine("    [global::Whizbang.Core.StreamId] public global::System.Guid EntityId { get; set; }");
    sb.AppendLine("    public string ItemIdentifier { get; set; } = \"\";");
    sb.AppendLine("    public global::Whizbang.Sagas.SagaItemState PreviousStatus { get; set; }");
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static void _emitHookStarted(StringBuilder sb, SagaInfo info) {
    sb.Append("  public sealed partial class HookStartedEvent : ").Append(info.EventBaseFullName).AppendLine(", global::Whizbang.Sagas.ISagaHookStartedEvent {");
    sb.Append("    public string SagaName { get; set; } = \"").Append(info.SagaName).AppendLine("\";");
    sb.AppendLine("    [global::Whizbang.Core.StreamId] public global::System.Guid EntityId { get; set; }");
    sb.AppendLine("    public string HookName { get; set; } = \"\";");
    sb.AppendLine("    public string? DisplayName { get; set; }");
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static void _emitHookCompleted(StringBuilder sb, SagaInfo info) {
    sb.Append("  public sealed partial class HookCompletedEvent : ").Append(info.EventBaseFullName).AppendLine(", global::Whizbang.Sagas.ISagaHookCompletedEvent {");
    sb.Append("    public string SagaName { get; set; } = \"").Append(info.SagaName).AppendLine("\";");
    sb.AppendLine("    [global::Whizbang.Core.StreamId] public global::System.Guid EntityId { get; set; }");
    sb.AppendLine("    public string HookName { get; set; } = \"\";");
    sb.AppendLine("    public string? DisplayName { get; set; }");
    sb.AppendLine("    public global::Whizbang.Sagas.SagaItemState Status { get; set; }");
    sb.AppendLine("    public string? ErrorMessage { get; set; }");
    sb.AppendLine("    public string? ErrorDetails { get; set; }");
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  // ── Service class ────────────────────────────────────────────────────

  private static void _emitService(StringBuilder sb, SagaInfo info) {
    sb.AppendLine("  public sealed class Service : global::Whizbang.Sagas.Services.BaseSagaService<");
    sb.AppendLine("    InitiatedEvent, ItemsDispatchedEvent, ItemStartedEvent, ItemCompletedEvent,");
    sb.AppendLine("    ItemFailedEvent, CompletedEvent, ResetEvent, HookStartedEvent, HookCompletedEvent> {");
    sb.AppendLine();
    sb.AppendLine("    public Service(global::Whizbang.Sagas.Services.ISagaEventEmitter emitter,");
    sb.AppendLine("                   global::Microsoft.Extensions.Logging.ILogger<Service> logger)");
    sb.Append("      : base(").Append(info.ClassName).AppendLine(".SagaName, emitter, logger) { }");
    sb.AppendLine();
    sb.AppendLine("    protected override InitiatedEvent BuildInitiatedEvent(global::Whizbang.Sagas.SagaContext ctx, global::System.Collections.Generic.IReadOnlyList<string> itemIdentifiers, global::System.Collections.Generic.IReadOnlyList<string>? hookNames, global::System.DateTimeOffset sentAt) =>");
    sb.AppendLine("      new() { EntityId = ctx.EntityId, ItemIdentifiers = itemIdentifiers, TotalItems = itemIdentifiers.Count, HookNames = hookNames };");
    sb.AppendLine();
    sb.AppendLine("    protected override ItemsDispatchedEvent BuildItemsDispatchedEvent(global::Whizbang.Sagas.SagaContext ctx, int totalItems, int successfullyDispatched, int failedToDispatch, global::System.DateTimeOffset sentAt) =>");
    sb.AppendLine("      new() { EntityId = ctx.EntityId, TotalItems = totalItems, SuccessfullyDispatched = successfullyDispatched, FailedToDispatch = failedToDispatch };");
    sb.AppendLine();
    sb.AppendLine("    protected override ItemStartedEvent BuildItemStartedEvent(global::Whizbang.Sagas.SagaContext ctx, string itemIdentifier, string? displayName, global::System.DateTimeOffset sentAt) =>");
    sb.AppendLine("      new() { EntityId = ctx.EntityId, SagaId = ctx.SagaId, ItemIdentifier = itemIdentifier, DisplayName = displayName };");
    sb.AppendLine();
    sb.AppendLine("    protected override ItemCompletedEvent BuildItemCompletedEvent(global::Whizbang.Sagas.SagaContext ctx, string itemIdentifier, string? displayName, global::System.DateTimeOffset sentAt) =>");
    sb.AppendLine("      new() { EntityId = ctx.EntityId, SagaId = ctx.SagaId, ItemIdentifier = itemIdentifier, DisplayName = displayName };");
    sb.AppendLine();
    sb.AppendLine("    protected override ItemFailedEvent BuildItemFailedEvent(global::Whizbang.Sagas.SagaContext ctx, string itemIdentifier, string errorMessage, string? errorDetails, string? displayName, global::System.DateTimeOffset sentAt) =>");
    sb.AppendLine("      new() { EntityId = ctx.EntityId, SagaId = ctx.SagaId, ItemIdentifier = itemIdentifier, DisplayName = displayName, ErrorMessage = errorMessage, ErrorDetails = errorDetails };");
    sb.AppendLine();
    sb.AppendLine("    protected override CompletedEvent BuildCompletedEvent(global::Whizbang.Sagas.SagaContext ctx, global::Whizbang.Sagas.SagaStatus finalStatus, string? completedByItemIdentifier, int completedItems, int failedItems, int totalItems, global::System.DateTimeOffset sentAt) =>");
    sb.AppendLine("      new() { EntityId = ctx.EntityId, FinalStatus = finalStatus, CompletedByItemIdentifier = completedByItemIdentifier, CompletedItems = completedItems, FailedItems = failedItems, TotalItems = totalItems };");
    sb.AppendLine();
    sb.AppendLine("    protected override ResetEvent BuildResetEvent(global::Whizbang.Sagas.SagaContext ctx, string itemIdentifier, global::Whizbang.Sagas.SagaItemState previousStatus, global::System.DateTimeOffset sentAt) =>");
    sb.AppendLine("      new() { EntityId = ctx.EntityId, ItemIdentifier = itemIdentifier, PreviousStatus = previousStatus };");
    sb.AppendLine();
    if (info.IncludeHooks) {
      sb.AppendLine("    protected override HookStartedEvent BuildHookStartedEvent(global::Whizbang.Sagas.SagaContext ctx, string hookName, string? displayName, global::System.DateTimeOffset sentAt) =>");
      sb.AppendLine("      new() { EntityId = ctx.EntityId, HookName = hookName, DisplayName = displayName };");
      sb.AppendLine();
      sb.AppendLine("    protected override HookCompletedEvent BuildHookCompletedEvent(global::Whizbang.Sagas.SagaContext ctx, string hookName, global::Whizbang.Sagas.SagaItemState status, string? errorMessage, string? errorDetails, global::System.DateTimeOffset sentAt) =>");
      sb.AppendLine("      new() { EntityId = ctx.EntityId, HookName = hookName, Status = status, ErrorMessage = errorMessage, ErrorDetails = errorDetails };");
    } else {
      sb.AppendLine("    protected override HookStartedEvent BuildHookStartedEvent(global::Whizbang.Sagas.SagaContext ctx, string hookName, string? displayName, global::System.DateTimeOffset sentAt) =>");
      sb.AppendLine("      throw new global::System.InvalidOperationException(\"This saga was generated with IncludeHooks = false.\");");
      sb.AppendLine();
      sb.AppendLine("    protected override HookCompletedEvent BuildHookCompletedEvent(global::Whizbang.Sagas.SagaContext ctx, string hookName, global::Whizbang.Sagas.SagaItemState status, string? errorMessage, string? errorDetails, global::System.DateTimeOffset sentAt) =>");
      sb.AppendLine("      throw new global::System.InvalidOperationException(\"This saga was generated with IncludeHooks = false.\");");
    }
    sb.AppendLine("  }");
  }

  private static void _emitServiceCollectionExtension(StringBuilder sb, SagaInfo info) {
    sb.AppendLine();
    sb.Append("public static class ").Append(info.ClassName).AppendLine("ServiceCollectionExtensions {");
    sb.Append("  public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Add").Append(info.ClassName).AppendLine("(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services) =>");
    sb.Append("    global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<").Append(info.Namespace is null ? "" : info.Namespace + ".").Append(info.ClassName).AppendLine(".Service>(services);");
    sb.AppendLine("}");
  }

  private sealed class SagaInfo {
    public SagaInfo(string? @namespace, string className, string sagaName, string eventBaseFullName, bool includeHooks, bool generateService, bool isPartial, Location location) {
      Namespace = @namespace;
      ClassName = className;
      SagaName = sagaName;
      EventBaseFullName = eventBaseFullName;
      IncludeHooks = includeHooks;
      GenerateService = generateService;
      IsPartial = isPartial;
      Location = location;
    }
    public string? Namespace { get; }
    public string ClassName { get; }
    public string SagaName { get; }
    public string EventBaseFullName { get; }
    public bool IncludeHooks { get; }
    public bool GenerateService { get; }
    public bool IsPartial { get; }
    public Location Location { get; }
  }
}
