using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using TUnit.Assertions;
using TUnit.Assertions.Extensions;
using TUnit.Core;
using Whizbang.Core;
using Whizbang.Core.Lenses;
using Whizbang.Core.Perspectives;
using Whizbang.Data.EFCore.Postgres.QueryTranslation;
using Whizbang.Data.EFCore.Postgres.QueryTranslation.Containment;

namespace Whizbang.Data.EFCore.Postgres.Tests.QueryTranslation;

/// <summary>
/// The compiled-SQL matrix for perspective queries: every field type crossed with every operator,
/// value source, composition and query shape that a repository can reasonably write.
/// </summary>
/// <remarks>
/// <para>
/// A perspective filter has three possible destinations and they are indistinguishable in the LINQ.
/// It can read a promoted column, it can be answered from the GIN index as a containment test, or it
/// falls back to extracting the value out of the JSON document for every row. Which one happens
/// decides whether a query is a lookup or a table scan, so each combination is pinned here rather
/// than left to be discovered under load.
/// </para>
/// <para>
/// Cases are generated by crossing the dimensions instead of being written out, so adding a type or
/// an operator adds a row to every relevant axis at once. Nothing opens a connection, so the whole
/// matrix runs in about a second.
/// </para>
/// </remarks>
/// <docs>fundamentals/perspectives/physical-fields#index-advisories</docs>
/// <docs>operations/diagnostics/whiz302</docs>
[NotInParallel("EFCorePostgresTests")]
[Category("Shard1")]
public class JsonbContainmentSqlMatrixTests {
  private const string UNUSED_CONNECTION = "Host=localhost;Database=matrix;Username=u;Password=p";

  /// <summary>Where a filter ended up.</summary>
  public enum Destination {
    /// <summary>Answered from the GIN index as a containment test.</summary>
    Containment,

    /// <summary>Extracted out of the JSON document per row.</summary>
    Extraction,

    /// <summary>Read from a promoted column.</summary>
    PhysicalColumn,

    /// <summary>Read from one of the row's own columns.</summary>
    RowColumn,

    /// <summary>
    /// Entity Framework refuses the expression outright, so the query fails at compile time rather
    /// than running slowly.
    /// </summary>
    /// <remarks>
    /// A distinct outcome from extraction and worth naming, because the two are opposite problems. An
    /// extraction runs and returns the right rows without an index; this does not run at all. A
    /// capability table that lumped them together would tell a reader their query is merely slow when
    /// in fact it throws.
    /// </remarks>
    Untranslatable,
  }

  public enum Status { Draft, Live, Retired }

  /// <summary>A combinable enumeration, where one stored value is a set of members.</summary>
  [Flags]
  public enum Access { None = 0, Read = 1, Write = 2 }

  [SuppressIndexAdvisory("the matrix exists to compile every shape, never to run one")]
  public class MatrixModel {
    [StreamId]
    public Guid StreamKey { get; init; }

    // Promoted to real columns.
    [PhysicalField(Indexed = true)]
    public Guid PhysGuid { get; init; }

    [PhysicalField(Indexed = true)]
    public int PhysInt { get; init; }

    [PhysicalField(Unique = true)]
    public string PhysString { get; init; } = string.Empty;

    // JSON-only scalars whose serialized text and PostgreSQL's agree.
    public string Str { get; init; } = string.Empty;
    public Guid Gid { get; init; }
    public bool Flag { get; init; }
    public short Small { get; init; }
    public int Num { get; init; }
    public long Big { get; init; }
    public decimal Money { get; init; }

    // JSON-only, but their two text forms are not guaranteed to agree.
    public double Dbl { get; init; }
    public float Flt { get; init; }
    public DateTime When { get; init; }
    public DateTimeOffset WhenOffset { get; init; }
    public Status State { get; init; }
    public Access Perms { get; init; }

    // Nullable.
    public string? MaybeStr { get; init; }
    public Guid? MaybeGid { get; init; }
    public int? MaybeNum { get; init; }

    public NestedModel Inner { get; init; } = new();
  }

  public class NestedModel {
    public string City { get; init; } = string.Empty;
    public int Floor { get; init; }
    public DeeperModel Deeper { get; init; } = new();
  }

  public class DeeperModel {
    public Guid Marker { get; init; }
  }

  private sealed class MatrixDbContext(DbContextOptions<MatrixDbContext> options) : DbContext(options) {
    protected override void OnModelCreating(ModelBuilder modelBuilder) {
      modelBuilder.Entity<PerspectiveRow<MatrixModel>>(entity => {
        entity.ToTable("wh_per_matrix");
        entity.HasKey(e => e.Id);
        entity.Property(e => e.Id).HasColumnName("id");

        entity.ComplexProperty(e => e.Data, d => {
          d.ToJson("data");
          d.ComplexProperty(p => p.Inner, i => i.ComplexProperty(p => p.Deeper));
        });
        entity.ComplexProperty(e => e.Metadata, m => m.ToJson("metadata"));
        entity.ComplexProperty(e => e.Scope, s => {
          s.ToJson("scope");
          s.ComplexCollection(p => p.Extensions, ex => ex.HasJsonPropertyName("ex"));
        });

        entity.Property(e => e.CreatedAt).HasColumnName("created_at").IsRequired();
        entity.Property(e => e.UpdatedAt).HasColumnName("updated_at").IsRequired();
        entity.Property(e => e.Version).HasColumnName("version").IsRequired();

        entity.Property<Guid>("phys_guid").HasColumnName("phys_guid");
        entity.Property<int>("phys_int").HasColumnName("phys_int");
        entity.Property<string?>("phys_string").HasColumnName("phys_string");
      });

      modelBuilder.UseWhizbangJsonbContainment();
    }
  }

  // Built once. A fresh DbContextOptions per case would ask Entity Framework for a new internal
  // service provider each time, and past twenty of those it raises ManyServiceProvidersCreatedWarning
  // as an error. Nothing here mutates, so one options instance serves the whole matrix.
  private static readonly DbContextOptions<MatrixDbContext> _matrixOptions =
    new DbContextOptionsBuilder<MatrixDbContext>()
      .UseNpgsql(UNUSED_CONNECTION)
      .UseWhizbangPhysicalFields()
      .ConfigureWarnings(w => w.Ignore(CoreEventId.ManyServiceProvidersCreatedWarning))
      .Options;

  /// <summary>
  /// The same model, with the reshape registered instead of the marker translations.
  /// </summary>
  /// <remarks>
  /// A separate options instance rather than a flag on the first one, and that matters for more than
  /// tidiness: Entity Framework caches a compiled query per service provider, so one shape compiled
  /// under one mechanism would otherwise be returned unchanged when the other mechanism was selected,
  /// and every second case would silently assert the first mechanism's output.
  /// </remarks>
  private static readonly DbContextOptions<MatrixDbContext> _reshapeOptions =
    new DbContextOptionsBuilder<MatrixDbContext>()
      .UseNpgsql(UNUSED_CONNECTION)
      .UseWhizbangPhysicalFields()
      .UseWhizbangContainmentReshape()
      .ConfigureWarnings(w => w.Ignore(CoreEventId.ManyServiceProvidersCreatedWarning))
      .Options;

  private static MatrixDbContext _newContext(ContainmentMode mode) {
    PhysicalFieldRegistry.Register<MatrixModel>("PhysGuid", "phys_guid");
    PhysicalFieldRegistry.Register<MatrixModel>("PhysInt", "phys_int");
    PhysicalFieldRegistry.Register<MatrixModel>("PhysString", "phys_string");

    JsonbContainmentSwitch.SetMode(mode);

    return new MatrixDbContext(
      mode == ContainmentMode.TranslatedTree ? _reshapeOptions : _matrixOptions);
  }

  private static MatrixDbContext _newContext() {
    PhysicalFieldRegistry.Register<MatrixModel>("PhysGuid", "phys_guid");
    PhysicalFieldRegistry.Register<MatrixModel>("PhysInt", "phys_int");
    PhysicalFieldRegistry.Register<MatrixModel>("PhysString", "phys_string");

    return new MatrixDbContext(_matrixOptions);
  }

  private delegate IQueryable<PerspectiveRow<MatrixModel>> Shape(IQueryable<PerspectiveRow<MatrixModel>> rows);

  private static readonly Dictionary<string, (Shape Shape, Destination Expected)> _matrix = _buildMatrix();

  // ========================================
  // The matrix
  // ========================================

  [SuppressMessage("Globalization", "CA1304:Specify CultureInfo",
    Justification = "The culture-dependent spelling is the subject: a developer writes ToLower() " +
      "without a culture, and what this pins is where that filter lands.")]
  [SuppressMessage("Globalization", "CA1311:Specify a culture or use an invariant version",
    Justification = "As CA1304: the spelling under test is the one a developer actually writes.")]
  [SuppressMessage("Performance", "CA1862:Use the StringComparison method overloads",
    Justification = "Rewriting these to Equals(StringComparison) would remove the very shapes the " +
      "matrix exists to cover, since case folding through a function is what keeps them unindexed.")]
  [SuppressMessage("Readability", "RCS1155:Use StringComparison when comparing strings",
    Justification = "As CA1862: the comparison without a StringComparison is the case under test.")]
  private static Dictionary<string, (Shape, Destination)> _buildMatrix() {
    var cases = new Dictionary<string, (Shape, Destination)>(StringComparer.Ordinal);

    // Base predicates, written out because an expression tree has to be literal to be translated.
    // Everything else is crossed over them, so adding one type here adds a row to every axis.
    var bases = new List<(string Key, Shape Shape, Destination Expected, bool Orders)>();
    void Base(string key, Shape shape, Destination expected) => bases.Add((key, shape, expected, false));

    // A base case that establishes its own ordering cannot be crossed with a wrapper that reorders
    // or drops the sort: a second OrderBy replaces the first and Distinct discards it, so the very
    // expression under test disappears from the SQL.
    void OrderingBase(string key, Shape shape, Destination expected) => bases.Add((key, shape, expected, true));

    // --- Equality on a JSON-only scalar whose two text forms agree, member-first and value-first,
    // --- as a constant and as a captured parameter.
    var s = "v";
    var g = _probeGuid;
    var b = true;
    short sh = 1;
    var i = 1;
    var l = 1L;
    var m = 1.5m;

    Base("eq/string/member-first/const", rows => rows.Where(x => x.Data.Str == "v"), Destination.Containment);
    Base("eq/string/value-first/const", rows => rows.Where(x => "v" == x.Data.Str), Destination.Containment);
    Base("eq/string/member-first/param", rows => rows.Where(x => x.Data.Str == s), Destination.Containment);
    Base("eq/string/value-first/param", rows => rows.Where(x => s == x.Data.Str), Destination.Containment);

    Base("eq/guid/member-first/const", rows => rows.Where(x => x.Data.Gid == _probeGuid), Destination.Containment);
    Base("eq/guid/value-first/const", rows => rows.Where(x => _probeGuid == x.Data.Gid), Destination.Containment);
    Base("eq/guid/member-first/param", rows => rows.Where(x => x.Data.Gid == g), Destination.Containment);
    Base("eq/guid/value-first/param", rows => rows.Where(x => g == x.Data.Gid), Destination.Containment);

    Base("eq/bool/member-first/const", rows => rows.Where(x => x.Data.Flag == true), Destination.Containment);
    Base("eq/bool/value-first/const", rows => rows.Where(x => true == x.Data.Flag), Destination.Containment);
    Base("eq/bool/member-first/param", rows => rows.Where(x => x.Data.Flag == b), Destination.Containment);
    Base("eq/bool/value-first/param", rows => rows.Where(x => b == x.Data.Flag), Destination.Containment);

    Base("eq/short/member-first/const", rows => rows.Where(x => x.Data.Small == (short)1), Destination.Containment);
    Base("eq/short/value-first/const", rows => rows.Where(x => (short)1 == x.Data.Small), Destination.Containment);
    Base("eq/short/member-first/param", rows => rows.Where(x => x.Data.Small == sh), Destination.Containment);
    Base("eq/short/value-first/param", rows => rows.Where(x => sh == x.Data.Small), Destination.Containment);

    Base("eq/int/member-first/const", rows => rows.Where(x => x.Data.Num == 1), Destination.Containment);
    Base("eq/int/value-first/const", rows => rows.Where(x => 1 == x.Data.Num), Destination.Containment);
    Base("eq/int/member-first/param", rows => rows.Where(x => x.Data.Num == i), Destination.Containment);
    Base("eq/int/value-first/param", rows => rows.Where(x => i == x.Data.Num), Destination.Containment);

    Base("eq/long/member-first/const", rows => rows.Where(x => x.Data.Big == 1L), Destination.Containment);
    Base("eq/long/value-first/const", rows => rows.Where(x => 1L == x.Data.Big), Destination.Containment);
    Base("eq/long/member-first/param", rows => rows.Where(x => x.Data.Big == l), Destination.Containment);
    Base("eq/long/value-first/param", rows => rows.Where(x => l == x.Data.Big), Destination.Containment);

    Base("eq/decimal/member-first/const", rows => rows.Where(x => x.Data.Money == 1.5m), Destination.Containment);
    Base("eq/decimal/value-first/const", rows => rows.Where(x => 1.5m == x.Data.Money), Destination.Containment);
    Base("eq/decimal/member-first/param", rows => rows.Where(x => x.Data.Money == m), Destination.Containment);
    Base("eq/decimal/value-first/param", rows => rows.Where(x => m == x.Data.Money), Destination.Containment);

    // --- Types whose serialized form and PostgreSQL's are not guaranteed to agree.
    var dbl = 1.5d;
    var flt = 1.5f;
    var when = _probeDate;
    var offset = _probeOffset;
    var state = Status.Live;

    Base("eligible-now/double/const", rows => rows.Where(x => x.Data.Dbl == 1.5d), Destination.Containment);
    Base("eligible-now/double/param", rows => rows.Where(x => x.Data.Dbl == dbl), Destination.Containment);
    Base("eligible-now/float/const", rows => rows.Where(x => x.Data.Flt == 1.5f), Destination.Containment);
    Base("eligible-now/float/param", rows => rows.Where(x => x.Data.Flt == flt), Destination.Containment);
    // A date reaches the index through a rendering of the instant, not by being passed through; the
    // format is locked on both sides by PerspectiveDateFormatLockTests.
    Base("eligible-now/datetime/const",
      rows => rows.Where(x => x.Data.When == new DateTime(2026, 3, 4, 5, 6, 7, DateTimeKind.Utc)),
      Destination.Containment);
    Base("eligible-now/datetime/param", rows => rows.Where(x => x.Data.When == when), Destination.Containment);
    Base("eligible-now/datetime/sentinel",
      rows => rows.Where(x => x.Data.When == DateTime.MaxValue), Destination.Containment);

    // An offset is not a formatting problem but an information one: the stored text keeps the offset
    // the row was written with, and equality compares instants, so one instant cannot produce every
    // text that equals it.
    Base("ineligible/datetimeoffset/param", rows => rows.Where(x => x.Data.WhenOffset == offset), Destination.Extraction);
    Base("eligible-now/enum/const", rows => rows.Where(x => x.Data.State == Status.Live), Destination.Containment);
    Base("eligible-now/enum/param", rows => rows.Where(x => x.Data.State == state), Destination.Containment);

    // --- Every operator other than equality, on the types that only had an equality case.
    //
    // Being eligible for containment is a property of the type, but reaching the index is a property
    // of the operator, and only equality qualifies. A type admitted to the eligible set must not drag
    // its other operators in with it: a range on an indexable type is still a range. These are the
    // shapes a repository writes most after equality, so each is pinned rather than assumed.
    var upper = _probeDate.AddDays(1);

    Base("op/datetime/greater", rows => rows.Where(x => x.Data.When > when), Destination.Extraction);
    Base("op/datetime/greater-or-equal", rows => rows.Where(x => x.Data.When >= when), Destination.Extraction);
    Base("op/datetime/less", rows => rows.Where(x => x.Data.When < when), Destination.Extraction);
    Base("op/datetime/less-or-equal", rows => rows.Where(x => x.Data.When <= when), Destination.Extraction);
    Base("op/datetime/not-equal", rows => rows.Where(x => x.Data.When != when), Destination.Extraction);

    // The dominant date shape in real repositories, and the one most at risk of being half rewritten.
    Base("op/datetime/between",
      rows => rows.Where(x => x.Data.When >= when && x.Data.When <= upper), Destination.Extraction);

    // A component of a date is not the stored key, so the path walk has to stand down rather than
    // treat "Year" as a member of the document.
    Base("op/datetime/year", rows => rows.Where(x => x.Data.When.Year == 2026), Destination.Extraction);
    Base("op/datetime/date-part", rows => rows.Where(x => x.Data.When.Date == when.Date), Destination.Extraction);
    Base("op/datetime/shifted", rows => rows.Where(x => x.Data.When.AddDays(1) == upper), Destination.Extraction);

    // An enumeration is ordered in C#, so these compile and must not reach the index.
    Base("op/enum/greater", rows => rows.Where(x => x.Data.State > Status.Draft), Destination.Extraction);
    Base("op/enum/greater-or-equal", rows => rows.Where(x => x.Data.State >= Status.Live), Destination.Extraction);
    Base("op/enum/less", rows => rows.Where(x => x.Data.State < Status.Retired), Destination.Extraction);
    Base("op/enum/not-equal", rows => rows.Where(x => x.Data.State != state), Destination.Extraction);

    // A combinable enumeration holds a set, so neither spelling of a flag test is the equality that
    // containment reproduces. Equality against a combination still is, and stays above.
    Base("op/enum/has-flag", rows => rows.Where(x => x.Data.Perms.HasFlag(Access.Read)), Destination.Extraction);
    Base("op/enum/bitwise",
      rows => rows.Where(x => (x.Data.Perms & Access.Read) == Access.Read), Destination.Extraction);
    Base("eq/enum/flags-combination",
      rows => rows.Where(x => x.Data.Perms == (Access.Read | Access.Write)), Destination.Containment);

    Base("op/double/greater", rows => rows.Where(x => x.Data.Dbl > dbl), Destination.Extraction);
    Base("op/double/less-or-equal", rows => rows.Where(x => x.Data.Dbl <= dbl), Destination.Extraction);
    Base("op/double/not-equal", rows => rows.Where(x => x.Data.Dbl != dbl), Destination.Extraction);
    Base("op/double/between",
      rows => rows.Where(x => x.Data.Dbl >= dbl && x.Data.Dbl <= dbl + 1), Destination.Extraction);
    Base("op/float/greater", rows => rows.Where(x => x.Data.Flt > flt), Destination.Extraction);
    Base("op/float/not-equal", rows => rows.Where(x => x.Data.Flt != flt), Destination.Extraction);

    Base("op/guid/greater", rows => rows.Where(x => x.Data.Gid.CompareTo(g) > 0), Destination.Extraction);

    // Two-sided ranges on the numeric types, which is what a paging or windowing filter is.
    Base("op/int/between", rows => rows.Where(x => x.Data.Num >= 1 && x.Data.Num <= 10), Destination.Extraction);
    Base("op/decimal/between",
      rows => rows.Where(x => x.Data.Money >= 1.5m && x.Data.Money <= 2.5m), Destination.Extraction);

    // Arithmetic moves the comparison off the member, so there is no member left to index.
    Base("op/int/arithmetic", rows => rows.Where(x => (x.Data.Num * 2) == 10), Destination.Extraction);
    Base("op/int/member-vs-member", rows => rows.Where(x => x.Data.Num == x.Data.Small), Destination.Extraction);

    // The string functions that change the value before comparing it.
    Base("op/string/to-lower", rows => rows.Where(x => x.Data.Str.ToLower() == "v"), Destination.Extraction);
    Base("op/string/to-upper", rows => rows.Where(x => x.Data.Str.ToUpper() == "V"), Destination.Extraction);
    Base("op/string/trimmed", rows => rows.Where(x => x.Data.Str.Trim() == "v"), Destination.Extraction);
    Base("op/string/is-null-or-empty",
      rows => rows.Where(x => string.IsNullOrEmpty(x.Data.MaybeStr)), Destination.Extraction);
    // Entity Framework refuses this overload outright. It is worth pinning because the ordinal
    // spelling of the very same call does reach the index through this framework's rewrite, so the
    // pair marks exactly where the capability starts and stops.
    Base("op/string/case-insensitive",
      rows => rows.Where(x => x.Data.Str.Equals("v", StringComparison.OrdinalIgnoreCase)),
      Destination.Untranslatable);

    // --- Nullable members: containment for a value, extraction for a null.
    string? maybeStr = "v";
    Guid? maybeGid = _probeGuid;
    int? maybeNum = 1;

    Base("nullable/string/value/const", rows => rows.Where(x => x.Data.MaybeStr == "v"), Destination.Containment);
    Base("nullable/string/value/param", rows => rows.Where(x => x.Data.MaybeStr == maybeStr), Destination.Containment);
    Base("nullable/guid/value/const", rows => rows.Where(x => x.Data.MaybeGid == _probeGuid), Destination.Containment);
    Base("nullable/guid/value/param", rows => rows.Where(x => x.Data.MaybeGid == maybeGid), Destination.Containment);
    Base("nullable/int/value/const", rows => rows.Where(x => x.Data.MaybeNum == 1), Destination.Containment);
    Base("nullable/int/value/param", rows => rows.Where(x => x.Data.MaybeNum == maybeNum), Destination.Containment);
    Base("nullable/string/null", rows => rows.Where(x => x.Data.MaybeStr == null), Destination.Extraction);
    Base("nullable/guid/null", rows => rows.Where(x => x.Data.MaybeGid == null), Destination.Extraction);
    Base("nullable/int/null", rows => rows.Where(x => x.Data.MaybeNum == null), Destination.Extraction);
    Base("nullable/string/not-null", rows => rows.Where(x => x.Data.MaybeStr != null), Destination.Extraction);

    // --- Promoted fields keep reading their column.
    Base("physical/guid/equal", rows => rows.Where(x => x.Data.PhysGuid == g), Destination.PhysicalColumn);
    Base("physical/int/equal", rows => rows.Where(x => x.Data.PhysInt == i), Destination.PhysicalColumn);
    Base("physical/int/range", rows => rows.Where(x => x.Data.PhysInt > 1), Destination.PhysicalColumn);
    Base("physical/int/not-equal", rows => rows.Where(x => x.Data.PhysInt != 1), Destination.PhysicalColumn);
    Base("physical/string/equal", rows => rows.Where(x => x.Data.PhysString == s), Destination.PhysicalColumn);
    Base("physical/string/like", rows => rows.Where(x => x.Data.PhysString.Contains("val")), Destination.PhysicalColumn);
    OrderingBase("physical/int/ordered", rows => rows.OrderBy(x => x.Data.PhysInt), Destination.PhysicalColumn);
    Base("physical/negated", rows => rows.Where(x => !(x.Data.PhysInt == 1)), Destination.PhysicalColumn);

    // --- Operators containment cannot express.
    Base("op/short/not-equal", rows => rows.Where(x => x.Data.Small != (short)1), Destination.Extraction);
    Base("op/short/greater", rows => rows.Where(x => x.Data.Small > (short)1), Destination.Extraction);
    Base("op/short/greater-or-equal", rows => rows.Where(x => x.Data.Small >= (short)1), Destination.Extraction);
    Base("op/short/less", rows => rows.Where(x => x.Data.Small < (short)1), Destination.Extraction);
    Base("op/short/less-or-equal", rows => rows.Where(x => x.Data.Small <= (short)1), Destination.Extraction);
    Base("op/int/not-equal", rows => rows.Where(x => x.Data.Num != 1), Destination.Extraction);
    Base("op/int/greater", rows => rows.Where(x => x.Data.Num > 1), Destination.Extraction);
    Base("op/int/greater-or-equal", rows => rows.Where(x => x.Data.Num >= 1), Destination.Extraction);
    Base("op/int/less", rows => rows.Where(x => x.Data.Num < 1), Destination.Extraction);
    Base("op/int/less-or-equal", rows => rows.Where(x => x.Data.Num <= 1), Destination.Extraction);
    Base("op/long/not-equal", rows => rows.Where(x => x.Data.Big != 1L), Destination.Extraction);
    Base("op/long/greater", rows => rows.Where(x => x.Data.Big > 1L), Destination.Extraction);
    Base("op/long/less", rows => rows.Where(x => x.Data.Big < 1L), Destination.Extraction);
    Base("op/decimal/not-equal", rows => rows.Where(x => x.Data.Money != 1.5m), Destination.Extraction);
    Base("op/decimal/greater", rows => rows.Where(x => x.Data.Money > 1.5m), Destination.Extraction);
    Base("op/decimal/greater-or-equal", rows => rows.Where(x => x.Data.Money >= 1.5m), Destination.Extraction);
    Base("op/decimal/less", rows => rows.Where(x => x.Data.Money < 1.5m), Destination.Extraction);
    Base("op/decimal/less-or-equal", rows => rows.Where(x => x.Data.Money <= 1.5m), Destination.Extraction);
    Base("op/string/not-equal", rows => rows.Where(x => x.Data.Str != "v"), Destination.Extraction);
    Base("op/string/contains", rows => rows.Where(x => x.Data.Str.Contains("val")), Destination.Extraction);
    Base("op/string/starts-with", rows => rows.Where(x => x.Data.Str.StartsWith("val")), Destination.Extraction);
    Base("op/string/ends-with", rows => rows.Where(x => x.Data.Str.EndsWith("val")), Destination.Extraction);
    Base("op/string/length", rows => rows.Where(x => x.Data.Str.Length > 3), Destination.Extraction);
    Base("op/guid/not-equal", rows => rows.Where(x => x.Data.Gid != _probeGuid), Destination.Extraction);
    Base("op/bool/negated-member", rows => rows.Where(x => !x.Data.Flag), Destination.Extraction);
    OrderingBase("op/string/ordered", rows => rows.OrderBy(x => x.Data.Str), Destination.Extraction);
    OrderingBase("op/int/ordered-descending", rows => rows.OrderByDescending(x => x.Data.Num), Destination.Extraction);

    // --- Nested members.
    Base("nested/string/const", rows => rows.Where(x => x.Data.Inner.City == "v"), Destination.Containment);
    Base("nested/string/param", rows => rows.Where(x => x.Data.Inner.City == s), Destination.Containment);
    Base("nested/int/const", rows => rows.Where(x => x.Data.Inner.Floor == 3), Destination.Containment);
    Base("nested/int/param", rows => rows.Where(x => x.Data.Inner.Floor == i), Destination.Containment);
    Base("nested/two-levels/const", rows => rows.Where(x => x.Data.Inner.Deeper.Marker == _probeGuid), Destination.Containment);
    Base("nested/two-levels/param", rows => rows.Where(x => x.Data.Inner.Deeper.Marker == g), Destination.Containment);
    Base("nested/range", rows => rows.Where(x => x.Data.Inner.Floor > 3), Destination.Extraction);
    Base("nested/not-equal", rows => rows.Where(x => x.Data.Inner.City != "v"), Destination.Extraction);
    OrderingBase("nested/ordered", rows => rows.OrderBy(x => x.Data.Inner.City), Destination.Extraction);

    // --- Negation, which is where containment and equality stop agreeing.
    Base("negated/string", rows => rows.Where(x => !(x.Data.Str == "v")), Destination.Extraction);
    Base("negated/guid", rows => rows.Where(x => !(x.Data.Gid == _probeGuid)), Destination.Extraction);
    Base("negated/int", rows => rows.Where(x => !(x.Data.Num == 1)), Destination.Extraction);
    Base("negated/nested", rows => rows.Where(x => !(x.Data.Inner.City == "v")), Destination.Extraction);
    Base("negated/around-and", rows => rows.Where(x => !(x.Data.Str == "v" && x.Data.Num == 1)), Destination.Extraction);
    Base("negated/around-or", rows => rows.Where(x => !(x.Data.Str == "v" || x.Data.Num == 1)), Destination.Extraction);
    Base("negated/double", rows => rows.Where(x => !!(x.Data.Str == "v")), Destination.Extraction);
    Base("negated/beside-positive", rows => rows.Where(x => !(x.Data.Str == "v") || x.Data.Num == 1), Destination.Containment);

    // --- Composition within a single predicate.
    Base("compose/and-two", rows => rows.Where(x => x.Data.Str == "v" && x.Data.Num == 1), Destination.Containment);
    Base("compose/or-two", rows => rows.Where(x => x.Data.Str == "v" || x.Data.Num == 1), Destination.Containment);
    Base("compose/and-three", rows => rows.Where(x => x.Data.Str == "v" && x.Data.Num == 1 && x.Data.Gid == _probeGuid), Destination.Containment);
    Base("compose/and-physical", rows => rows.Where(x => x.Data.Str == "v" && x.Data.PhysInt == 1), Destination.Containment);
    Base("compose/and-row-column", rows => rows.Where(x => x.Data.Str == "v" && x.Version > 1), Destination.Containment);
    Base("compose/and-range", rows => rows.Where(x => x.Data.Str == "v" && x.Data.Num > 1), Destination.Containment);
    Base("compose/and-null-check", rows => rows.Where(x => x.Data.Str == "v" && x.Data.MaybeStr == null), Destination.Containment);
    Base("compose/chained-where", rows => rows.Where(x => x.Data.Str == "v").Where(x => x.Data.Num == 1), Destination.Containment);
    Base("compose/mixed-nested", rows => rows.Where(x => x.Data.Inner.City == "v" && x.Data.Str == "v"), Destination.Containment);

    // --- The row's own columns.
    Base("row/id", rows => rows.Where(x => x.Id == g), Destination.RowColumn);
    Base("row/version", rows => rows.Where(x => x.Version == 1), Destination.RowColumn);
    Base("row/updated-at", rows => rows.Where(x => x.UpdatedAt > when), Destination.RowColumn);
    OrderingBase("row/created-at-ordered", rows => rows.OrderBy(x => x.CreatedAt), Destination.RowColumn);
    Base("row/id-and-version", rows => rows.Where(x => x.Id == g && x.Version > 0), Destination.RowColumn);

    // --- Query syntax is the same tree in different clothes.
    Base("query-syntax/where-eligible", rows => from x in rows where x.Data.Str == "v" select x, Destination.Containment);
    Base("query-syntax/where-range", rows => from x in rows where x.Data.Num > 1 select x, Destination.Extraction);
    Base("query-syntax/where-negated", rows => from x in rows where !(x.Data.Str == "v") select x, Destination.Extraction);
    Base("query-syntax/orderby-eligible", rows => from x in rows where x.Data.Gid == _probeGuid orderby x.Version select x, Destination.Containment);
    Base("query-syntax/nested", rows => from x in rows where x.Data.Inner.City == "v" select x, Destination.Containment);

    // Cross every base predicate with the query shapes a repository wraps it in. None of these
    // wrappers touches a JSON member, so the destination of the predicate cannot change.
    var wrappers = new (string Name, Func<Shape, Shape> Wrap)[] {
      ("bare", inner => inner),
      ("ordered-by-key", inner => rows => inner(rows).OrderBy(x => x.Id)),
      ("ordered-then-by", inner => rows => inner(rows).OrderBy(x => x.Id).ThenByDescending(x => x.Version)),
      ("paged", inner => rows => inner(rows).Skip(10).Take(5)),
      ("distinct", inner => rows => inner(rows).Distinct()),
      ("refiltered-on-row-column", inner => rows => inner(rows).Where(x => x.Version > 0)),
      ("ordered-and-paged", inner => rows => inner(rows).OrderBy(x => x.CreatedAt).Skip(1).Take(2)),
    };

    // Wrappers that leave an existing ORDER BY intact.
    var orderPreserving = new[] { "bare", "paged", "refiltered-on-row-column" };

    foreach (var (key, shape, expected, orders) in bases) {
      foreach (var (wrapperName, wrap) in wrappers) {
        if (orders && !orderPreserving.Contains(wrapperName, StringComparer.Ordinal)) {
          continue;
        }

        cases[$"{key}::{wrapperName}"] = (wrap(shape), expected);
      }
    }

    return cases;
  }

  private static readonly Guid _probeGuid = new("6f9619ff-8b86-d011-b42d-00cf4fc964ff");
  private static readonly DateTime _probeDate = new(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc);
  private static readonly DateTimeOffset _probeOffset = new(2026, 1, 1, 0, 0, 0, TimeSpan.Zero);

  // ========================================
  // The test
  // ========================================

  /// <summary>
  /// Every case in the matrix, once per mechanism that can compile it.
  /// </summary>
  /// <returns>One tuple per case and mechanism.</returns>
  /// <remarks>
  /// <para>
  /// Running the whole matrix against both mechanisms is the main thing keeping them from diverging.
  /// The cases assert where a filter landed by reading compiled SQL, which makes them indifferent to
  /// how it got there, so any disagreement between the two becomes a named failing case rather than
  /// something a consumer finds.
  /// </para>
  /// <para>
  /// The destinations are shared except where they are deliberately not, which
  /// <see cref="_destinationUnder"/> decides.
  /// </para>
  /// </remarks>
  public static IEnumerable<(string CaseKey, ContainmentMode Mode, Destination Expected)> Cases() =>
    from entry in _matrix.OrderBy(kv => kv.Key, StringComparer.Ordinal)
    from mode in new[] { ContainmentMode.ExpressionTree, ContainmentMode.TranslatedTree }
    select (entry.Key, mode, _destinationUnder(entry.Key, entry.Value.Expected, mode));

  /// <summary>
  /// Where a case is expected to land under one mechanism, which is the same for both unless a
  /// difference is deliberate.
  /// </summary>
  /// <remarks>
  /// <para>
  /// Three deliberate differences, and the direction matters: one is the reshape doing less, and two
  /// are the reshape doing better. None of them is a disagreement about which rows come back, which
  /// is the thing the two mechanisms are not allowed to differ on.
  /// </para>
  /// <para>
  /// <strong>A date does less.</strong> The tree rewrite renders the instant in SQL to match what the
  /// serializer wrote; the reshape does not, because writing that rendering there would mean building
  /// exactly what the canonical stored format is going to delete. So a date keeps the extraction
  /// form under the reshape: correct rows, no index. THESE CASES SHOULD BE DELETED, not inverted,
  /// once dates are stored as a number, at which point the two agree again.
  /// </para>
  /// <para>
  /// <strong>A doubly negated comparison does better.</strong> The tree rewrite stands down at any
  /// negation depth, including an even one where the negations cancel. By the time the reshape runs,
  /// Entity Framework has already collapsed them, so it sees a plain equality and indexes it.
  /// Equivalent under three-valued logic too, since a null that is negated twice is still null and
  /// still excludes the row.
  /// </para>
  /// <para>
  /// <strong>An emptiness test does better.</strong> On the tree there is no equality to see, because
  /// the shape is still a method call. After translation it is a null test or an equality against the
  /// empty string, and the second half of that indexes. The rows are the same: an absent key and an
  /// explicit null are both caught by the null test either way.
  /// </para>
  /// </remarks>
  private static Destination _destinationUnder(string caseKey, Destination shared, ContainmentMode mode) {
    if (mode != ContainmentMode.TranslatedTree) {
      return shared;
    }

    if (caseKey.StartsWith("eligible-now/datetime/", StringComparison.Ordinal)) {
      return Destination.Extraction;
    }

    return caseKey.StartsWith("negated/double", StringComparison.Ordinal)
        || caseKey.StartsWith("op/string/is-null-or-empty", StringComparison.Ordinal)
      ? Destination.Containment
      : shared;
  }

  /// <summary>
  /// Compiles the case and asserts the filter landed where it was meant to.
  /// </summary>
  /// <param name="caseKey">The matrix key, which also names the test.</param>
  /// <param name="mode">The mechanism compiling it.</param>
  /// <param name="expected">Where the filter should have gone.</param>
  [Test]
  [MethodDataSource(nameof(Cases))]
  public async Task CompiledSql_SendsTheFilterWhereExpectedAsync(
    string caseKey, ContainmentMode mode, Destination expected) {
    var (shape, _) = _matrix[caseKey];

    using var db = _newContext(mode);

    if (expected == Destination.Untranslatable) {
      await Assert.That(() => shape(db.Set<PerspectiveRow<MatrixModel>>()).ToQueryString())
        .Throws<InvalidOperationException>()
        .Because("the shape has to fail at query compilation rather than silently answer differently");
      return;
    }

    var sql = shape(db.Set<PerspectiveRow<MatrixModel>>()).ToQueryString();

    var containment = sql.Contains("@>", StringComparison.Ordinal);
    var extraction = sql.Contains("data ->>", StringComparison.Ordinal)
                     || sql.Contains("data ->", StringComparison.Ordinal)
                     || sql.Contains("data #>>", StringComparison.Ordinal)
                     || sql.Contains("data #>", StringComparison.Ordinal);

    switch (expected) {
      case Destination.Containment:
        await Assert.That(containment).IsTrue();
        await Assert.That(sql).Contains("jsonb_build_object", StringComparison.Ordinal);
        break;

      case Destination.Extraction:
        await Assert.That(extraction).IsTrue();
        await Assert.That(containment).IsFalse();
        break;

      case Destination.PhysicalColumn:
        await Assert.That(containment).IsFalse();
        await Assert.That(extraction).IsFalse();
        await Assert.That(sql.Contains("phys_", StringComparison.Ordinal)).IsTrue();
        break;

      case Destination.RowColumn:
        await Assert.That(containment).IsFalse();
        await Assert.That(extraction).IsFalse();
        break;

      default:
        throw new InvalidOperationException($"Unhandled destination {expected}.");
    }
  }

  /// <summary>The matrix is worth having only if it is broad, so its size is asserted too.</summary>
  [Test]
  public async Task Matrix_CoversEveryAxisAsync() {
    await Assert.That(_matrix.Count).IsGreaterThanOrEqualTo(700);

    foreach (var destination in Enum.GetValues<Destination>()) {
      var covered = _matrix.Values.Count(v => v.Expected == destination);
      await Assert.That(covered).IsGreaterThan(0);
    }
  }

  /// <summary>
  /// A model that has not registered the translations keeps the extraction form, so the rewrite can
  /// never be a surprise for a consumer that did not ask for it.
  /// </summary>
  [Test]
  public async Task WithoutRegistration_TheRewriteStandsDownAsync() {
    using var db = new UnregisteredDbContext(_unregisteredOptions);

    var sql = db.Set<PerspectiveRow<MatrixModel>>().Where(x => x.Data.Str == "v").ToQueryString();

    await Assert.That(sql).Contains("data ->>", StringComparison.Ordinal);
    await Assert.That(sql).DoesNotContain("@>", StringComparison.Ordinal);
  }

  private static readonly DbContextOptions<UnregisteredDbContext> _unregisteredOptions =
    new DbContextOptionsBuilder<UnregisteredDbContext>()
      .UseNpgsql(UNUSED_CONNECTION)
      .UseWhizbangPhysicalFields()
      .ConfigureWarnings(w => w.Ignore(CoreEventId.ManyServiceProvidersCreatedWarning))
      .Options;

  private sealed class UnregisteredDbContext(DbContextOptions<UnregisteredDbContext> options) : DbContext(options) {
    protected override void OnModelCreating(ModelBuilder modelBuilder) =>
      modelBuilder.Entity<PerspectiveRow<MatrixModel>>(entity => {
        entity.ToTable("wh_per_matrix");
        entity.HasKey(e => e.Id);
        entity.Property(e => e.Id).HasColumnName("id");
        entity.ComplexProperty(e => e.Data, d => {
          d.ToJson("data");
          d.ComplexProperty(p => p.Inner, i => i.ComplexProperty(p => p.Deeper));
        });
        entity.ComplexProperty(e => e.Metadata, m => m.ToJson("metadata"));
        entity.ComplexProperty(e => e.Scope, s => {
          s.ToJson("scope");
          s.ComplexCollection(p => p.Extensions, ex => ex.HasJsonPropertyName("ex"));
        });
        entity.Property(e => e.CreatedAt).HasColumnName("created_at").IsRequired();
        entity.Property(e => e.UpdatedAt).HasColumnName("updated_at").IsRequired();
        entity.Property(e => e.Version).HasColumnName("version").IsRequired();
        entity.Property<Guid>("phys_guid").HasColumnName("phys_guid");
        entity.Property<int>("phys_int").HasColumnName("phys_int");
        entity.Property<string?>("phys_string").HasColumnName("phys_string");
      });
  }

  /// <summary>Records the SQL for every case, so a reviewer can read what the matrix actually asserts.</summary>
  [Test]
  public async Task Matrix_IsRecordedForReviewAsync() {
    var target = Environment.GetEnvironmentVariable("WHIZ_MATRIX_DUMP");
    if (string.IsNullOrWhiteSpace(target)) {
      return;
    }

    var mode = string.Equals(Environment.GetEnvironmentVariable("WHIZ_MATRIX_MODE"), "reshape",
      StringComparison.Ordinal) ? ContainmentMode.TranslatedTree : ContainmentMode.ExpressionTree;
    using var db = _newContext(mode);
    var sink = new System.Text.StringBuilder();
    foreach (var (key, (shape, expected)) in _matrix.OrderBy(kv => kv.Key, StringComparer.Ordinal)) {
      sink.AppendLine(CultureInfo.InvariantCulture, $"##### {key}  [{expected}]");
      // A case whose destination is Untranslatable throws here by design, and the dump is a reading
      // aid rather than an assertion, so it records the refusal and carries on.
      try {
        sink.AppendLine(shape(db.Set<PerspectiveRow<MatrixModel>>()).ToQueryString());
      } catch (InvalidOperationException refused) {
        sink.AppendLine(CultureInfo.InvariantCulture, $"REFUSED: {refused.Message.Split('\n')[0]}");
      }
      sink.AppendLine();
    }

    await File.WriteAllTextAsync(target, sink.ToString());
  }
}
