using System.Globalization;
using Microsoft.EntityFrameworkCore;
using TUnit.Assertions;
using TUnit.Assertions.Extensions;
using TUnit.Core;
using Whizbang.Core;
using Whizbang.Core.Lenses;
using Whizbang.Core.Perspectives;
using Whizbang.Data.EFCore.Postgres.QueryTranslation;

namespace Whizbang.Data.EFCore.Postgres.Tests.QueryTranslation;

/// <summary>
/// The compiled-SQL matrix for perspective queries: every field type crossed with every operator,
/// value source, composition and query shape that a repository can reasonably write.
/// </summary>
/// <remarks>
/// <para>
/// A perspective filter has three possible destinations and they are indistinguishable in the LINQ.
/// It can read a promoted column, it can be answered from the GIN index as a containment test, or it
/// falls back to extracting the value out of the JSON document for every row. Which one happens
/// decides whether a query is a lookup or a table scan, so each combination is pinned here rather
/// than left to be discovered under load.
/// </para>
/// <para>
/// Cases are generated by crossing the dimensions instead of being written out, so adding a type or
/// an operator adds a row to every relevant axis at once. Nothing opens a connection, so the whole
/// matrix runs in about a second.
/// </para>
/// </remarks>
/// <docs>fundamentals/perspectives/physical-fields#index-advisories</docs>
/// <docs>operations/diagnostics/whiz302</docs>
[NotInParallel("EFCorePostgresTests")]
[Category("Shard1")]
public class JsonbContainmentSqlMatrixTests {
  private const string UNUSED_CONNECTION = "Host=localhost;Database=matrix;Username=u;Password=p";

  /// <summary>Where a filter ended up.</summary>
  public enum Destination {
    /// <summary>Answered from the GIN index as a containment test.</summary>
    Containment,

    /// <summary>Extracted out of the JSON document per row.</summary>
    Extraction,

    /// <summary>Read from a promoted column.</summary>
    PhysicalColumn,

    /// <summary>Read from one of the row's own columns.</summary>
    RowColumn,
  }

  public enum Status { Draft, Live, Retired }

  [SuppressIndexAdvisory("the matrix exists to compile every shape, never to run one")]
  public class MatrixModel {
    [StreamId]
    public Guid StreamKey { get; init; }

    // Promoted to real columns.
    [PhysicalField(Indexed = true)]
    public Guid PhysGuid { get; init; }

    [PhysicalField(Indexed = true)]
    public int PhysInt { get; init; }

    [PhysicalField(Unique = true)]
    public string PhysString { get; init; } = string.Empty;

    // JSON-only scalars whose serialized text and PostgreSQL's agree.
    public string Str { get; init; } = string.Empty;
    public Guid Gid { get; init; }
    public bool Flag { get; init; }
    public short Small { get; init; }
    public int Num { get; init; }
    public long Big { get; init; }
    public decimal Money { get; init; }

    // JSON-only, but their two text forms are not guaranteed to agree.
    public double Dbl { get; init; }
    public float Flt { get; init; }
    public DateTime When { get; init; }
    public DateTimeOffset WhenOffset { get; init; }
    public Status State { get; init; }

    // Nullable.
    public string? MaybeStr { get; init; }
    public Guid? MaybeGid { get; init; }
    public int? MaybeNum { get; init; }

    public NestedModel Inner { get; init; } = new();
  }

  public class NestedModel {
    public string City { get; init; } = string.Empty;
    public int Floor { get; init; }
    public DeeperModel Deeper { get; init; } = new();
  }

  public class DeeperModel {
    public Guid Marker { get; init; }
  }

  private sealed class MatrixDbContext(DbContextOptions<MatrixDbContext> options) : DbContext(options) {
    protected override void OnModelCreating(ModelBuilder modelBuilder) {
      modelBuilder.Entity<PerspectiveRow<MatrixModel>>(entity => {
        entity.ToTable("wh_per_matrix");
        entity.HasKey(e => e.Id);
        entity.Property(e => e.Id).HasColumnName("id");

        entity.ComplexProperty(e => e.Data, d => {
          d.ToJson("data");
          d.ComplexProperty(p => p.Inner, i => i.ComplexProperty(p => p.Deeper));
        });
        entity.ComplexProperty(e => e.Metadata, m => m.ToJson("metadata"));
        entity.ComplexProperty(e => e.Scope, s => {
          s.ToJson("scope");
          s.ComplexCollection(p => p.Extensions, ex => ex.HasJsonPropertyName("ex"));
        });

        entity.Property(e => e.CreatedAt).HasColumnName("created_at").IsRequired();
        entity.Property(e => e.UpdatedAt).HasColumnName("updated_at").IsRequired();
        entity.Property(e => e.Version).HasColumnName("version").IsRequired();

        entity.Property<Guid>("phys_guid").HasColumnName("phys_guid");
        entity.Property<int>("phys_int").HasColumnName("phys_int");
        entity.Property<string?>("phys_string").HasColumnName("phys_string");
      });

      modelBuilder.UseWhizbangJsonbContainment();
    }
  }

  private static MatrixDbContext _newContext() {
    PhysicalFieldRegistry.Register<MatrixModel>("PhysGuid", "phys_guid");
    PhysicalFieldRegistry.Register<MatrixModel>("PhysInt", "phys_int");
    PhysicalFieldRegistry.Register<MatrixModel>("PhysString", "phys_string");

    return new MatrixDbContext(new DbContextOptionsBuilder<MatrixDbContext>()
      .UseNpgsql(UNUSED_CONNECTION)
      .UseWhizbangPhysicalFields()
      .Options);
  }

  private delegate IQueryable<PerspectiveRow<MatrixModel>> Shape(IQueryable<PerspectiveRow<MatrixModel>> rows);

  private static readonly Dictionary<string, (Shape Shape, Destination Expected)> _matrix = _buildMatrix();

  // ========================================
  // The matrix
  // ========================================

  private static Dictionary<string, (Shape, Destination)> _buildMatrix() {
    var cases = new Dictionary<string, (Shape, Destination)>(StringComparer.Ordinal);

    void Add(string key, Shape shape, Destination expected) => cases[key] = (shape, expected);

    // --- Equality on a JSON-only scalar whose text forms agree: containment, both operand orders,
    // --- constant and parameter, and wrapped in each query shape that keeps an IQueryable.
    var eligible = new (string Name, Func<bool, Shape> Build)[] {
      ("string",  reversed => reversed ? r => r.Where(x => "v" == x.Data.Str)               : r => r.Where(x => x.Data.Str == "v")),
      ("guid",    reversed => reversed ? r => r.Where(x => _probeGuid == x.Data.Gid)        : r => r.Where(x => x.Data.Gid == _probeGuid)),
      ("bool",    reversed => reversed ? r => r.Where(x => true == x.Data.Flag)             : r => r.Where(x => x.Data.Flag == true)),
      ("short",   reversed => reversed ? r => r.Where(x => (short)1 == x.Data.Small)        : r => r.Where(x => x.Data.Small == (short)1)),
      ("int",     reversed => reversed ? r => r.Where(x => 1 == x.Data.Num)                 : r => r.Where(x => x.Data.Num == 1)),
      ("long",    reversed => reversed ? r => r.Where(x => 1L == x.Data.Big)                : r => r.Where(x => x.Data.Big == 1L)),
      ("decimal", reversed => reversed ? r => r.Where(x => 1.5m == x.Data.Money)            : r => r.Where(x => x.Data.Money == 1.5m)),
    };

    foreach (var (name, build) in eligible) {
      foreach (var reversed in new[] { false, true }) {
        var order = reversed ? "value-first" : "member-first";
        Add($"eligible/{name}/{order}/const", build(reversed), Destination.Containment);
      }
    }

    // Parameter-valued equality, which is what a repository method actually produces.
    foreach (var (name, build) in _eligibleParameterShapes()) {
      Add($"eligible/{name}/parameter", build, Destination.Containment);
    }

    // The same predicate under every query shape that still yields an IQueryable.
    var wrappers = new (string Name, Func<Shape, Shape> Wrap)[] {
      ("where", inner => rows => inner(rows)),
      ("ordered", inner => rows => inner(rows).OrderBy(x => x.Id)),
      ("ordered-then", inner => rows => inner(rows).OrderBy(x => x.Id).ThenByDescending(x => x.Version)),
      ("paged", inner => rows => inner(rows).Skip(10).Take(5)),
      ("distinct", inner => rows => inner(rows).Distinct()),
      ("double-filtered", inner => rows => inner(rows).Where(x => x.Version > 0)),
    };

    foreach (var (typeName, build) in eligible) {
      foreach (var (wrapperName, wrap) in wrappers) {
        Add($"shape/{wrapperName}/{typeName}", wrap(build(false)), Destination.Containment);
      }
    }

    // --- Types whose serialized form and PostgreSQL's are not guaranteed to agree: extraction.
    Add("ineligible/double", rows => rows.Where(x => x.Data.Dbl == 1.5d), Destination.Extraction);
    Add("ineligible/float", rows => rows.Where(x => x.Data.Flt == 1.5f), Destination.Extraction);
    Add("ineligible/datetime", rows => rows.Where(x => x.Data.When == _probeDate), Destination.Extraction);
    Add("ineligible/datetimeoffset", rows => rows.Where(x => x.Data.WhenOffset == _probeOffset), Destination.Extraction);
    Add("ineligible/enum", rows => rows.Where(x => x.Data.State == Status.Live), Destination.Extraction);

    // --- Nullable members: containment for a non-null comparison, extraction for a null one.
    Add("nullable/string/value", rows => rows.Where(x => x.Data.MaybeStr == "v"), Destination.Containment);
    Add("nullable/guid/value", rows => rows.Where(x => x.Data.MaybeGid == _probeGuid), Destination.Containment);
    Add("nullable/int/value", rows => rows.Where(x => x.Data.MaybeNum == 1), Destination.Containment);
    Add("nullable/string/null", rows => rows.Where(x => x.Data.MaybeStr == null), Destination.Extraction);
    Add("nullable/guid/null", rows => rows.Where(x => x.Data.MaybeGid == null), Destination.Extraction);
    Add("nullable/int/null", rows => rows.Where(x => x.Data.MaybeNum == null), Destination.Extraction);

    // --- Promoted fields keep reading their column, whatever the operator.
    Add("physical/guid/equal", rows => rows.Where(x => x.Data.PhysGuid == _probeGuid), Destination.PhysicalColumn);
    Add("physical/int/equal", rows => rows.Where(x => x.Data.PhysInt == 1), Destination.PhysicalColumn);
    Add("physical/int/range", rows => rows.Where(x => x.Data.PhysInt > 1), Destination.PhysicalColumn);
    Add("physical/string/equal", rows => rows.Where(x => x.Data.PhysString == "v"), Destination.PhysicalColumn);
    Add("physical/string/like", rows => rows.Where(x => x.Data.PhysString.Contains("val")), Destination.PhysicalColumn);
    Add("physical/int/ordered", rows => rows.OrderBy(x => x.Data.PhysInt), Destination.PhysicalColumn);

    // --- Operators containment cannot express, per numeric type.
    var numerics = new (string Name, Shape[] Shapes)[] {
      ("short", [
        rows => rows.Where(x => x.Data.Small != (short)1),
        rows => rows.Where(x => x.Data.Small > (short)1),
        rows => rows.Where(x => x.Data.Small >= (short)1),
        rows => rows.Where(x => x.Data.Small < (short)1),
        rows => rows.Where(x => x.Data.Small <= (short)1),
      ]),
      ("int", [
        rows => rows.Where(x => x.Data.Num != 1),
        rows => rows.Where(x => x.Data.Num > 1),
        rows => rows.Where(x => x.Data.Num >= 1),
        rows => rows.Where(x => x.Data.Num < 1),
        rows => rows.Where(x => x.Data.Num <= 1),
      ]),
      ("long", [
        rows => rows.Where(x => x.Data.Big != 1L),
        rows => rows.Where(x => x.Data.Big > 1L),
        rows => rows.Where(x => x.Data.Big >= 1L),
        rows => rows.Where(x => x.Data.Big < 1L),
        rows => rows.Where(x => x.Data.Big <= 1L),
      ]),
      ("decimal", [
        rows => rows.Where(x => x.Data.Money != 1.5m),
        rows => rows.Where(x => x.Data.Money > 1.5m),
        rows => rows.Where(x => x.Data.Money >= 1.5m),
        rows => rows.Where(x => x.Data.Money < 1.5m),
        rows => rows.Where(x => x.Data.Money <= 1.5m),
      ]),
    };

    var operatorNames = new[] { "not-equal", "greater", "greater-or-equal", "less", "less-or-equal" };
    foreach (var (name, shapes) in numerics) {
      for (var i = 0; i < shapes.Length; i++) {
        Add($"operator/{name}/{operatorNames[i]}", shapes[i], Destination.Extraction);
      }
    }

    Add("operator/string/not-equal", rows => rows.Where(x => x.Data.Str != "v"), Destination.Extraction);
    Add("operator/string/contains", rows => rows.Where(x => x.Data.Str.Contains("val")), Destination.Extraction);
    Add("operator/string/starts-with", rows => rows.Where(x => x.Data.Str.StartsWith("val")), Destination.Extraction);
    Add("operator/string/ends-with", rows => rows.Where(x => x.Data.Str.EndsWith("val")), Destination.Extraction);
    Add("operator/string/length", rows => rows.Where(x => x.Data.Str.Length > 3), Destination.Extraction);
    Add("operator/guid/not-equal", rows => rows.Where(x => x.Data.Gid != _probeGuid), Destination.Extraction);
    Add("operator/bool/negated", rows => rows.Where(x => !x.Data.Flag), Destination.Extraction);
    Add("operator/string/ordered", rows => rows.OrderBy(x => x.Data.Str), Destination.Extraction);
    Add("operator/int/ordered-descending", rows => rows.OrderByDescending(x => x.Data.Num), Destination.Extraction);

    // --- Nested members: containment nests too.
    Add("nested/string", rows => rows.Where(x => x.Data.Inner.City == "v"), Destination.Containment);
    Add("nested/int", rows => rows.Where(x => x.Data.Inner.Floor == 3), Destination.Containment);
    Add("nested/two-levels", rows => rows.Where(x => x.Data.Inner.Deeper.Marker == _probeGuid), Destination.Containment);
    Add("nested/range", rows => rows.Where(x => x.Data.Inner.Floor > 3), Destination.Extraction);
    Add("nested/ordered", rows => rows.OrderBy(x => x.Data.Inner.City), Destination.Extraction);

    // --- Composition.
    Add("compose/and-two-eligible",
      rows => rows.Where(x => x.Data.Str == "v" && x.Data.Num == 1), Destination.Containment);
    Add("compose/or-two-eligible",
      rows => rows.Where(x => x.Data.Str == "v" || x.Data.Num == 1), Destination.Containment);
    Add("compose/and-three-eligible",
      rows => rows.Where(x => x.Data.Str == "v" && x.Data.Num == 1 && x.Data.Gid == _probeGuid), Destination.Containment);
    Add("compose/eligible-and-physical",
      rows => rows.Where(x => x.Data.Str == "v" && x.Data.PhysInt == 1), Destination.Containment);
    Add("compose/eligible-and-row-column",
      rows => rows.Where(x => x.Data.Str == "v" && x.Version > 1), Destination.Containment);
    Add("compose/chained-where",
      rows => rows.Where(x => x.Data.Str == "v").Where(x => x.Data.Num == 1), Destination.Containment);
    Add("compose/negated-eligible",
      rows => rows.Where(x => !(x.Data.Str == "v")), Destination.Extraction);
    Add("compose/negated-nested",
      rows => rows.Where(x => !(x.Data.Inner.City == "v")), Destination.Extraction);
    Add("compose/negated-guid",
      rows => rows.Where(x => !(x.Data.Gid == _probeGuid)), Destination.Extraction);
    Add("compose/negated-around-and",
      rows => rows.Where(x => !(x.Data.Str == "v" && x.Data.Num == 1)), Destination.Extraction);
    Add("compose/negation-beside-positive",
      rows => rows.Where(x => !(x.Data.Str == "v") || x.Data.Num == 1), Destination.Containment);
    Add("compose/eligible-and-range",
      rows => rows.Where(x => x.Data.Str == "v" && x.Data.Num > 1), Destination.Containment);

    // --- The row's own columns are untouched by any of this.
    Add("row/id", rows => rows.Where(x => x.Id == _probeGuid), Destination.RowColumn);
    Add("row/version", rows => rows.Where(x => x.Version == 1), Destination.RowColumn);
    Add("row/updated-at", rows => rows.Where(x => x.UpdatedAt > _probeDate), Destination.RowColumn);
    Add("row/created-at-ordered", rows => rows.OrderBy(x => x.CreatedAt), Destination.RowColumn);

    // --- Query syntax is the same tree in different clothes.
    Add("query-syntax/where-eligible",
      rows => from x in rows where x.Data.Str == "v" select x, Destination.Containment);
    Add("query-syntax/where-range",
      rows => from x in rows where x.Data.Num > 1 select x, Destination.Extraction);
    Add("query-syntax/orderby-eligible",
      rows => from x in rows where x.Data.Gid == _probeGuid orderby x.Version select x, Destination.Containment);

    return cases;
  }

  private static IEnumerable<(string Name, Shape Build)> _eligibleParameterShapes() {
    var s = "v";
    var g = _probeGuid;
    var b = true;
    short sh = 1;
    var i = 1;
    var l = 1L;
    var m = 1.5m;

    yield return ("string", rows => rows.Where(x => x.Data.Str == s));
    yield return ("guid", rows => rows.Where(x => x.Data.Gid == g));
    yield return ("bool", rows => rows.Where(x => x.Data.Flag == b));
    yield return ("short", rows => rows.Where(x => x.Data.Small == sh));
    yield return ("int", rows => rows.Where(x => x.Data.Num == i));
    yield return ("long", rows => rows.Where(x => x.Data.Big == l));
    yield return ("decimal", rows => rows.Where(x => x.Data.Money == m));
  }

  private static readonly Guid _probeGuid = new("6f9619ff-8b86-d011-b42d-00cf4fc964ff");
  private static readonly DateTime _probeDate = new(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc);
  private static readonly DateTimeOffset _probeOffset = new(2026, 1, 1, 0, 0, 0, TimeSpan.Zero);

  // ========================================
  // The test
  // ========================================

  /// <summary>Every case in the matrix, as (key, expected destination).</summary>
  /// <returns>One tuple per case.</returns>
  public static IEnumerable<(string CaseKey, Destination Expected)> Cases() =>
    _matrix.OrderBy(kv => kv.Key, StringComparer.Ordinal)
           .Select(kv => (kv.Key, kv.Value.Expected));

  /// <summary>
  /// Compiles the case and asserts the filter landed where it was meant to.
  /// </summary>
  /// <param name="caseKey">The matrix key, which also names the test.</param>
  /// <param name="expected">Where the filter should have gone.</param>
  [Test]
  [MethodDataSource(nameof(Cases))]
  public async Task CompiledSql_SendsTheFilterWhereExpectedAsync(string caseKey, Destination expected) {
    var (shape, _) = _matrix[caseKey];

    using var db = _newContext();
    var sql = shape(db.Set<PerspectiveRow<MatrixModel>>()).ToQueryString();

    var containment = sql.Contains("@>", StringComparison.Ordinal);
    var extraction = sql.Contains("data ->>", StringComparison.Ordinal)
                     || sql.Contains("data ->", StringComparison.Ordinal)
                     || sql.Contains("data #>>", StringComparison.Ordinal)
                     || sql.Contains("data #>", StringComparison.Ordinal);

    switch (expected) {
      case Destination.Containment:
        await Assert.That(containment).IsTrue();
        await Assert.That(sql).Contains("jsonb_build_object", StringComparison.Ordinal);
        break;

      case Destination.Extraction:
        await Assert.That(extraction).IsTrue();
        await Assert.That(containment).IsFalse();
        break;

      case Destination.PhysicalColumn:
        await Assert.That(containment).IsFalse();
        await Assert.That(extraction).IsFalse();
        await Assert.That(sql.Contains("phys_", StringComparison.Ordinal)).IsTrue();
        break;

      case Destination.RowColumn:
        await Assert.That(containment).IsFalse();
        await Assert.That(extraction).IsFalse();
        break;

      default:
        throw new InvalidOperationException($"Unhandled destination {expected}.");
    }
  }

  /// <summary>The matrix is worth having only if it is broad, so its size is asserted too.</summary>
  [Test]
  public async Task Matrix_CoversEveryAxisAsync() {
    await Assert.That(_matrix.Count).IsGreaterThanOrEqualTo(100);

    foreach (var destination in Enum.GetValues<Destination>()) {
      var covered = _matrix.Values.Count(v => v.Expected == destination);
      await Assert.That(covered).IsGreaterThan(0);
    }
  }

  /// <summary>
  /// A model that has not registered the translations keeps the extraction form, so the rewrite can
  /// never be a surprise for a consumer that did not ask for it.
  /// </summary>
  [Test]
  public async Task WithoutRegistration_TheRewriteStandsDownAsync() {
    using var db = new UnregisteredDbContext(new DbContextOptionsBuilder<UnregisteredDbContext>()
      .UseNpgsql(UNUSED_CONNECTION)
      .UseWhizbangPhysicalFields()
      .Options);

    var sql = db.Set<PerspectiveRow<MatrixModel>>().Where(x => x.Data.Str == "v").ToQueryString();

    await Assert.That(sql).Contains("data ->>", StringComparison.Ordinal);
    await Assert.That(sql).DoesNotContain("@>", StringComparison.Ordinal);
  }

  private sealed class UnregisteredDbContext(DbContextOptions<UnregisteredDbContext> options) : DbContext(options) {
    protected override void OnModelCreating(ModelBuilder modelBuilder) =>
      modelBuilder.Entity<PerspectiveRow<MatrixModel>>(entity => {
        entity.ToTable("wh_per_matrix");
        entity.HasKey(e => e.Id);
        entity.Property(e => e.Id).HasColumnName("id");
        entity.ComplexProperty(e => e.Data, d => {
          d.ToJson("data");
          d.ComplexProperty(p => p.Inner, i => i.ComplexProperty(p => p.Deeper));
        });
        entity.ComplexProperty(e => e.Metadata, m => m.ToJson("metadata"));
        entity.ComplexProperty(e => e.Scope, s => {
          s.ToJson("scope");
          s.ComplexCollection(p => p.Extensions, ex => ex.HasJsonPropertyName("ex"));
        });
        entity.Property(e => e.CreatedAt).HasColumnName("created_at").IsRequired();
        entity.Property(e => e.UpdatedAt).HasColumnName("updated_at").IsRequired();
        entity.Property(e => e.Version).HasColumnName("version").IsRequired();
        entity.Property<Guid>("phys_guid").HasColumnName("phys_guid");
        entity.Property<int>("phys_int").HasColumnName("phys_int");
        entity.Property<string?>("phys_string").HasColumnName("phys_string");
      });
  }

  /// <summary>Records the SQL for every case, so a reviewer can read what the matrix actually asserts.</summary>
  [Test]
  public async Task Matrix_IsRecordedForReviewAsync() {
    var target = Environment.GetEnvironmentVariable("WHIZ_MATRIX_DUMP");
    if (string.IsNullOrWhiteSpace(target)) {
      return;
    }

    using var db = _newContext();
    var sink = new System.Text.StringBuilder();
    foreach (var (key, (shape, expected)) in _matrix.OrderBy(kv => kv.Key, StringComparer.Ordinal)) {
      sink.AppendLine(CultureInfo.InvariantCulture, $"##### {key}  [{expected}]");
      sink.AppendLine(shape(db.Set<PerspectiveRow<MatrixModel>>()).ToQueryString());
      sink.AppendLine();
    }

    await File.WriteAllTextAsync(target, sink.ToString());
  }
}
