using ECommerce.BFF.API.Hubs;
using ECommerce.BFF.API.Lenses;
using ECommerce.BFF.API.Perspectives;
using ECommerce.Contracts.Events;
using ECommerce.Contracts.Generated;
using FastEndpoints;
using FastEndpoints.Swagger;
using Whizbang.Core;
using Whizbang.Core.Generated;
using Whizbang.Core.Observability;
using Whizbang.Core.Workers;
using Whizbang.Data.Dapper.Postgres;
using Whizbang.Transports.AzureServiceBus;

var builder = WebApplication.CreateBuilder(args);

// Add service defaults (telemetry, health checks, service discovery)
builder.AddServiceDefaults();

// Get connection strings from Aspire configuration
var postgresConnection = builder.Configuration.GetConnectionString("bffdb")
    ?? throw new InvalidOperationException("PostgreSQL connection string 'bffdb' not found");
var serviceBusConnection = builder.Configuration.GetConnectionString("servicebus")
    ?? throw new InvalidOperationException("Azure Service Bus connection string 'servicebus' not found");

// Register Whizbang Postgres stores (inbox, outbox, read models)
builder.Services.AddWhizbangPostgres(postgresConnection);
builder.Services.AddWhizbangPostgresHealthChecks();

// Register Azure Service Bus transport
builder.Services.AddAzureServiceBusTransport(serviceBusConnection, ECommerce.Contracts.Generated.WhizbangJsonContext.Default);
builder.Services.AddAzureServiceBusHealthChecks();

// Add trace store for observability
builder.Services.AddSingleton<ITraceStore, InMemoryTraceStore>();

// Register all discovered perspectives (source-generated)
// Perspectives are registered as Scoped services via AddWhizbangPerspectives()
builder.Services.AddWhizbangPerspectives();

// TODO: Implement Dispatcher → Event Store → Perspectives integration
// ARCHITECTURAL DECISION:
// - Dispatcher sends ALL events to Event Store
// - Event Store determines which perspectives to invoke
// - Source generator creates the wiring (zero-reflection, designed for speed)
//
// FUTURE ENHANCEMENT:
// - Auto-generate perspective tables using JSONB approach (MartenDB style)
// - Multiple JSONB fields: metadata (envelope), model_data, permissions
// - Fixed columns: id, created_date, updated_date, tenant_id
// - No manual migrations - all generated by core library
// - Research performance impact of multiple JSONB fields

// Register lenses (readonly repositories)
builder.Services.AddScoped<IOrderLens, OrderLens>();

// Register outbox publisher worker for reliable event publishing
builder.Services.AddHostedService<OutboxPublisherWorker>();

// TODO: Re-enable after figuring out perspective integration with dispatcher
// Service Bus consumer - receives ALL events from all services
// var consumerOptions = new ServiceBusConsumerOptions();
// consumerOptions.Subscriptions.Add(new TopicSubscription("orders", "bff-service"));
// builder.Services.AddSingleton(consumerOptions);
// builder.Services.AddHostedService<ServiceBusConsumerWorker>();

// Add FastEndpoints for REST API (AOT-compatible)
builder.Services.AddFastEndpoints();
builder.Services.SwaggerDocument();

// Add SignalR for real-time client updates (AOT-compatible with typed hub)
builder.Services.AddSignalR()
  .AddJsonProtocol(options => {
    // Use source-generated JSON context for AOT compatibility
    options.PayloadSerializerOptions = ECommerce.Contracts.Generated.WhizbangJsonContext.CreateOptions();
  });

// Add CORS for Angular development
builder.Services.AddCors(options => {
  options.AddDefaultPolicy(policy => {
    policy.WithOrigins("http://localhost:4200")  // Angular dev server
      .AllowAnyHeader()
      .AllowAnyMethod()
      .AllowCredentials();  // Required for SignalR
  });
});

var app = builder.Build();

// Configure the HTTP request pipeline
if (app.Environment.IsDevelopment()) {
  app.UseDeveloperExceptionPage();
  app.UseSwaggerGen(); // FastEndpoints Swagger UI
}

app.UseHttpsRedirection();

// Enable CORS before other middleware
app.UseCors();

// FastEndpoints (REST API)
app.UseFastEndpoints(config => {
  config.Endpoints.RoutePrefix = "api";
});

// Map SignalR hub
app.MapHub<OrderStatusHub>("/hubs/order-status");

// Aspire health checks and diagnostics
app.MapDefaultEndpoints();

app.Run();
