#region HEADER
// <auto-generated/>
// Generated at: __TIMESTAMP__
// This file was generated by Whizbang.Transports.FastEndpoints.Generators
// DO NOT EDIT - Changes will be overwritten
#endregion
#nullable enable

using FastEndpoints;
using Microsoft.EntityFrameworkCore;
using Whizbang.Core.Lenses;
using Whizbang.Transports.FastEndpoints;

namespace __NAMESPACE__;

#region ENDPOINT_CLASSES
// Endpoint classes will be generated here
#endregion

/// <summary>
/// Diagnostic information about Whizbang REST lens endpoint discovery.
/// </summary>
public static class WhizbangRestLensDiagnostics {
  /// <summary>
  /// Gets the name of the generator that produced this code.
  /// </summary>
  public static string GeneratorName => "RestLensEndpointGenerator";

  /// <summary>
  /// Gets the timestamp when the code was generated.
  /// </summary>
  public static string GeneratedTimestamp => "__TIMESTAMP__";

  /// <summary>
  /// Gets the total count of discovered lenses.
  /// </summary>
  public static int DiscoveredLensCount => __LENS_COUNT__;

  #region LENS_INFO_PROPERTIES
  // Individual lens info properties will be generated here
  #endregion
}
