#region HEADER
// <auto-generated/>
// Generated at: __TIMESTAMP__
// This file was generated by Whizbang.Transports.FastEndpoints.Generators
// DO NOT EDIT - Changes will be overwritten
#endregion
#nullable enable

using FastEndpoints;
using Whizbang.Core;
using Whizbang.Transports.FastEndpoints;
using Whizbang.Transports.Mutations;

namespace __NAMESPACE__;

#region ENDPOINT_CLASSES
// Endpoint classes will be generated here
#endregion

/// <summary>
/// Diagnostic information about Whizbang REST mutation endpoint discovery.
/// </summary>
public static class WhizbangRestMutationDiagnostics {
  /// <summary>
  /// Gets the name of the generator that produced this code.
  /// </summary>
  public static string GeneratorName => "RestMutationEndpointGenerator";

  /// <summary>
  /// Gets the timestamp when the code was generated.
  /// </summary>
  public static string GeneratedTimestamp => "__TIMESTAMP__";

  /// <summary>
  /// Gets the total count of discovered mutations.
  /// </summary>
  public static int DiscoveredMutationCount => __MUTATION_COUNT__;

  #region MUTATION_INFO_PROPERTIES
  // Individual mutation info properties will be generated here
  #endregion
}
