using Microsoft.Extensions.Logging.Abstractions;
using TUnit.Assertions;
using TUnit.Core;
using Whizbang.Core.Diagnostics;
using Whizbang.Core.Messaging;
using Whizbang.Core.Perspectives.Sync;

namespace Whizbang.Core.Tests.Perspectives.Sync;

/// <summary>
/// BUG REPRODUCTION TESTS: These tests simulate the EXACT real-world cross-scope scenario
/// that is failing in production.
///
/// The scenario:
/// 1. Request 1: StartActivityCommandHandler returns Route.Local(StartedEvent)
///    - Event is stored in wh_event_store
///    - wh_perspective_events row is created with processed_at = NULL
/// 2. Request 2: RequestActivityStatusCommandHandler has [AwaitPerspectiveSync]
///    - WaitForStreamAsync is called
///    - EXPECTED: Handler should WAIT until event is processed
///    - ACTUAL BUG: Handler fires immediately!
///
/// The bug: The handler fires BEFORE the perspective has processed the event.
/// This means WaitForStreamAsync is returning "Synced" incorrectly.
/// </summary>
public class RealWorldCrossScopeBugReproductionTests {

  // ==================================================================================
  // Simulated event types - these need to have FullName and Assembly like real types
  // ==================================================================================
  public record SimulatedStartedEvent;
  public record SimulatedCompletedEvent;

  /// <summary>
  /// BUG REPRODUCTION TEST #1:
  /// This test simulates the EXACT scenario where the bug occurs.
  ///
  /// Setup:
  /// - Event EXISTS in wh_event_store (Request 1 stored it)
  /// - Event EXISTS in wh_perspective_events with processed_at = NULL (worker created it)
  /// - Perspective has NOT yet called Apply() (processed_at is still NULL)
  ///
  /// Expected behavior:
  /// - WaitForStreamAsync should return TimedOut (or keep polling)
  /// - Handler should NOT fire until event is processed
  ///
  /// Actual bug:
  /// - WaitForStreamAsync returns Synced immediately
  /// - Handler fires before perspective processes the event
  /// </summary>
  [Test]
  public async Task BUGREPRO_CrossScope_EventPendingInPerspective_ShouldNotReturnSyncedAsync() {
    // Arrange
    var streamId = Guid.NewGuid();
    var eventId = Guid.NewGuid();
    var perspectiveName = typeof(FakeProjection).FullName!;

    // Track what EventTypeFilter is generated by the awaiter
    string[]? capturedEventTypeFilter = null;
    var queryCount = 0;

    // Mock coordinator that simulates:
    // - Event IS in wh_event_store
    // - Event IS in wh_perspective_events with processed_at = NULL (PENDING)
    var mockCoordinator = new MockWorkCoordinator((request, _) => {
      queryCount++;
      var inquiry = request.PerspectiveSyncInquiries?.FirstOrDefault();
      capturedEventTypeFilter = inquiry?.EventTypeFilter;

      // Simulate: Event discovered, but NOT YET PROCESSED
      // This is the state AFTER Request 1 completes but BEFORE worker processes
      return Task.FromResult(new WorkBatch {
        OutboxWork = [],
        InboxWork = [],
        PerspectiveWork = [],
        SyncInquiryResults = [
          new SyncInquiryResult {
            InquiryId = inquiry?.InquiryId ?? Guid.NewGuid(),
            StreamId = streamId,
            PendingCount = 1,      // Event is PENDING
            ProcessedCount = 0,     // NOT processed yet
            PendingEventIds = [eventId],
            ProcessedEventIds = []
          }
        ]
      });
    });

    var clock = new DebuggerAwareClock();
    var logger = NullLogger<PerspectiveSyncAwaiter>.Instance;

    // NO tracker - this simulates Request 2 which is a DIFFERENT scope
    var awaiter = new PerspectiveSyncAwaiter(mockCoordinator, clock, logger, tracker: null);

    // Act - Call WaitForStreamAsync exactly as [AwaitPerspectiveSync] does
    var result = await awaiter.WaitForStreamAsync(
      typeof(FakeProjection),
      streamId,
      [typeof(SimulatedStartedEvent)],
      timeout: TimeSpan.FromMilliseconds(300)  // Short timeout for test
    );

    // Assert - THIS IS THE KEY ASSERTION
    // If the bug exists, result.Outcome will be Synced (WRONG!)
    // If the bug is fixed, result.Outcome should be TimedOut (CORRECT - event is pending)
    await Assert.That(result.Outcome)
      .IsEqualTo(SyncOutcome.TimedOut)
      .Because(
        "Event is PENDING (exists but processed_at=NULL), so sync should time out waiting. " +
        "If this test FAILS with Outcome=Synced, the BUG exists - handler will fire too early!");

    // Verify we actually polled the database multiple times (waiting behavior)
    await Assert.That(queryCount).IsGreaterThan(1)
      .Because("We should poll multiple times while waiting for the event to be processed");

    // Verify the EventTypeFilter was generated correctly
    await Assert.That(capturedEventTypeFilter).IsNotNull();
    var expectedFormat = $"{typeof(SimulatedStartedEvent).FullName}, {typeof(SimulatedStartedEvent).Assembly.GetName().Name}";
    await Assert.That(capturedEventTypeFilter![0]).IsEqualTo(expectedFormat)
      .Because("EventTypeFilter must include assembly name to match stored format");
  }

  /// <summary>
  /// BUG REPRODUCTION TEST #2:
  /// What happens when SQL returns NO result rows?
  ///
  /// This could happen if:
  /// - EventTypeFilter doesn't match stored format (the bug I fixed earlier)
  /// - No events exist for the stream
  ///
  /// The question: Does WaitForStreamAsync interpret "no results" as "synced"?
  /// </summary>
  [Test]
  public async Task BUGREPRO_CrossScope_NoSQLResults_ShouldNotReturnSyncedAsync() {
    // Arrange
    var streamId = Guid.NewGuid();
    var queryCount = 0;

    // Mock coordinator that returns EMPTY results (simulating EventTypeFilter mismatch)
    var mockCoordinator = new MockWorkCoordinator((request, _) => {
      queryCount++;

      // Return NO sync results - this simulates what happens when EventTypeFilter doesn't match
      return Task.FromResult(new WorkBatch {
        OutboxWork = [],
        InboxWork = [],
        PerspectiveWork = [],
        SyncInquiryResults = []  // EMPTY - no results
      });
    });

    var clock = new DebuggerAwareClock();
    var logger = NullLogger<PerspectiveSyncAwaiter>.Instance;
    var awaiter = new PerspectiveSyncAwaiter(mockCoordinator, clock, logger, tracker: null);

    // Act
    var result = await awaiter.WaitForStreamAsync(
      typeof(FakeProjection),
      streamId,
      [typeof(SimulatedStartedEvent)],
      timeout: TimeSpan.FromMilliseconds(300)
    );

    // Assert - What happens with no results?
    // If we get Synced, that's potentially wrong behavior when events SHOULD exist
    // This test documents the current behavior
    Console.WriteLine($"Result when SQL returns no rows: {result.Outcome}");
    Console.WriteLine($"Query count: {queryCount}");

    // The current behavior: no results = keep polling = timeout
    // This is CORRECT because we don't know if events exist or not
    await Assert.That(result.Outcome).IsEqualTo(SyncOutcome.TimedOut)
      .Because("No SQL results should NOT be interpreted as 'synced' - we should keep polling");
  }

  /// <summary>
  /// BUG REPRODUCTION TEST #3:
  /// What happens when SQL returns a result with PendingCount = 0 but NO processed events?
  ///
  /// This tests the IsFullySynced logic.
  /// </summary>
  [Test]
  public async Task BUGREPRO_CrossScope_ZeroPendingZeroProcessed_ChecksBehaviorAsync() {
    // Arrange
    var streamId = Guid.NewGuid();

    // Mock coordinator that returns: PendingCount=0, ProcessedCount=0
    // This could mean "no events to wait for" OR "events exist but aren't tracked yet"
    var mockCoordinator = new MockWorkCoordinator((request, _) => {
      var inquiry = request.PerspectiveSyncInquiries?.FirstOrDefault();

      return Task.FromResult(new WorkBatch {
        OutboxWork = [],
        InboxWork = [],
        PerspectiveWork = [],
        SyncInquiryResults = [
          new SyncInquiryResult {
            InquiryId = inquiry?.InquiryId ?? Guid.NewGuid(),
            StreamId = streamId,
            PendingCount = 0,
            ProcessedCount = 0,
            PendingEventIds = [],
            ProcessedEventIds = []
          }
        ]
      });
    });

    var clock = new DebuggerAwareClock();
    var logger = NullLogger<PerspectiveSyncAwaiter>.Instance;
    var awaiter = new PerspectiveSyncAwaiter(mockCoordinator, clock, logger, tracker: null);

    // Act
    var result = await awaiter.WaitForStreamAsync(
      typeof(FakeProjection),
      streamId,
      [typeof(SimulatedStartedEvent)],
      timeout: TimeSpan.FromMilliseconds(100)
    );

    // Assert - Document the current behavior
    // With PendingCount=0, IsFullySynced returns true, so we get Synced
    Console.WriteLine($"Result when PendingCount=0, ProcessedCount=0: {result.Outcome}");

    // THIS IS THE BUG PATH!
    // If the EventTypeFilter doesn't match, SQL returns PendingCount=0
    // Then IsFullySynced = (PendingCount == 0) = true
    // Handler fires immediately, but events actually DO exist!
    await Assert.That(result.Outcome).IsEqualTo(SyncOutcome.Synced)
      .Because("Current behavior: PendingCount=0 returns Synced - THIS IS WHERE THE BUG MANIFESTS!");
  }

  /// <summary>
  /// VERIFICATION: Confirm the EventTypeFilter format is correct.
  /// </summary>
  [Test]
  public async Task VERIFY_EventTypeFilter_HasCorrectFormatAsync() {
    var streamId = Guid.NewGuid();
    string[]? capturedFilter = null;

    var mockCoordinator = new MockWorkCoordinator((request, _) => {
      capturedFilter = request.PerspectiveSyncInquiries?.FirstOrDefault()?.EventTypeFilter;
      return Task.FromResult(new WorkBatch {
        OutboxWork = [],
        InboxWork = [],
        PerspectiveWork = [],
        SyncInquiryResults = [
          new SyncInquiryResult {
            InquiryId = Guid.NewGuid(),
            StreamId = streamId,
            PendingCount = 0,
            ProcessedCount = 0
          }
        ]
      });
    });

    var clock = new DebuggerAwareClock();
    var logger = NullLogger<PerspectiveSyncAwaiter>.Instance;
    var awaiter = new PerspectiveSyncAwaiter(mockCoordinator, clock, logger, tracker: null);

    await awaiter.WaitForStreamAsync(
      typeof(FakeProjection),
      streamId,
      [typeof(SimulatedStartedEvent), typeof(SimulatedCompletedEvent)],
      timeout: TimeSpan.FromMilliseconds(50)
    );

    // Verify format
    await Assert.That(capturedFilter).IsNotNull();
    await Assert.That(capturedFilter!.Length).IsEqualTo(2);

    var expected1 = $"{typeof(SimulatedStartedEvent).FullName}, {typeof(SimulatedStartedEvent).Assembly.GetName().Name}";
    var expected2 = $"{typeof(SimulatedCompletedEvent).FullName}, {typeof(SimulatedCompletedEvent).Assembly.GetName().Name}";

    await Assert.That(capturedFilter[0]).IsEqualTo(expected1);
    await Assert.That(capturedFilter[1]).IsEqualTo(expected2);

    // Print for debugging
    Console.WriteLine($"Filter[0]: {capturedFilter[0]}");
    Console.WriteLine($"Filter[1]: {capturedFilter[1]}");
  }
}
